# frozen_string_literal: true

# Autogenerated migration to convert asset_creation_parents to utf8mb4
class MigrateAssetCreationParentsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('asset_creation_parents', from: 'utf8', to: 'utf8mb4')
  end
end
