# frozen_string_literal: true

# Autogenerated migration to convert lots to utf8mb4
class MigrateLotsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('lots', from: 'utf8', to: 'utf8mb4')
  end
end
