# frozen_string_literal: true

# Autogenerated migration to convert billing_product_catalogues to utf8mb4
class MigrateBillingProductCataloguesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('billing_product_catalogues', from: 'latin1', to: 'utf8mb4')
  end
end
