# frozen_string_literal: true

# Autogenerated migration to convert batch_requests to utf8mb4
class MigrateBatchRequestsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('batch_requests', from: 'latin1', to: 'utf8mb4')
  end
end
