# frozen_string_literal: true

# Autogenerated migration to convert plate_creators to utf8mb4
class MigratePlateCreatorsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('plate_creators', from: 'latin1', to: 'utf8mb4')
  end
end
