# frozen_string_literal: true

# Autogenerated migration to convert state_changes to utf8mb4
class MigrateStateChangesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('state_changes', from: 'latin1', to: 'utf8mb4')
  end
end
