# frozen_string_literal: true

# Autogenerated migration to convert aker_jobs to utf8mb4
class MigrateAkerJobsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('aker_jobs', from: 'latin1', to: 'utf8mb4')
  end
end
