# frozen_string_literal: true

# Autogenerated migration to convert pac_bio_library_tube_metadata to utf8mb4
class MigratePacBioLibraryTubeMetadataToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('pac_bio_library_tube_metadata', from: 'latin1', to: 'utf8mb4')
  end
end
