# frozen_string_literal: true

# Autogenerated migration to convert well_links to utf8mb4
class MigrateWellLinksToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('well_links', from: 'latin1', to: 'utf8mb4')
  end
end
