# frozen_string_literal: true

# Autogenerated migration to convert robot_properties to utf8mb4
class MigrateRobotPropertiesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('robot_properties', from: 'latin1', to: 'utf8mb4')
  end
end
