# frozen_string_literal: true

# Autogenerated migration to convert barcode_prefixes to utf8mb4
class MigrateBarcodePrefixesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('barcode_prefixes', from: 'latin1', to: 'utf8mb4')
  end
end
