# frozen_string_literal: true

# Autogenerated migration to convert qc_metric_requests to utf8mb4
class MigrateQcMetricRequestsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('qc_metric_requests', from: 'latin1', to: 'utf8mb4')
  end
end
