# frozen_string_literal: true

# Autogenerated migration to convert billing_products to utf8mb4
class MigrateBillingProductsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('billing_products', from: 'latin1', to: 'utf8mb4')
  end
end
