# frozen_string_literal: true

# Autogenerated migration to convert plate_types to utf8mb4
class MigratePlateTypesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('plate_types', from: 'latin1', to: 'utf8mb4')
  end
end
