# frozen_string_literal: true

# Autogenerated migration to convert product_criteria to utf8mb4
class MigrateProductCriteriaToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('product_criteria', from: 'latin1', to: 'utf8mb4')
  end
end
