# frozen_string_literal: true

# Autogenerated migration to convert product_lines to utf8mb4
class MigrateProductLinesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('product_lines', from: 'latin1', to: 'utf8mb4')
  end
end
