# frozen_string_literal: true

# Autogenerated migration to convert asset_barcodes to utf8mb4
class MigrateAssetBarcodesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('asset_barcodes', from: 'latin1', to: 'utf8mb4')
  end
end
