# frozen_string_literal: true

# Autogenerated migration to convert products to utf8mb4
class MigrateProductsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('products', from: 'latin1', to: 'utf8mb4')
  end
end
