# frozen_string_literal: true

# Autogenerated migration to convert stamp_qcables to utf8mb4
class MigrateStampQcablesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('stamp_qcables', from: 'utf8', to: 'utf8mb4')
  end
end
