# frozen_string_literal: true

# Autogenerated migration to convert sample_manifests to utf8mb4
class MigrateSampleManifestsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('sample_manifests', from: 'latin1', to: 'utf8mb4')
  end
end
