# frozen_string_literal: true

# Autogenerated migration to convert workflow_samples to utf8mb4
class MigrateWorkflowSamplesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('workflow_samples', from: 'latin1', to: 'utf8mb4')
  end
end
