# frozen_string_literal: true

# Autogenerated migration to convert pre_capture_pool_pooled_requests to utf8mb4
class MigratePreCapturePoolPooledRequestsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('pre_capture_pool_pooled_requests', from: 'utf8', to: 'utf8mb4')
  end
end
