# frozen_string_literal: true

# Autogenerated migration to convert request_events to utf8mb4
class MigrateRequestEventsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('request_events', from: 'utf8', to: 'utf8mb4')
  end
end
