# frozen_string_literal: true

# Autogenerated migration to convert permissions to utf8mb4
class MigratePermissionsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('permissions', from: 'latin1', to: 'utf8mb4')
  end
end
