# frozen_string_literal: true

# Autogenerated migration to convert well_to_tube_transfers to utf8mb4
class MigrateWellToTubeTransfersToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('well_to_tube_transfers', from: 'latin1', to: 'utf8mb4')
  end
end
