# frozen_string_literal: true

# Autogenerated migration to convert tasks to utf8mb4
class MigrateTasksToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('tasks', from: 'latin1', to: 'utf8mb4')
  end
end
