# frozen_string_literal: true

# Autogenerated migration to convert sample_manifest_assets to utf8mb4
class MigrateSampleManifestAssetsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('sample_manifest_assets', from: 'latin1', to: 'utf8mb4')
  end
end
