# frozen_string_literal: true

# Autogenerated migration to convert bulk_transfers to utf8mb4
class MigrateBulkTransfersToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('bulk_transfers', from: 'utf8', to: 'utf8mb4')
  end
end
