# frozen_string_literal: true

# Autogenerated migration to convert robots to utf8mb4
class MigrateRobotsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('robots', from: 'latin1', to: 'utf8mb4')
  end
end
