# frozen_string_literal: true

# Autogenerated migration to convert plate_conversions to utf8mb4
class MigratePlateConversionsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('plate_conversions', from: 'utf8', to: 'utf8mb4')
  end
end
