# frozen_string_literal: true

# Autogenerated migration to convert qc_reports to utf8mb4
class MigrateQcReportsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('qc_reports', from: 'latin1', to: 'utf8mb4')
  end
end
