# frozen_string_literal: true

# Autogenerated migration to convert aker_containers to utf8mb4
class MigrateAkerContainersToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('aker_containers', from: 'latin1', to: 'utf8mb4')
  end
end
