# frozen_string_literal: true

# Autogenerated migration to convert sanger_sample_ids to utf8mb4
class MigrateSangerSampleIdsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('sanger_sample_ids', from: 'latin1', to: 'utf8mb4')
  end
end
