# frozen_string_literal: true

# Autogenerated migration to convert request_type_validators to utf8mb4
class MigrateRequestTypeValidatorsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('request_type_validators', from: 'utf8', to: 'utf8mb4')
  end
end
