# frozen_string_literal: true

# Autogenerated migration to convert work_orders to utf8mb4
class MigrateWorkOrdersToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('work_orders', from: 'latin1', to: 'utf8mb4')
  end
end
