# frozen_string_literal: true

# Autogenerated migration to convert uuids to utf8mb4
class MigrateUuidsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('uuids', from: 'latin1', to: 'utf8mb4')
  end
end
