# frozen_string_literal: true

# Autogenerated migration to convert work_completions_submissions to utf8mb4
class MigrateWorkCompletionsSubmissionsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('work_completions_submissions', from: 'latin1', to: 'utf8mb4')
  end
end
