# frozen_string_literal: true

# Autogenerated migration to convert failures to utf8mb4
class MigrateFailuresToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('failures', from: 'latin1', to: 'utf8mb4')
  end
end
