# frozen_string_literal: true

# Autogenerated migration to convert plate_owners to utf8mb4
class MigratePlateOwnersToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('plate_owners', from: 'latin1', to: 'utf8mb4')
  end
end
