# frozen_string_literal: true

# Autogenerated migration to convert pooling_methods to utf8mb4
class MigratePoolingMethodsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('pooling_methods', from: 'utf8', to: 'utf8mb4')
  end
end
