# frozen_string_literal: true

# Autogenerated migration to convert location_reports to utf8mb4
class MigrateLocationReportsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('location_reports', from: 'latin1', to: 'utf8mb4')
  end
end
