# frozen_string_literal: true

# Autogenerated migration to convert identifiers to utf8mb4
class MigrateIdentifiersToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('identifiers', from: 'latin1', to: 'utf8mb4')
  end
end
