---
Opentrons:
  name: Opentrons
  workflow: Ultima UG200
  sorted: 0
  lab_activity: true
  sti_type: SetDescriptorsTask
Amp:
  name: Amp
  workflow: Ultima UG200
  sorted: 1
  lab_activity: true
  sti_type: SetDescriptorsTask
