# frozen_string_literal: true

# This file was automatically generated by `rails g record_loader`
# It is not necessary to modify this file, instead individual tasks
# will register themselves as a dependency.
namespace :record_loader do
  desc 'Automatically runs all record loader tasks'
  task all: :environment

  task all_except_in_test: :environment do
    Rake::Task['record_loader:all'].invoke unless Rails.env.test?
  end
end

# Automatically run record loader before seeds
task 'db:seed' => 'record_loader:all_except_in_test'
