# frozen_string_literal: true

# This file was automatically generated by `rails g record_loader`
# It is not necessary to modify this file, instead individual tasks
# will register themselves as a dependency.
namespace :record_loader do
  desc 'Automatically runs all record loader tasks'
  task all: :environment
end
