# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

selected_env = ENV['RAILS_ENV'] ||= 'cucumber'

if selected_env != 'cucumber'
  puts "You are running the cucumber specs with the #{selected_env} environment."
  puts "This can cause problems with gem loading. Please use 'cucumber' instead."
end

require_relative 'simplecov' # loading order is important
require 'cucumber/rails'
require_relative 'parameter_types' # does not seem to be automatically loaded correctly...

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail. This is a different from how
# your application behaves in the production environment, where an error page will
# be rendered instead.
#
# Sometimes we want to override this default behaviour and allow Rails to rescue
# exceptions and display an error page (just like when the app is running in production).
# Typical scenarios where you want to do this is when you test your error pages.
# There are two ways to allow Rails to rescue exceptions:
#
# 1) Tag your scenario (or feature) with @allow-rescue
#
# 2) Set the value below to true. Beware that doing this globally is not
# recommended as it will mask a lot of errors for you!
#
ActionController::Base.allow_rescue = false

require 'database_cleaner-activerecord-seeded_deletion'

# Configure DatabaseCleaner to use the SeededDeletion strategy
DatabaseCleaner[:active_record].strategy = DatabaseCleaner::ActiveRecord::SeededDeletion.new

Before do
  # Do something before each scenario
  DatabaseCleaner.start  # This captures the current state of the database
end

After do |scenario|
  # Do something after each scenario
  DatabaseCleaner.clean  # This deletes only the records created after DatabaseCleaner.start was called
end
