# These transfer templates are associated with the Bioscan pipelines.
---
# Plate-to-plate transfers
Transfer columns 1-1:
  name: Transfer columns 1-1
  transfer_class_name: Transfer::BetweenPlates
  transfers: "---\nA1: A1\nB1: B1\nC1: C1\nD1: D1\nE1: E1\nF1: F1\nG1: G1\nH1: H1\n"

Transfer columns 1-2:
  name: Transfer columns 1-2
  transfer_class_name: Transfer::BetweenPlates
  transfers: "---\nA1: A1\nA2: A2\nB1: B1\nB2: B2\nC1: C1\nC2: C2\nD1: D1\nD2: D2\nE1: E1\nE2: E2\nF1: F1\nF2: F2\nG1: G1\nG2: G2\nH1: H1\nH2: H2\n"

Transfer columns 1-3:
  name: Transfer columns 1-3
  transfer_class_name: Transfer::BetweenPlates
  transfers: "---\nA1: A1\nA2: A2\nA3: A3\nB1: B1\nB2: B2\nB3: B3\nC1: C1\nC2: C2\nC3: C3\nD1: D1\nD2: D2\nD3: D3\nE1: E1\nE2: E2\nE3: E3\nF1: F1\nF2: F2\nF3: F3\nG1: G1\nG2: G2\nG3: G3\nH1: H1\nH2: H2\nH3: H3\n"
Transfer columns 1-4:
  name: Transfer columns 1-4
  transfer_class_name: Transfer::BetweenPlates
  transfers: "---\nA1: A1\nA2: A2\nA3: A3\nA4: A4\nB1: B1\nB2: B2\nB3: B3\nB4: B4\nC1: C1\nC2: C2\nC3: C3\nC4: C4\nD1: D1\nD2: D2\nD3: D3\nD4: D4\nE1: E1\nE2: E2\nE3: E3\nE4: E4\nF1: F1\nF2: F2\nF3: F3\nF4: F4\nG1: G1\nG2: G2\nG3: G3\nG4: G4\nH1: H1\nH2: H2\nH3: H3\nH4: H4\n"

Transfer columns 1-6:
  name: Transfer columns 1-6
  transfer_class_name: Transfer::BetweenPlates
  transfers: "---\nA1: A1\nA2: A2\nA3: A3\nA4: A4\nA5: A5\nA6: A6\nB1: B1\nB2: B2\nB3: B3\nB4: B4\nB5: B5\nB6: B6\nC1: C1\nC2: C2\nC3: C3\nC4: C4\nC5: C5\nC6: C6\nD1: D1\nD2: D2\nD3: D3\nD4: D4\nD5: D5\nD6: D6\nE1: E1\nE2: E2\nE3: E3\nE4: E4\nE5: E5\nE6: E6\nF1: F1\nF2: F2\nF3: F3\nF4: F4\nF5: F5\nF6: F6\nG1: G1\nG2: G2\nG3: G3\nG4: G4\nG5: G5\nG6: G6\nH1: H1\nH2: H2\nH3: H3\nH4: H4\nH5: H5\nH6: H6\n"

Transfer columns 1-12:
  name: Transfer columns 1-12
  transfer_class_name: Transfer::BetweenPlates
  transfers: "---\nA1: A1\nA2: A2\nA3: A3\nA4: A4\nA5: A5\nA6: A6\nA7: A7\nA8: A8\nA9: A9\nA10: A10\nA11: A11\nA12: A12\nB1: B1\nB2: B2\nB3: B3\nB4: B4\nB5: B5\nB6: B6\nB7: B7\nB8: B8\nB9: B9\nB10: B10\nB11: B11\nB12: B12\nC1: C1\nC2: C2\nC3: C3\nC4: C4\nC5: C5\nC6: C6\nC7: C7\nC8: C8\nC9: C9\nC10: C10\nC11: C11\nC12: C12\nD1: D1\nD2: D2\nD3: D3\nD4: D4\nD5: D5\nD6: D6\nD7: D7\nD8: D8\nD9: D9\nD10: D10\nD11: D11\nD12: D12\nE1: E1\nE2: E2\nE3: E3\nE4: E4\nE5: E5\nE6: E6\nE7: E7\nE8: E8\nE9: E9\nE10: E10\nE11: E11\nE12: E12\nF1: F1\nF2: F2\nF3: F3\nF4: F4\nF5: F5\nF6: F6\nF7: F7\nF8: F8\nF9: F9\nF10: F10\nF11: F11\nF12: F12\nG1: G1\nG2: G2\nG3: G3\nG4: G4\nG5: G5\nG6: G6\nG7: G7\nG8: G8\nG9: G9\nG10: G10\nG11: G11\nG12: G12\nH1: H1\nH2: H2\nH3: H3\nH4: H4\nH5: H5\nH6: H6\nH7: H7\nH8: H8\nH9: H9\nH10: H10\nH11: H11\nH12: H12\n"

Pool wells based on submission:
  name: Pool wells based on submission
  transfer_class_name: Transfer::BetweenPlatesBySubmission

Custom pooling:
  name: Custom pooling
  transfer_class_name: Transfer::BetweenPlates

Transfer wells to MX library tubes by submission:
  name: Transfer wells to MX library tubes by submission
  transfer_class_name: Transfer::FromPlateToTubeBySubmission

Transfer wells to specific tubes by submission:
  name: Transfer wells to specific tubes by submission
  transfer_class_name: Transfer::FromPlateToSpecificTubes

Transfer from tube to tube by submission:
  name: Transfer from tube to tube by submission
  transfer_class_name: Transfer::BetweenTubesBySubmission

# Plate-to-tube transfers
Transfer wells to specific tubes defined by submission:
  name: Transfer wells to specific tubes defined by submission
  transfer_class_name: Transfer::FromPlateToSpecificTubesByPool

Transfer between specific tubes:
  name: Transfer between specific tubes
  transfer_class_name: Transfer::BetweenSpecificTubes

Whole plate to tube:
  name: Whole plate to tube
  transfer_class_name: Transfer::FromPlateToTube
  transfers: "---\n- A1\n- A2\n- A3\n- A4\n- A5\n- A6\n- A7\n- A8\n- A9\n- A10\n- A11\n- A12\n- B1\n- B2\n- B3\n- B4\n- B5\n- B6\n- B7\n- B8\n- B9\n- B10\n- B11\n- B12\n- C1\n- C2\n- C3\n- C4\n- C5\n- C6\n- C7\n- C8\n- C9\n- C10\n- C11\n- C12\n- D1\n- D2\n- D3\n- D4\n- D5\n- D6\n- D7\n- D8\n- D9\n- D10\n- D11\n- D12\n- E1\n- E2\n- E3\n- E4\n- E5\n- E6\n- E7\n- E8\n- E9\n- E10\n- E11\n- E12\n- F1\n- F2\n- F3\n- F4\n- F5\n- F6\n- F7\n- F8\n- F9\n- F10\n- F11\n- F12\n- G1\n- G2\n- G3\n- G4\n- G5\n- G6\n- G7\n- G8\n- G9\n- G10\n- G11\n- G12\n- H1\n- H2\n- H3\n- H4\n- H5\n- H6\n- H7\n- H8\n- H9\n- H10\n- H11\n- H12\n"

384 plate to tube:
  name: 384 plate to tube
  transfer_class_name: Transfer::FromPlateToTube
  transfers: "---\n- A1\n- A2\n- A3\n- A4\n- A5\n- A6\n- A7\n- A8\n- A9\n- A10\n- A11\n- A12\n- A13\n- A14\n- A15\n- A16\n- A17\n- A18\n- A19\n- A20\n- A21\n- A22\n- A23\n- A24\n- B1\n- B2\n- B3\n- B4\n- B5\n- B6\n- B7\n- B8\n- B9\n- B10\n- B11\n- B12\n- B13\n- B14\n- B15\n- B16\n- B17\n- B18\n- B19\n- B20\n- B21\n- B22\n- B23\n- B24\n- C1\n- C2\n- C3\n- C4\n- C5\n- C6\n- C7\n- C8\n- C9\n- C10\n- C11\n- C12\n- C13\n- C14\n- C15\n- C16\n- C17\n- C18\n- C19\n- C20\n- C21\n- C22\n- C23\n- C24\n- D1\n- D2\n- D3\n- D4\n- D5\n- D6\n- D7\n- D8\n- D9\n- D10\n- D11\n- D12\n- D13\n- D14\n- D15\n- D16\n- D17\n- D18\n- D19\n- D20\n- D21\n- D22\n- D23\n- D24\n- E1\n- E2\n- E3\n- E4\n- E5\n- E6\n- E7\n- E8\n- E9\n- E10\n- E11\n- E12\n- E13\n- E14\n- E15\n- E16\n- E17\n- E18\n- E19\n- E20\n- E21\n- E22\n- E23\n- E24\n- F1\n- F2\n- F3\n- F4\n- F5\n- F6\n- F7\n- F8\n- F9\n- F10\n- F11\n- F12\n- F13\n- F14\n- F15\n- F16\n- F17\n- F18\n- F19\n- F20\n- F21\n- F22\n- F23\n- F24\n- G1\n- G2\n- G3\n- G4\n- G5\n- G6\n- G7\n- G8\n- G9\n- G10\n- G11\n- G12\n- G13\n- G14\n- G15\n- G16\n- G17\n- G18\n- G19\n- G20\n- G21\n- G22\n- G23\n- G24\n- H1\n- H2\n- H3\n- H4\n- H5\n- H6\n- H7\n- H8\n- H9\n- H10\n- H11\n- H12\n- H13\n- H14\n- H15\n- H16\n- H17\n- H18\n- H19\n- H20\n- H21\n- H22\n- H23\n- H24\n- I1\n- I2\n- I3\n- I4\n- I5\n- I6\n- I7\n- I8\n- I9\n- I10\n- I11\n- I12\n- I13\n- I14\n- I15\n- I16\n- I17\n- I18\n- I19\n- I20\n- I21\n- I22\n- I23\n- I24\n- J1\n- J2\n- J3\n- J4\n- J5\n- J6\n- J7\n- J8\n- J9\n- J10\n- J11\n- J12\n- J13\n- J14\n- J15\n- J16\n- J17\n- J18\n- J19\n- J20\n- J21\n- J22\n- J23\n- J24\n- K1\n- K2\n- K3\n- K4\n- K5\n- K6\n- K7\n- K8\n- K9\n- K10\n- K11\n- K12\n- K13\n- K14\n- K15\n- K16\n- K17\n- K18\n- K19\n- K20\n- K21\n- K22\n- K23\n- K24\n- L1\n- L2\n- L3\n- L4\n- L5\n- L6\n- L7\n- L8\n- L9\n- L10\n- L11\n- L12\n- L13\n- L14\n- L15\n- L16\n- L17\n- L18\n- L19\n- L20\n- L21\n- L22\n- L23\n- L24\n- M1\n- M2\n- M3\n- M4\n- M5\n- M6\n- M7\n- M8\n- M9\n- M10\n- M11\n- M12\n- M13\n- M14\n- M15\n- M16\n- M17\n- M18\n- M19\n- M20\n- M21\n- M22\n- M23\n- M24\n- N1\n- N2\n- N3\n- N4\n- N5\n- N6\n- N7\n- N8\n- N9\n- N10\n- N11\n- N12\n- N13\n- N14\n- N15\n- N16\n- N17\n- N18\n- N19\n- N20\n- N21\n- N22\n- N23\n- N24\n- O1\n- O2\n- O3\n- O4\n- O5\n- O6\n- O7\n- O8\n- O9\n- O10\n- O11\n- O12\n- O13\n- O14\n- O15\n- O16\n- O17\n- O18\n- O19\n- O20\n- O21\n- O22\n- O23\n- O24\n- P1\n- P2\n- P3\n- P4\n- P5\n- P6\n- P7\n- P8\n- P9\n- P10\n- P11\n- P12\n- P13\n- P14\n- P15\n- P16\n- P17\n- P18\n- P19\n- P20\n- P21\n- P22\n- P23\n- P24\n"

Flip Plate:
  name: Flip Plate
  transfer_class_name: Transfer::BetweenPlates
  transfers: "---\nA1: H12\nA2: H11\nA3: H10\nA4: H9\nA5: H8\nA6: H7\nA7: H6\nA8: H5\nA9: H4\nA10: H3\nA11: H2\nA12: H1\nB1: G12\nB2: G11\nB3: G10\nB4: G9\nB5: G8\nB6: G7\nB7: G6\nB8: G5\nB9: G4\nB10: G3\nB11: G2\nB12: G1\nC1: F12\nC2: F11\nC3: F10\nC4: F9\nC5: F8\nC6: F7\nC7: F6\nC8: F5\nC9: F4\nC10: F3\nC11: F2\nC12: F1\nD1: E12\nD2: E11\nD3: E10\nD4: E9\nD5: E8\nD6: E7\nD7: E6\nD8: E5\nD9: E4\nD10: E3\nD11: E2\nD12: E1\nE1: D12\nE2: D11\nE3: D10\nE4: D9\nE5: D8\nE6: D7\nE7: D6\nE8: D5\nE9: D4\nE10: D3\nE11: D2\nE12: D1\nF1: C12\nF2: C11\nF3: C10\nF4: C9\nF5: C8\nF6: C7\nF7: C6\nF8: C5\nF9: C4\nF10: C3\nF11: C2\nF12: C1\nG1: B12\nG2: B11\nG3: B10\nG4: B9\nG5: B8\nG6: B7\nG7: B6\nG8: B5\nG9: B4\nG10: B3\nG11: B2\nG12: B1\nH1: A12\nH2: A11\nH3: A10\nH4: A9\nH5: A8\nH6: A7\nH7: A6\nH8: A5\nH9: A4\nH10: A3\nH11: A2\nH12: A1\n"

Transfer wells to MX library tubes by multiplex:
  name: Transfer wells to MX library tubes by multiplex
  transfer_class_name: Transfer::FromPlateToTubeByMultiplex

Pooling rows to first column:
  name: Pooling rows to first column
  transfer_class_name: Transfer::BetweenPlates
  transfers: "---\nA1: A1\nA2: A1\nA3: A1\nA4: A1\nA5: A1\nA6: A1\nA7: A1\nA8: A1\nA9: A1\nA10: A1\nA11: A1\nA12: A1\nB1: B1\nB2: B1\nB3: B1\nB4: B1\nB5: B1\nB6: B1\nB7: B1\nB8: B1\nB9: B1\nB10: B1\nB11: B1\nB12: B1\nC1: C1\nC2: C1\nC3: C1\nC4: C1\nC5: C1\nC6: C1\nC7: C1\nC8: C1\nC9: C1\nC10: C1\nC11: C1\nC12: C1\nD1: D1\nD2: D1\nD3: D1\nD4: D1\nD5: D1\nD6: D1\nD7: D1\nD8: D1\nD9: D1\nD10: D1\nD11: D1\nD12: D1\nE1: E1\nE2: E1\nE3: E1\nE4: E1\nE5: E1\nE6: E1\nE7: E1\nE8: E1\nE9: E1\nE10: E1\nE11: E1\nE12: E1\nF1: F1\nF2: F1\nF3: F1\nF4: F1\nF5: F1\nF6: F1\nF7: F1\nF8: F1\nF9: F1\nF10: F1\nF11: F1\nF12: F1\nG1: G1\nG2: G1\nG3: G1\nG4: G1\nG5: G1\nG6: G1\nG7: G1\nG8: G1\nG9: G1\nG10: G1\nG11: G1\nG12: G1\nH1: H1\nH2: H1\nH3: H1\nH4: H1\nH5: H1\nH6: H1\nH7: H1\nH8: H1\nH9: H1\nH10: H1\nH11: H1\nH12: H1\n"
