version: "2"
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "app/assets/javascripts/sequencescape/datepicker.js"
  - "public/**/*"
plugins:
  fixme:
    enabled: true
  reek:
    enabled: true
  bundler-audit:
    enabled: true
  flog:
    enabled: true
