inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.3
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - db/views_schema.rb
    - db/archived_migrations/*
    - vendor/**/*
# The cop is meant to enforce conventions regarding variables containing numbers
# However in 0.43.0 it is bugged. Both changed on master and disabled by default
# The exclusions don't even get added to the rubocop_todo properly!
Style/VariableNumber:
  Enabled: false
Rails:
  Enabled: true
# Step definitions are defined with Given /regex/ do ...
# There is little ambiguity here, and brackets just break convention
Lint/AmbiguousRegexpLiteral:
  Exclude:
    - features/support/step_definitions/**/*
# These steps are explicitly designed for debugging. In general usage, they wont
# be used.
Lint/Debugger:
  Exclude:
    - 'features/support/step_definitions/debug_steps.rb'
    - 'features/support/developing.rb'
# Enforces 1234565789 as 123_456_789: While nice when dealing with actual big
# numbers, we're more likely to see it shout at us about barcodes.
Style/NumericLiterals:
  Enabled: false

# Blocks are used to structure tests and are part of the shoulda dsl.
# The standard BlockLength limits are too stringent for this purpose.
# Block DSL is also used in routes
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
    - 'config/routes.rb'

# Enforces the new rails 5 style. Re-enable on Rails 5 upgrade.
Rails/HttpPositionalArguments:
  Enabled: false

# We have a few custom find_by methods which we maintain.
# At least for now. find_by_id_or_name is a bit clunky.
Rails/DynamicFindBy:
  Whitelist:
    - find_by_sql
    - find_by_id_or_name
    - find_by_id_or_name!

Style/IndentArray:
  EnforcedStyle: consistent
