inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.4
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - db/views_schema.rb
    - db/archived_migrations/*
    - vendor/**/*
# The cop is meant to enforce conventions regarding variables containing numbers
# However in 0.43.0 it is bugged. Both changed on master and disabled by default
# The exclusions don't even get added to the rubocop_todo properly!
Naming/VariableNumber:
  Enabled: false
Rails:
  Enabled: true
# Step definitions are defined with Given /regex/ do ...
# There is little ambiguity here, and brackets just break convention
Lint/AmbiguousRegexpLiteral:
  Exclude:
    - features/support/step_definitions/**/*
# These steps are explicitly designed for debugging. In general usage, they wont
# be used.
Lint/Debugger:
  Exclude:
    - 'features/support/step_definitions/debug_steps.rb'
    - 'features/support/developing.rb'
# Enforces 1234565789 as 123_456_789: While nice when dealing with actual big
# numbers, we're more likely to see it shout at us about barcodes.
Style/NumericLiterals:
  Enabled: false

# Blocks are used to structure tests and are part of the shoulda dsl.
# The standard BlockLength limits are too stringent for this purpose.
# Block DSL is also used in routes
# We should be careful keeping rake tasks here, as large tasks are still an issue.
# Not sure if we need to split namespaces across several files though.
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'lib/tasks/*'
# We have a few custom find_by methods which we maintain.
# At least for now. find_by_id_or_name is a bit clunky.
Rails/DynamicFindBy:
  Exclude:
    - 'lib/sample_manifest_excel/**/*'
    - 'test/lib/sample_manifest_excel/**/*'
  Whitelist:
    - find_by_sql
    - find_by_id_or_name
    - find_by_id_or_name!

Layout/IndentArray:
  EnforcedStyle: consistent
Style/ClassAndModuleChildren:
  Enabled: false

# Rubocop has a few issues with this when generating the ignore files.
# Also, I'm far from convinced that its correct. It argues in favour of
# +'' over Sting.new when creating a mutable string due to marginal
# performance improvements.
# See: http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Performance/UnfreezeString
# That said, I can see potential advantages wrt. encoding
# Anyway, leaving this off for now.
Performance/UnfreezeString:
  Enabled: false
# This should be the rubocop defaults, not sure why its kicking up a fuss.
Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space
