inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml
  - .rubocop_todo.yml
require:
  - test_prof/rubocop
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

RSpec/AggregateExamples:
  # Aggregate examples can be useful, but the cop gets into nasty battles with
  # other Spec cops, and is only really of value in expensive tests.
  Enabled: false
# Added exclude because api and feature specs do not have a specific class.
RSpec/DescribeClass:
  Exclude:
    - "spec/requests/**/*.rb"
    - "spec/api/**/*.rb"
    - "spec/features/**/*.rb"
    - "spec/lib/warren/*.rb"
    - "spec/models/billing/*.rb"
AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - db/views_schema.rb
    - db/archived_migrations/*
    # CI installs gems in the vendor directory, which causes rubocop to try
    # and cop our gems. We don't want it to.
    - vendor/**/*
    - bin/*
    - sbin/*
    - node_modules/**/*

Rails/SkipsModelValidations:
  Exclude:
    - "db/migrate/*.rb"
    - "db/migrate_asset_refactor/*.rb"
    - "features/support/step_definitions/*.rb"

Style/Documentation:
  Exclude:
    - "test/**/*"
    - "spec/**/*"

Rails:
  Enabled: true
# Step definitions are defined with Given /regex/ do ...
# There is little ambiguity here, and brackets just break convention
Lint/AmbiguousRegexpLiteral:
  Exclude:
    - features/support/step_definitions/**/*
# These steps are explicitly designed for debugging. In general usage, they wont
# be used.
Lint/Debugger:
  Exclude:
    - "features/support/step_definitions/debug_steps.rb"
    - "features/support/developing.rb"
# Enforces 1234565789 as 123_456_789: While nice when dealing with actual big
# numbers, we're more likely to see it shout at us about barcodes.
Style/NumericLiterals:
  Enabled: false

# Blocks are used to structure tests and are part of the shoulda dsl.
# The standard BlockLength limits are too stringent for this purpose.
# Block DSL is also used in routes
# We should be careful keeping rake tasks here, as large tasks are still an issue.
# Not sure if we need to split namespaces across several files though.
# We exclude builders, as they are concerned with rendering xml
Metrics/BlockLength:
  Exclude:
    - Gemfile
    - "db/seeds/**/*"
    - "**/*.builder"
  IgnoredMethods:
    - describe
    - context
    - background
    - scenario
    - namespace
    - task
    - included
    - shared_context
    - shared_examples
    - shared_examples_for
    - state_machine
    - configure
    - draw
    - feature
    - subject
    - let
    - let!
    - factory
    - define
    - guard
    - transient
    - with_nested_has_many_association
    - with_association
    - it
    - class_eval
    - has_metadata
    - resources
    - aasm
    - redefine_aasm
    - model
    - step
    # Less sure that these should be excluded.
    # Lots of code in them is bad, however we also have things like
    # expected outputs, which can be large
    - setup
    - test
    - before
    - should
# We have a few custom find_by methods which we maintain.
# At least for now. find_by_id_or_name is a bit clunky.
Rails/DynamicFindBy:
  Exclude:
    - "app/sample_manifest_excel/**/*"
    - "test/app/sample_manifest_excel/**/*"
  Whitelist:
    - find_by_sql
    - find_by_id_or_name
    - find_by_id_or_name!
    - find_by_barcode
    - find_by_or_null
# Method length limits make little sense when you are describing a table schema
# or a view.
Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"
    - "db/migrate_asset_refactor/*"
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Style/ClassAndModuleChildren:
  Enabled: false
# This should be the rubocop defaults, not sure why its kicking up a fuss.
Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - cucumber
    - profile

RSpec/ExampleLength:
  inherit_mode:
    merge:
      - Exclude
  # Disable for features, as we might want to step through long processes
  Exclude:
    - "spec/features/**/*"

Metrics/ClassLength:
  inherit_mode:
    merge:
      - Exclude
  # Disable for features, as we might want to step through long processes
  Exclude:
    - "spec/**/*"
RSpec/Rails/AvoidSetupHook:
  Exclude:
    - "test/**/*"

RSpec/MultipleExpectations:
  Exclude:
    - "spec/features/**/*"
