codecov:
  notify:
    # do not notify until at least n builds have been uploaded from the CI pipeline
    # rake_tests (push)
    # rake_tests (pull_request)
    # ruby_test x3 (push)
    # ruby_test x3 (pull_request)
    # cucumber_tests x2 (push)
    # cucumber_tests x2 (pull_request)
    after_n_builds: 12
