#!/bin/bash

set -e
echo 'Cleaning up'
NODE_ENV=production bundle exec rake assets:clobber
echo 'Compiling assets'
NODE_ENV=production bundle exec rake assets:precompile
echo 'Generating sha'
git rev-parse HEAD > REVISION
git tag -l --points-at HEAD --sort -version:refname | head -1 > TAG
git rev-parse --abbrev-ref HEAD > BRANCH
echo 'Compiling tar.gz'
tar \
    --exclude='./.git' \
    --exclude='./tmp' \
    --exclude='./compile-build' \
    --exclude='./vendor/bundle' \
    --exclude='./node_modules' \
    --exclude='./log/*' \
    --exclude='./.bundle' \
    --exclude='./.codeclimate.yml' \
    --exclude='./.gitignore' \
    --exclude='./.simplecov' \
    --exclude='./.rspec' \
    --exclude='./.rubocop*' \
    --exclude='./coverage' \
    --exclude='./features' \
    --exclude='./knapsack_cucumber_report.json' \
    --exclude='./run_coverage' \
    --exclude='./sbin' \
    --exclude='./sequencescape.sublime-project' \
    --exclude='./spec' \
    --exclude='./test' \
    --exclude='./yarn.lock' \
    --exclude='./*.swp' \
    --exclude='./.tags' \
    --exclude='./.travis.yml' \
    --exclude='./README' \
    --exclude='release.tar.gz' \
    -zcvf /tmp/release.tar.gz ./
mv /tmp/release.tar.gz ./release.tar.gz
echo 'Release complete!'
echo `pwd`/release.tar.gz
