version: "3.3"
services:
  sequencescape_server:
    build: .
    image: sequencescape_local_image
    depends_on: 
      - mysql_server
    ports:
      - "3000:3000"
    environment:
      - DBHOST=mysql_server
      - RESET_DATABASE=$RESET_DATABASE
    volumes:
      - ".:/code"
    entrypoint: "bash -c ./entrypoint.sh"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 4
  sequencescape_worker:
    image: sequencescape_local_image
    depends_on: 
      - sequencescape_server
    environment:
      - DBHOST=mysql_server
    volumes:
      - ".:/code"
    entrypoint: "bash -c 'bundle exec rake jobs:work'"

  mysql_server:
    image: mysql:5.7
    volumes:
        - ./dockermysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
