#
# Extension of the stack for Local Dev environment running.
# Provides mounting code from the current folder path and
# connect to web and rabbitmq UI
services:
  sequencescape_server:
    ports:
      - "3000:3000"
    volumes:
      - ".:/code"

  sequencescape_worker:
    volumes:
      - ".:/code"

  mysql_server:
    volumes:
      - ./dockermysql:/var/lib/mysql

  rabbitmq_server:
    ports:
      - "15672:15672"

  sequencescape_consumer:
    volumes:
      - ".:/code"
