#!/bin/bash
export RAILS_ENV=test
bundle exec rails db:environment:set
bundle exec rake db:drop
bundle exec rake db:setup
bundle exec rspec
bundle exec rake test
export RAILS_ENV=cucumber
bundle exec rails db:environment:set
bundle exec rake db:reset
bundle exec cucumber
