---
# Section names must be unique inside the record loader folder.
"OTR carrier Lot # UG200":
  name: "OTR carrier Lot #"
  task: Opentrons
  workflow: Ultima UG200
  kind: Text
  required: false
  sorter: 0
OTR carrier expiry UG200:
  name: OTR carrier expiry
  task: Opentrons
  workflow: Ultima UG200
  kind: Date
  required: false
  sorter: 1
"Reaction Mix 7 Lot # UG200":
  name: "Reaction Mix 7 Lot #"
  task: Opentrons
  workflow: Ultima UG200
  kind: Text
  required: false
  sorter: 2
Reaction Mix 7 expiry UG200:
  name: Reaction Mix 7 expiry
  task: Opentrons
  workflow: Ultima UG200
  kind: Date
  required: false
  sorter: 3
"NFW Lot # UG200":
  name: "NFW Lot #"
  task: Opentrons
  workflow: Ultima UG200
  kind: Text
  required: false
  sorter: 4
NFW expiry UG200:
  name: NFW expiry
  task: Opentrons
  workflow: Ultima UG200
  kind: Date
  required: false
  sorter: 5
"Oil Lot # UG200":
  name: "Oil Lot #"
  task: Opentrons
  workflow: Ultima UG200
  kind: Text
  required: false
  sorter: 6
Oil expiry UG200:
  name: Oil expiry
  task: Opentrons
  workflow: Ultima UG200
  kind: Date
  required: false
  sorter: 7
Pipette carousel UG200:
  name: Pipette carousel
  task: Opentrons
  workflow: Ultima UG200
  kind: Text
  required: false
  sorter: 8
Opentrons Inst. Name UG200:
  name: Opentrons Inst. Name
  task: Opentrons
  workflow: Ultima UG200
  kind: Text
  required: true
  sorter: 9
Assign Control Bead Tube UG200:
  name: Assign Control Bead Tube
  task: Amp
  workflow: Ultima UG200
  kind: Text
  required: false
  sorter: 0
UG AMP Inst. Name UG200:
  name: UG AMP Inst. Name
  task: Amp
  workflow: Ultima UG200
  kind: Text
  required: true
  sorter: 1
