---
# Section names must be unique inside the record loader folder.
Pipette carousel UG200:
  name: Pipette carousel
  task: Opentrons
  workflow: Ultima UG200
  kind: Text
  required: false
  sorter: 8 # Note sorted numbers are high because there were previous descriptors that have since been removed.
Opentrons Inst. Name UG200:
  name: Opentrons Inst. Name
  task: Opentrons
  workflow: Ultima UG200
  kind: Text
  required: true
  sorter: 9
