---
Element Aviti PhiX type:
  name: PhiX type
  task: Loading
  workflow: Element Aviti
  kind: Selection
  value: Element PhiX
  selection:
    Element PhiX: Element PhiX
    Comp PhiX: Comp PhiX
  required: true
  sorter: 6
