---
# Add entries to this file to generate them automatically upon running
# rake record_loader:all or rake record_loader:<%= underscore %>
# If you want entries which are only created in development mode then simply
# create a file in this directory ending in '.dev.yml'
# You can add as many additional .yml files to this directory as you wish.
# Example:
# <%= record_key %> A:
#   other_attribute: 'Value'
# <%= record_key %> B:
#   other_attribute: 'Value'
requested_flowcell_type:
  name: Flowcell Requested
  key: requested_flowcell_type
  label: Flowcell Requested
  width: 5
  hide_in_inbox: 0
