---
Chromium Genome 96:
  name: Chromium Genome 96
  tag_group_name: Chromium Genome 96
PN-1000212 Single Index Kit N, Set A:
  name: PN-1000212 Single Index Kit N, Set A
  tag_group_name: PN-1000212 Single Index Kit N, Set A
