---
Chromium Genome 96:
  name: Chromium Genome 96
  tag_group_name: Chromium Genome 96
Chromium Single Cell:
  name: Chromium Single Cell
  tag_group_name: Chromium Single Cell
Chromium i7 Multiplex Kit N Set A:
  name: Chromium i7 Multiplex Kit N Set A
  tag_group_name: Chromium i7 Multiplex Kit N Set A
PN-1000212 Single Index Kit N, Set A:
  name: PN-1000212 Single Index Kit N, Set A
  tag_group_name: PN-1000212 Single Index Kit N, Set A
