---
Ultima P1:
  name: Ultima P1
  tag_group_name: Ultima P1
Ultima P2:
  name: Ultima P2
  tag_group_name: Ultima P2
Ultima P3:
  name: Ultima P3
  tag_group_name: Ultima P3
UG-RD-1916 (Solaris 2.0 V1 PCR-Free Adapters for Ultima Genomics P4):
  name: UG-RD-1916 (Solaris 2.0 V1 PCR-Free Adapters for Ultima Genomics P4)
  tag_group_name: UG-RD-1916 (Solaris 2.0 V1 PCR-Free Adapters for Ultima Genomics P4)
UG-RD-1940 (Solaris 2.0 PCR-Free Adapters for Ultima Genomics P1):
  name: UG-RD-1940 (Solaris 2.0 PCR-Free Adapters for Ultima Genomics P1)
  tag_group_name: UG-RD-1940 (Solaris 2.0 PCR-Free Adapters for Ultima Genomics P1)
