# These submission templates are associated with the Limber Cardinal pipeline.
# They are in a separate file to allow us to soft-release them before
# the real release.
---
Limber - Cardinal:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["limber_cardinal"]
    project_name: "Project Cardinal"
    product_line_name: Cardinal
    product_catalogue_name: Cardinal
Limber - Cardinal cell banking:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["limber_cardinal_banking"]
    project_name: "Project Cardinal"
    product_line_name: Cardinal
    product_catalogue_name: Cardinal
