# This submission template is associated with the Limber Targeted NanoSeq pipeline.
---
Limber-Htp - Targeted NanoSeq:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["limber_targeted_nanoseq"]
    project_name: "Project Cardinal"
    product_line_name: Cardinal
    product_catalogue_name: Cardinal
