# This submission template is associated with the Bioscan pipeline.
---
Limber-Htp - Bioscan:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["bioscan_test_request_type"]
    product_line_name: Illumina-HTP
    product_catalogue_name: WGS
