# These submission templates are associated with the Bioscan pipelines.
---
# Lysate plate preparation from the stock insects plate
Limber-Htp - Bioscan Lysate Prep:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["limber_bioscan_lysate_prep"]
    product_line_name: Bioscan
    product_catalogue_name: Bioscan
# Library preparation from the Lysate or Lysate Input plate
# NB. PacBio long read Sequencing happens in Traction for Bioscan
Limber-Htp - Bioscan Library Prep - Automated:
  name: "Limber-Htp - Bioscan Library Prep - Automated"
  submission_class_name: "AutomatedOrder"
  related_records:
    request_type_keys: ["limber_bioscan_library_prep"]
    product_line_name: Bioscan
    product_catalogue_name: Bioscan
    project_name: "BIOSCAN"
