# These submission templates are associated with the Limber scRNA Core Cell Extraction pipeline.
# They are in a separate file to allow us to soft-release them before
# the real release.
---
Limber - scRNA Core Cell Extraction:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["limber_scrna_core_cell_extraction"]
    product_line_name: scRNA Core Cell Extraction
    product_catalogue_name: scRNA Core Cell Extraction
