# This submission template is associated with the Limber Bait Capture Library preparation pipeline.
---
Limber-Htp - Bait Capture Library:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["limber_bait_capture_library_prep"]
    product_line_name: Illumina-HTP
    product_catalogue_name: Bait Capture Library
