# Submission template for scRNA Core 'Donor Pooling' and 'cDNA Prep'.
# - submission_class_name is LinearSubmission because it represents a
#   chain of request types in linear order.
# - request_type_keys is an array of request types. These match two stages of
#   the pipeline for doing the submission in one go.
# - project_name (cost code) is not included here because it comes from the
#   manual subssion.
# - product_line name is a grouping of related products. This is shown in UI
#   as a category for the submission templates.
# - product_catalogue_name is the name of the product catalogue that has a
#   selection_behaviour as 'SingleProduct'.
---
Limber-Htp - scRNA Core Donor Pooling and cDNA Prep:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["limber_scrna_core_donor_pooling", "limber_scrna_core_cdna_prep"]
    product_line_name: Sample Prep
    product_catalogue_name: scRNA Core
