# Submission templates for the scRNA Core pipeline.
# - submission_class_name is LinearSubmission because it a simple submission
#   that represents a chain of request types in linear order but there is only
#   one request type for two stages of the pipeline in this sumission.
# - request_type_keys is an array of request types.
# - project_name (cost code) is not included here because it comes from the
#   manual subssion.
# - product_line name is a grouping of related products. This is shown in UI
#   as a category for the submission templates.
# - product_catalogue_name is the name of the product catalogue that has a
#   selection_behaviour as 'SingleProduct'.
---
Limber-Htp - scRNA Core cDNA Prep GEM-X 5p:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["limber_scrna_core_cdna_prep_gem_x_5p"]
    product_line_name: Short Read
    product_catalogue_name: scRNA Core
Limber-Htp - scRNA Core cDNA Prep GEM-X 5p GEMs Input:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["limber_scrna_core_cdna_prep_gem_x_5p_gems_input"]
    product_line_name: Short Read
    product_catalogue_name: scRNA Core
Limber-Htp - scRNA Core cDNA PCR CITE:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["limber_scrna_core_cdna_pcr_cite", "limber_multiplexing"]
    project_name: "S0842"
    product_line_name: Short Read
    product_catalogue_name: scRNA Core
