# Submission templates for the aggregation and library prep parts of the scRNA Core pipeline.
---
Limber-Htp - scRNA Core Aggregation:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["limber_scrna_core_aggregation"]
    product_line_name: Short Read
    product_catalogue_name: scRNA Core
Limber-Htp - scRNA Core Library Prep:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["limber_scrna_core_library_prep"]
    product_line_name: Short Read
    product_catalogue_name: scRNA Core
Limber-Htp - scRNA Core Library Prep - Pool:
  submission_class_name: "LinearSubmission"
  related_records:
    # The following uses limber_multiplexing_norm instead of limber_multiplexing
    # in order to allow the MX sections of the scRNA Core pipeline branches, GE,
    # BCR, TCR, and CITE-seq, to end with the Norm tubes of different purposes.
    # The Norm tubes will be pooled together in poolings/new page.
    request_type_keys: ["limber_scrna_core_library_prep", "limber_multiplexing_norm"]
    product_line_name: Short Read
    product_catalogue_name: scRNA Core
Limber-Htp - scRNA Core Library Prep - NovaSeqX paired end sequencing:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys:
      ["limber_scrna_core_library_prep", "limber_multiplexing", "illumina_htp_novaseqx_paired_end_sequencing"]
    product_line_name: Short Read
    product_catalogue_name: scRNA Core
Limber-Htp - scRNA Core Library Prep - NovaSeq 6000 paired end sequencing:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys:
      ["limber_scrna_core_library_prep", "limber_multiplexing", "illumina_htp_novaseq_6000_paired_end_sequencing"]
    product_line_name: Short Read
    product_catalogue_name: scRNA Core
Limber-Htp - scRNA Core Library Prep - MiSeq sequencing:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["limber_scrna_core_library_prep", "limber_multiplexing", "illumina_b_miseq_sequencing"]
    product_line_name: Short Read
    product_catalogue_name: scRNA Core
