# These submission templates are associated with the EMSeq pipeline.
---
# EMSeq DNA Prep submission template
Limber-Htp - LCM Triomics DNA Prep:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["limber_lcm_triomics_dna_prep"]
    product_line_name: LCM Triomics
    product_catalogue_name: LCM Triomics
