# Submission templates for LCM Triomics WGS and EMSeq
---
# LCM Triomics EMSeq submission template
Limber-Htp - LCM Triomics EMSeq:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["limber_lcm_triomics_emseq"]
    product_line_name: LCM Triomics WGS and EMSeq
    product_catalogue_name: LCM Triomics
