# These submission templates are associated with the EMSeq pipeline.
---
# EMSeq DNA Prep submission template
Limber-Htp - EMSeq DNA Prep:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["limber_emseq_dna_prep"]
    product_line_name: EMSeq
    product_catalogue_name: EMSeq
