# Y24-366
Limber-Htp - BGE PCR Free:
  name: "Limber-Htp - BGE PCR Free"
  submission_class_name: "LinearSubmission"
  related_records:
    product_line_name: Illumina-HTP
    product_catalogue_name: BGE
    request_type_keys: ["limber_bge_pcr_free", "limber_multiplexing"]
Limber-Htp - BGE ISC:
  name: "Limber-Htp - BGE ISC"
  submission_class_name: "LinearSubmission"
  related_records:
    product_line_name: Illumina-HTP
    product_catalogue_name: BGE
    request_type_keys: ["limber_bge_isc", "limber_multiplexing_bge", "illumina_htp_novaseqx_paired_end_sequencing"] # Other request types?
Limber-Htp - BGE Transition - Automated:
  name: "Limber-Htp - BGE Transition - Automated"
  submission_class_name: "AutomatedOrder"
  related_records:
    product_line_name: Illumina-HTP
    product_catalogue_name: BGE
    request_type_keys: ["limber_bge_transition"] # Other request types?
