# This submission template is associated with the Ultima PCR Free Library preparation pipeline.
---
Limber-Htp - Ultima PCR Free - Ultima sequencing:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["limber_ultima_htp_pcr_free", "limber_multiplexing_ultima", "ultima_sequencing"]
    order_role: PCR Free
    product_line_name: Ultima
    product_catalogue_name: GenericNoPCR
Limber-Htp - Ultima PCR Free - Rebalancing:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["limber_rebalancing_ultima"]
    order_role: PCR Free
    product_line_name: Ultima
    product_catalogue_name: GenericNoPCR
# TODO: requires automated sequencing presenter story for UPF Balanced Norm tube
Limber-Htp - Ultima PCR Free - Ultima sequencing Automated:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["ultima_sequencing"]
    order_role: PCR Free
    product_line_name: Ultima
    product_catalogue_name: GenericNoPCR
