# These submission templates are used to enter the illumina to ultima library ltp conversion pipeline
---
# Aggregates wells from Illumina library plates into ULTP DNA Norm, where the
# conversion submission (one of the templates below) is then made.
Limber-Bespoke - Ultima Conv - Aggregation:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["limber_ultima_ltp_aggregation"]
    product_line_name: Ultima
    product_catalogue_name: Generic

Limber-Bespoke - Ultima Conv - Ultima UG100 sequencing:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["limber_ultima_ltp_conversion", "limber_multiplexing_ultima_ltp", "ultima_sequencing"]
    product_line_name: Ultima
    product_catalogue_name: Generic

Limber-Bespoke - Ultima Conv - Ultima UG200 sequencing:
  submission_class_name: "LinearSubmission"
  related_records:
    request_type_keys: ["limber_ultima_ltp_conversion", "limber_multiplexing_ultima_ltp", "ultima_ug200_sequencing"]
    product_line_name: Ultima
    product_catalogue_name: Generic
