---
Limber-Htp - Ultima HiC Conv - Ultima UG100 sequencing:
  name: "Limber-Htp - Ultima HiC Conv - Ultima UG100 sequencing"
  submission_class_name: "LinearSubmission"
  related_records:
    product_line_name: Ultima
    product_catalogue_name: HiC
    request_type_keys: ["limber_hic", "limber_ultima_hic_conv", "limber_multiplexing_ultima_hic_conv", "ultima_sequencing"]
Limber-Htp - Ultima HiC Conv - Ultima UG200 sequencing:
  name: "Limber-Htp - Ultima HiC Conv - Ultima UG200 sequencing"
  submission_class_name: "LinearSubmission"
  related_records:
    product_line_name: Ultima
    product_catalogue_name: HiC
    request_type_keys: ["limber_hic", "limber_ultima_hic_conv", "limber_multiplexing_ultima_hic_conv", "ultima_ug200_sequencing"]
