gender:
  options:
    - Male
    - Female
    - Mixed
    - Hermaphrodite
    - Unknown
    - Not Applicable
dna_source:
  options:
    - Blood
    - Cell Line
    - Saliva
    - Whole Genome Amplified
    - FFPE
    - Amniocentesis Uncultured
    - Amniocentesis Cultured
    - CVS Uncultured
    - CVS Cultured
    - Fetal Blood
    - Tissue
yes_no:
  options:
    - "Yes"
    - "No"
purification_method:
  options:
    - Glassmilk/Qiagen
    - Ultrapure
    - Column/Qiagen
    - Microdialyser/Spectrum
    - Ethanol
    - Other
concentration_determined_by:
  options:
    - PicoGreen
    - Nanodrop
    - Spectrophotometer
    - Other
dna_storage_conditions:
  options:
    - +4C
    - "-20C"
    - "-80C"
library_type:
  identifier: :name
  scope: :alphabetical
library_type_long_read:
  identifier: :name
  scope:
    - :from_record_loaders
    - 001_long_read
  scope_on: LibraryType
primer_panel:
  identifier: :name
  scope: :alphabetical
reference_genome:
  identifier: :name
  scope: :alphabetical
chromium_tag_groups:
  identifier: :name
  scope: :chromium
  scope_on: TagGroup
chromium_single_index_tag_groups:
  identifier: :name
  scope: :visible_single_index_chromium
  scope_on: TagSet
dual_index_tag_sets:
  identifier: :name
  scope: :visible_dual_index
  scope_on: TagSet
gc_content:
  options:
    - "Neutral"
    - "High AT"
    - "High GC"
control_type:
  options:
    - "positive"
    - "negative"
bioscan_control_type:
  options:
    - "pcr positive"
    - "pcr negative"
    - "lysate negative"
insdc_country:
  identifier: :name
  scope: :sorted_for_select
  scope_on: Insdc::Country
collected_by_for_cardinal:
  options:
    - ELGH_Bradford_21034
    - ELGH_London_21032
    - UKB_Bristol_11028
    - UKB_Newcastle_11027
    - UKB_Reading_11026
    - UKB_Stockport_11025
# TODO: this list will need updating, asking Laura L 10th Aug 23
collected_by_for_scrna_core:
  options:
    - IBD-BAR
    - IBD-BAT
    - IBD-BER
    - IBD-BIR
    - IBD-BOU
    - IBD-CAM
    - IBD-CAR
    - IBD-CDD
    - IBD-COV
    - IBD-ECH
    - IBD-EDI
    - IBD-ENH
    - IBD-ESH
    - IBD-GST
    - IBD-HUL
    - IBD-ICL
    - IBD-KCH
    - IBD-KET
    - IBD-LEE
    - IBD-LIV
    - IBD-MAN
    - IBD-NCL
    - IBD-NNU
    - IBD-NOR
    - IBD-OXF
    - IBD-PEN
    - IBD-RDE
    - IBD-ROF
    - IBD-SME
    - IBD-SOM
    - IBD-STE
    - IBD-STG
    - IBD-STH
    - IBD-STS
    - IBD-SUS
    - IBD-SWA
    - IBD-SWF
    - IBD-TOR
    - IBD-UHS
    - IBD-WOL
collected_by_for_controls:
  options:
    - Sanger Institute
retention_instructions:
  options:
    - Destroy after 2 years
    - Return to customer after 2 years
    - Long term storage
