# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

# To enable developers to have their own development setup per repository clone we allow them to stick
# the suffix they want attached to any database names in the suffix file in the root of the project.
<% suffix = "_#{File.read(File.join(Rails.root, 'database_suffix'))}".strip rescue nil %>

mysql: &MYSQL
  adapter: mysql2
  host: 127.0.0.1
  port: 3306
  username: <%= ENV.fetch('DBUSERNAME','root') %>
  password: <%= ENV['DBPASSWORD'] %>
  encoding: utf8
  properties:
    characterSetResults: utf8
  pool: 5
  timeout: 5000
  reaping_frequency: 600
  variables:
    sql_mode: TRADITIONAL
    # This improbably large value mimics the global option for production
    # Without this things fall back to 1024 (At least with my setup) which
    # is too small for larger pools.
    group_concat_max_len: 67108864

development:
  <<: *MYSQL
  database: sequencescape_development<%= suffix %>

  # indentation is deliberate!
  development_warehouse: &warehouse
    <<: *MYSQL
    database: warehouse_development<%= suffix %>

development_local:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

development_local_snp:
  adapter: sqlite3
  database: db/snp_development.sqlite3
  pool: 5
  timeout: 5000

development_local_cas:
  adapter: sqlite3
  database: db/cas_development.sqlite3
  pool: 5
  timeout: 5000

##  Oracle legacy
development_snp:
  adapter: nulldb
  database: snp
  username: username
  password: password

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.

test: &test
  <<: *MYSQL
  database: sequencescape_test<%= ENV['TEST_ENV_NUMBER'] %><%= suffix %>
  pool: 10
  timeout: 5000

cucumber:
  <<: *test
  database: sequencescape_test<%= ENV['TEST_ENV_NUMBER'] %><%= suffix %>_cuke

# In production environments adapter should be 'oracle_enhanced',
# Username, password and database are values that go to sqlplus login <username>/<password>@<database>

agresso_test_db:
  adapter: nulldb
  database: database
  username: username
  password: password

# These other connections are exported during deploy, from:
# ssh://git/repos/git/psd/config/private.git/
### Staging
### Next release
### Training
### Production
