---
GbS Tag Set A:
  :tag_group_name: Sanger_168tags - 10 mer tags
  :tag2_group_name: Dual Index Tag2 sequences
  :direction_algorithm: TagLayout::InColumnsThenRows
  :walking_algorithm: TagLayout::Quadrants
GbS Tag Set B:
  :tag_group_name: Sanger_168tags - 10 mer tags
  :tag2_group_name: Dual Index Tag2 sequences set B
  :direction_algorithm: TagLayout::InColumnsThenRows
  :walking_algorithm: TagLayout::Quadrants
GbS Tag Set C:
  :tag_group_name: Sanger_168tags - 10 mer tags
  :tag2_group_name: Dual Index Tag2 sequences set C
  :direction_algorithm: TagLayout::InColumnsThenRows
  :walking_algorithm: TagLayout::Quadrants
GbS Tag Set D:
  :tag_group_name: Sanger_168tags - 10 mer tags
  :tag2_group_name: Dual Index Tag2 sequences set D
  :direction_algorithm: TagLayout::InColumnsThenRows
  :walking_algorithm: TagLayout::Quadrants
IDT GbS Tag Set A:
  tag_group_name: Sanger_168tags - 10 mer tags
  tag2_group_name: Dual Index Tag2 sequences
  :direction_algorithm: TagLayout::InColumnsThenRows
  :walking_algorithm: TagLayout::Quadrants
IDT GbS Tag Set B:
  tag_group_name: Sanger_168tags - 10 mer tags
  tag2_group_name: Dual Index Tag2 sequences set B
  :direction_algorithm: TagLayout::InColumnsThenRows
  :walking_algorithm: TagLayout::Quadrants
IDT GbS Tag Set C:
  tag_group_name: Sanger_168tags - 10 mer tags
  tag2_group_name: Dual Index Tag2 sequences set C
  :direction_algorithm: TagLayout::InColumnsThenRows
  :walking_algorithm: TagLayout::Quadrants
IDT GbS Tag Set D:
  tag_group_name: Sanger_168tags - 10 mer tags
  tag2_group_name: Dual Index Tag2 sequences set D
  :direction_algorithm: TagLayout::InColumnsThenRows
  :walking_algorithm: TagLayout::Quadrants
