Ultima P1:
  :tag_group_name: Ultima P1
  :direction_algorithm: TagLayout::InColumns
  :walking_algorithm: TagLayout::WalkWellsOfPlate
Ultima P2:
  :tag_group_name: Ultima P2
  :direction_algorithm: TagLayout::InColumns
  :walking_algorithm: TagLayout::WalkWellsOfPlate
