---
Element Aviti:
  name: Element Aviti
  sti_type: SequencingPipeline
  sorter: 10
  max_size: 2
  summary: 1
  externally_managed: 0
  group_name: Sequencing
  control_request_type_id: 0
  min_size: 1
  request_type_keys:
    - element_aviti_sequencing
  workflow:
    name: Element Aviti
    item_limit: 2
