---
Ultima:
  name: Ultima Sequencing
  # sti_type: UltimaSequencingPipeline
  validator_class_name: UltimaValidator
  sorter: 10
  max_size: 2
  summary: 1
  externally_managed: 0
  group_name: Sequencing
  control_request_type_id: 0
  min_size: 1
  request_type_keys:
    - ultima_sequencing
  workflow:
    name: Ultima
    item_limit: 2
