---
title: Accessioning Call Graph Overview
---
%%{ init: { 
    'flowchart': { 'curve': 'curvy' },
    'theme': 'neutral'
  }
}%%
flowchart LR
    %% Legend
    subgraph Legend [Legend]
        direction TB
        L_User(fa:fa-user User)
        L_External(fa:fa-arrow-up External API)
        L_API(fa:fa-arrow-right-to-bracket API)
        L_Interface(fa:fa-computer-mouse User Interface)
        L_Model(fa:fa-square-caret-down Model)
        L_Controller(fa:fa-arrows-spin Controller)
        L_View(fa:fa-eye View)
        L_Function(fa:fa-caret-right Function)
        L_Config(fa:fa-screwdriver-wrench Configuration)
        L_Resource(fa:fa-file Resource)
        L_Library(fa:fa-book Library)
        L_Async(fa:fa-clock Asynchronous Process)
    
        L_User ~~~ L_External ~~~ L_API ~~~ L_Interface ~~~ L_Resource ~~~ L_Async 
        L_Config ~~~ L_Controller ~~~ L_Model ~~~ L_View ~~~ L_Function ~~~ L_Library
    
        InvisibleNodeA[ ] -..-> | Data flow | InvisibleNodeB[ ] -- Function calls --> InvisibleNodeC[ ] == Accessioning function calls ==> InvisibleNodeD[ ]
    end

    Legend ~~~ Providers
    %% End Legend

    %% Nodes
    %% Users
    User_SeqOps(fa:fa-user SeqOps)
    User_Study_Owners(fa:fa-user Study Owners)
    User_Neil(fa:fa-user Neil)
    User_SSR(fa:fa-user SSRs)
    User_LB_Users(fa:fa-user LB Users)
    User_Developers(fa:fa-user Developers)
    User_SS_Users(fa:fa-user SS Users)

    %% External Systems
    External_EBI_Studies(fa:fa-arrow-up EBI Studies)
    External_EBI_Samples(fa:fa-arrow-up EBI Samples)

    %% User Interfaces
    UI_LB_Charge_and_Pass(fa:fa-computer-mouse Charge and Pass)
    UI_SS_Sample_GAN(fa:fa-computer-mouse Generate Accession Number)
    UI_SS_Sample_SAA(fa:fa-computer-mouse Save and Accession)
    UI_SS_Study_GAN(fa:fa-computer-mouse Generate Accession Number)
    UI_SS_Study_AAS(fa:fa-computer-mouse Accession all Samples)
    UI_SS_Manifest_Upload(fa:fa-computer-mouse Manifest Upload)

    %% Models   
    MD_SS_Order(fa:fa-square-caret-down Order)
    %% MD_SS_AccessionService(fa:fa-square-caret-down AccessionService)
    MD_SS_Submission_AccessionBehaviour(fa:fa-square-caret-down Submission::AccessionBehaviour)
    %% MD_SS_Sample(fa:fa-square-caret-down Sample)
    %% MD_SS_Study(fa:fa-square-caret-down Study)
    MD_SS_SampleManifest_Uploader(fa:fa-square-caret-down SampleManifest::Uploader)
    MD_SS_AccessionStatuses(fa:fa-square-caret-down AccessionStatuses)

    %% Controllers
    %% CT_SS_Samples(fa:fa-arrows-spin Samples Controller)
    %% CT_SS_Studies(fa:fa-arrows-spin Studies Controller)

    %% Views
    VW_SS_Sample(fa:fa-eye Sample View)
    VW_SS_Study(fa:fa-eye Study View)

    %% Functions
    FN_SS_SampleManifestExcel_Upload_Base_trigger_accessioning(fa:fa-caret-right SampleManifestExcel::Upload::Base#trigger_accessioning)
    FN_SS_AccessionService_select_for_study(fa:fa-caret-right select_for_study)
    FN_SS_AccessionService_submit_study_for_user(fa:fa-caret-right submit_study_for_user)
    FN_SS_AccessionService_submit(fa:fa-caret-right submit)
    FN_SS_Accessionable_Study_update_accession_number(fa:fa-caret-right Accessionable::Study#update_accession_number!)
    FN_SS_Sample_accession(fa:fa-caret-right accession)
    FN_SS_Sample_accession_and_handle_validation_errors(fa:fa-caret-right accession_and_handle_validation_errors)
    FN_SS_Sample_validate_accessionable(fa:fa-caret-right validate_accessionable!)
    FN_SS_Samples_accession(fa:fa-caret-right accession)
    FN_SS_Study_accession_all_samples(fa:fa-caret-right accession_all_samples)
    FN_SS_Studies_accession_all_samples(fa:fa-caret-right accession_all_samples)
    FN_SS_Studies_accession(fa:fa-caret-right accession)
    FN_SS_Studies_rescue_accession_errors(fa:fa-caret-right rescue_accession_errors)
    FN_SS_Accession_accession_sample(fa:fa-caret-right accession_sample)
    FN_SS_Accession_Sample_validate(fa:fa-caret-right Accession::Sample#validate)
    FN_SS_Accession_Sample_update_accession_number(fa:fa-caret-right Accession::Sample#update_accession_number)
    FN_SS_Study_validate_study_for_accessioning(fa:fa-caret-right validate_study_for_accessioning!)

    %% Libraries
    LB_SS_AccessioningV1Client(fa:fa-book AccessioningV1Client)

    %% Other Components
    API_SS_OrderResource(fa:fa-arrow-right-to-bracket Order Resource)
    CP_SS_AccessionSubmission(fa:fa-book Accession::Submission)
    DJ_SS_SampleAccessioningJob(fa:fa-clock SampleAccessioningJob)

    %% Config
    CF_SS_accession_samples(fa:fa-screwdriver-wrench accession_samples)
    CF_SS_disable_accession_check(fa:fa-screwdriver-wrench disable_accession_check)

    %% Resources
    RES_Manifest(fa:fa-file Manifest)

    %% Groupings of nodes
    subgraph Providers
        User_SeqOps
        User_Study_Owners
        User_Neil
        User_SSR
    end
    subgraph Application_Limber[Limber Application]
        UI_LB_Charge_and_Pass
    end
    subgraph Application_Sequencescape[Sequencescape Application]
        UI_SS_Manifest_Upload
        MD_SS_SampleManifest_Uploader
        FN_SS_SampleManifestExcel_Upload_Base_trigger_accessioning
        MD_SS_Order
        MD_SS_Submission_AccessionBehaviour
        CF_SS_accession_samples
        CF_SS_disable_accession_check

        DJ_SS_SampleAccessioningJob
        LB_SS_AccessioningV1Client
        MD_SS_AccessionStatuses

        FN_SS_Accessionable_Study_update_accession_number

        VW_SS_Sample
        VW_SS_Study

        subgraph Samples
            UI_SS_Sample_SAA
            UI_SS_Sample_GAN
        end        
        subgraph Studies
            UI_SS_Study_GAN
            UI_SS_Study_AAS
        end
        subgraph SS_API["SS API"]
            API_SS_OrderResource
        end
        subgraph CT_SS_Studies[fa:fa-arrows-spin Studies Controller]
            FN_SS_Studies_accession_all_samples
            FN_SS_Studies_accession
            FN_SS_Studies_rescue_accession_errors
        end
        subgraph MD_SS_Study[fa:fa-square-caret-down Study Model]
            FN_SS_Study_accession_all_samples
            FN_SS_Study_validate_study_for_accessioning
        end
        subgraph CT_SS_Samples[fa:fa-arrows-spin Samples Controller]
            FN_SS_Samples_accession
        end
        subgraph LB_SS_Accession[fa:fa-book Accession - samples only]
            FN_SS_Accession_accession_sample
            CP_SS_AccessionSubmission
            FN_SS_Accession_Sample_validate
            FN_SS_Accession_Sample_update_accession_number
        end
        subgraph MD_SS_AccessionService[fa:fa-square-caret-down AccessionService Model - studies only]
            FN_SS_AccessionService_select_for_study
            FN_SS_AccessionService_submit_study_for_user
            FN_SS_AccessionService_submit
        end
        subgraph MD_SS_Sample[fa:fa-square-caret-down Sample Model]
            FN_SS_Sample_accession
            FN_SS_Sample_accession_and_handle_validation_errors
            FN_SS_Sample_validate_accessionable
        end
    end
    subgraph External_EBI[fa:fa-globe EBI ENA Webin REST V1]
        External_EBI_Studies
        External_EBI_Samples
    end
    subgraph Consumers
        User_LB_Users
        User_SS_Users
        User_Developers
    end

    %% Edge connections between nodes

    Providers ~~~ Application_Limber ~~~ Consumers
    Providers ~~~ Application_Sequencescape ~~~ Consumers

    CT_SS_Studies ~~~ MD_SS_Study ~~~ CT_SS_Samples ~~~ MD_SS_Sample
    FN_SS_Samples_accession ~~~ FN_SS_AccessionService_submit_study_for_user

    %% Limber-related
    User_SeqOps --> UI_LB_Charge_and_Pass -...-> User_LB_Users
    UI_LB_Charge_and_Pass --> API_SS_OrderResource --> MD_SS_Order
    MD_SS_Order --> MD_SS_Submission_AccessionBehaviour
    MD_SS_Submission_AccessionBehaviour --> CF_SS_disable_accession_check
    MD_SS_Submission_AccessionBehaviour -..-> | exception email | User_Developers

    %% Manifest upload
    User_SSR --> RES_Manifest -..-> UI_SS_Manifest_Upload --> MD_SS_SampleManifest_Uploader 
    MD_SS_SampleManifest_Uploader --> FN_SS_SampleManifestExcel_Upload_Base_trigger_accessioning ---> FN_SS_Accession_accession_sample
    
    %% Sample generate accession number
    User_SSR --> UI_SS_Sample_GAN
    User_Neil --> UI_SS_Sample_GAN
    UI_SS_Sample_GAN --> FN_SS_Samples_accession
    FN_SS_Samples_accession <--> | 1. | FN_SS_Accession_accession_sample
    FN_SS_Accession_accession_sample ==> DJ_SS_SampleAccessioningJob
    DJ_SS_SampleAccessioningJob <--> | 1. | FN_SS_Accession_Sample_validate
    DJ_SS_SampleAccessioningJob ==> | 2. | CP_SS_AccessionSubmission
    CP_SS_AccessionSubmission ==> LB_SS_AccessioningV1Client
    LB_SS_AccessioningV1Client ==> External_EBI_Samples
    External_EBI_Samples ==> | Success: accession number | FN_SS_Accession_Sample_update_accession_number
    External_EBI_Samples ==> | Failure: reason | MD_SS_AccessionStatuses
    FN_SS_Accession_Sample_update_accession_number -.- VW_SS_Sample
    MD_SS_AccessionStatuses -.- VW_SS_Sample
    FN_SS_Samples_accession --> | 2. | VW_SS_Sample
    VW_SS_Sample --> User_SS_Users

    %% Sample save and accession
    User_SSR --> UI_SS_Sample_SAA
    UI_SS_Sample_SAA --> FN_SS_Sample_accession_and_handle_validation_errors
    FN_SS_Sample_accession_and_handle_validation_errors --> FN_SS_Accession_accession_sample

    %% Study accession all samples
    User_Neil --> UI_SS_Study_AAS
    User_Study_Owners --> UI_SS_Study_AAS
    UI_SS_Study_AAS --> FN_SS_Studies_accession_all_samples 
    FN_SS_Studies_accession_all_samples <--> | 1. | FN_SS_Study_accession_all_samples
    FN_SS_Study_accession_all_samples --> FN_SS_Accession_accession_sample
    FN_SS_Studies_accession_all_samples --> | 2. | VW_SS_Study

    %% Study generate accession number
    User_Study_Owners --> UI_SS_Study_GAN
    UI_SS_Study_GAN --> FN_SS_Studies_accession
    FN_SS_Studies_accession <--> | 1. | FN_SS_Study_validate_study_for_accessioning
    FN_SS_Studies_accession <--> | 2. | FN_SS_AccessionService_select_for_study
    FN_SS_Studies_accession <--> | 3. | FN_SS_AccessionService_submit_study_for_user
    FN_SS_Studies_accession --> | 4. IF success -- flash message | VW_SS_Study
    FN_SS_Studies_accession --> | 4. IF error | FN_SS_Studies_rescue_accession_errors
    FN_SS_AccessionService_submit_study_for_user ==> FN_SS_AccessionService_submit
    FN_SS_AccessionService_submit ==> External_EBI_Studies
    External_EBI_Studies ==> FN_SS_Accessionable_Study_update_accession_number
    FN_SS_Studies_rescue_accession_errors --> | flash message | VW_SS_Study
    VW_SS_Study --> User_SS_Users

    %% Subgraph styling

    %% lemon-chiffon: #fbf8cc
    %% champagne-pink: #fde4cf
    %% tea-rose-red: #ffcfd2
    %% pink-lavender: #f1c0e8
    %% mauve: #cfbaf0
    %% jordy-blue: #a3c4f3
    %% non-photo-blue: #90dbf4
    %% electric-blue: #8eecf5
    %% aquamarine: #98f5e1
    %% celadon: #b9fbc0

    classDef default fill:#fafafa,stroke:#333,stroke-width:1px;

    classDef invisible fill:transparent,stroke:transparent;
    classDef legendTransparent fill:transparent,stroke:#333,stroke-width:1px;
    classDef application fill:#90dbf4;
    classDef configuration fill:#fbf8cc;
    classDef railsModel fill:#98f5e1;
    classDef railsController fill:#b9fbc0;
    classDef users fill:#f1c0e8;
    classDef userInterface fill:#a3c4f3;

    class InvisibleNodeA,InvisibleNodeB,InvisibleNodeC,InvisibleNodeD invisible;
    class Legend legendTransparent;
    class Application_Sequencescape,Application_Limber application;
    class L_Config,CF_SS_disable_accession_check,CF_SS_accession_samples configuration;
    class SS_API,DelayedJob,Samples,Studies,Submissions SequencescapeSection;
    class L_Model,MD_SS_Study,MD_SS_AccessionService,MD_SS_Sample,MD_SS_SampleManifest_Uploader,MD_SS_Order,MD_SS_Submission_AccessionBehaviour railsModel;
    class L_Controller,CT_SS_Samples,CT_SS_Studies railsController;
    class L_User,User_SeqOps,User_Study_Owners,User_Neil,User_SSR,User_LB_Users,User_SS_Users,User_Developers users;
    class L_Interface,UI_LB_Charge_and_Pass,UI_SS_Sample_GAN,UI_SS_Sample_SAA,UI_SS_Study_GAN,UI_SS_Study_AAS,UI_SS_Manifest_Upload userInterface;
