---
title: Accessioning User Graph
---
%%{ init: {
    'flowchart': { 'curve': 'curvy' },
    'theme': 'neutral'
  }
}%%
flowchart LR
    %% Legend
    subgraph Legend [Legend]
        direction TB
        L_User(fa:fa-user User)
        L_API(fa:fa-arrow-right-to-bracket API)
        L_Interface(fa:fa-computer-mouse User Interface)
        L_Model(fa:fa-square-caret-down Model)
        L_Controller(fa:fa-arrows-spin Controller)
        L_Function(fa:fa-caret-right Function)
        L_Resource(fa:fa-file Resource)

        L_User ~~~ L_Interface ~~~ L_API ~~~ L_Resource
        L_Controller ~~~ L_Model ~~~ L_Function

        InvisibleNodeA[ ] -..-> | Data flow | InvisibleNodeB[ ] -- Function calls --> InvisibleNodeC[ ]
    end
    %% End Legend

    %% Nodes
    %% Users
    User_SeqOps(fa:fa-user SeqOps)
    User_Neil(fa:fa-user Neil)
    User_SSR(fa:fa-user SSRs)

    %% User Interfaces
    UI_LB_Charge_and_Pass(fa:fa-computer-mouse Charge and Pass)
    UI_SS_Sample_GAN(fa:fa-computer-mouse Generate Accession Number)
    UI_SS_Study_GAN(fa:fa-computer-mouse Generate Accession Number)
    UI_SS_Study_AAS(fa:fa-computer-mouse Accession all Samples)
    UI_SS_Manifest_Upload(fa:fa-computer-mouse Manifest Upload)

    %% Models
    MD_SS_Order(fa:fa-square-caret-down Order)
    MD_SS_SampleManifest_Uploader(fa:fa-square-caret-down SampleManifest::Uploader)

    %% Functions
    FN_SS_Samples_accession(fa:fa-caret-right accession)
    FN_SS_Studies_accession_all_samples(fa:fa-caret-right accession_all_samples)
    FN_SS_Studies_accession(fa:fa-caret-right accession)

    %% Other Components
    API_SS_OrderResource(fa:fa-arrow-right-to-bracket Order Resource)

    %% Resources
    RES_Manifest(fa:fa-file Manifest)

    %% Groupings of nodes
    subgraph Providers
        User_SeqOps
        User_Neil
        User_SSR
    end
    subgraph Application_Limber
        UI_LB_Charge_and_Pass
    end
    subgraph Application_Sequencescape
        UI_SS_Manifest_Upload
        MD_SS_SampleManifest_Uploader
        MD_SS_Order

        subgraph Samples
            UI_SS_Sample_GAN
        end
        subgraph Studies
            UI_SS_Study_GAN
            UI_SS_Study_AAS
        end
        subgraph SS_API["SS API"]
            API_SS_OrderResource
        end
        subgraph CT_SS_Studies[fa:fa-arrows-spin Studies Controller]
            FN_SS_Studies_accession_all_samples
            FN_SS_Studies_accession
        end
        subgraph CT_SS_Samples[fa:fa-arrows-spin Samples Controller]
            FN_SS_Samples_accession
        end
    end

    %% Edge connections between nodes
    Legend ~~~ Providers

    %% Limber-related
    User_SeqOps --> UI_LB_Charge_and_Pass
    UI_LB_Charge_and_Pass --> API_SS_OrderResource --> MD_SS_Order

    %% Manifest upload
    User_SSR --> RES_Manifest -.-> UI_SS_Manifest_Upload --> MD_SS_SampleManifest_Uploader

    %% Sample generate accession number
    User_SSR --> UI_SS_Sample_GAN
    User_Neil --> UI_SS_Sample_GAN
    UI_SS_Sample_GAN --> FN_SS_Samples_accession

    %% Study accession all samples
    User_SSR  --> UI_SS_Study_AAS
    User_Neil --> UI_SS_Study_AAS
    UI_SS_Study_AAS --> FN_SS_Studies_accession_all_samples

    %% Study generate accession number
    User_Neil --> UI_SS_Study_GAN
    UI_SS_Study_GAN --> FN_SS_Studies_accession

    %% Subgraph styling

    %% lemon-chiffon: #fbf8cc
    %% champagne-pink: #fde4cf
    %% tea-rose-red: #ffcfd2
    %% pink-lavender: #f1c0e8
    %% mauve: #cfbaf0
    %% jordy-blue: #a3c4f3
    %% non-photo-blue: #90dbf4
    %% electric-blue: #8eecf5
    %% aquamarine: #98f5e1
    %% celadon: #b9fbc0

    classDef default fill:#fafafa,stroke:#333,stroke-width:1px;

    classDef invisible fill:transparent,stroke:transparent;
    classDef legendTransparent fill:transparent,stroke:#333,stroke-width:1px;
    classDef application fill:#90dbf4;
    classDef railsModel fill:#98f5e1;
    classDef railsController fill:#b9fbc0;
    classDef users fill:#f1c0e8;
    classDef userInterface fill:#a3c4f3;

    class InvisibleNodeA,InvisibleNodeB,InvisibleNodeC,InvisibleNodeD invisible;
    class Legend legendTransparent;
    class Application_Sequencescape,Application_Limber application;
    class L_Model,MD_SS_SampleManifest_Uploader,MD_SS_Order railsModel;
    class L_Controller,CT_SS_Samples,CT_SS_Studies railsController;
    class L_User,User_SeqOps,User_Neil,User_SSR users;
    class L_Interface,UI_LB_Charge_and_Pass,UI_SS_Sample_GAN,UI_SS_Study_GAN,UI_SS_Study_AAS,UI_SS_Manifest_Upload userInterface;
