EBI_Library_strategy:
  - "RNA-Seq"
  - "ChIP-Seq"
  - "WGS"
  - "WXS"
  - "AMPLICON"
  - "CLONE"
  - "POOLCLONE"
  - "CLONEEND"
  - "Bisulfite-Seq"
  - "MNase-Seq"
  - "DNase-Hypersensitivity"
  - "FAIRE-seq"
  - "SELEX"
  - "RIP-Seq"
  - "ChIA-PET"
  - "OTHER"
EBI_Library_source:
  - "GENOMIC"
  - "TRANSCRIPTOMIC"
  - "METAGENOMIC"
  - "METATRANSCRIPTOMIC"
  - "SYNTHETIC"
  - "VIRAL RNA"
  - "OTHER"
EBI_Library_selection:
  - "RANDOM"
  - "PCR"
  - "RANDOM PCR"
  - "RT-PCR"
  - "HMPR"
  - "MF"
  - "CF-S"
  - "CF-M"
  - "CF-T"
  - "MDA"
  - "MSLL"
  - "cDNA"
  - "ChIP"
  - "MNase"
  - "DNAse"
  - "Hybrid Selection"
  - "Reduced Representation"
  - "Restriction Digest"
  - "5-methylcytidine antibody"
  - "MBD2 protein methyl-CpG binding domain"
  -