development:
  type: log
  config:
    exchange: psd.sequencescape
  subscriptions:
    queue_broadcast_consumer:
      exchange: psd.sequencescape
      queue: psd.queue_broadcast
      routing_keys:
        - development.queue_broadcast.#
      deadletter_exchange: deadletters
profile:
  type: log
test:
  type: test
cucumber:
  type: test
production:
  type: log
