# By default the development environment just logs the message and
# payload. If you wish to enable broadcasting in development mode,
# the easiest way to do so is to set the ENV WARREN_TYPE.
# For example
# `WARREN_TYPE=broadcast bundle exec rails s`
# This will override the setting in warren.yml
development:
  type: log
  # Log mode does not actually use this configuration, but
  # it is provided for convenience when broadcast mode is enabled.
  # The provided settings are the default options of RabbitMQ
  # DO NOT commit sensitive information in this file. Instead you may
  # use the WARREN_CONNECTION_URI environmental variable
  config:
    server:
      host: <%= ENV.fetch('RMQHOST', 'localhost') %>
      port: 5672
      username: guest
      password: guest
      vhost: /
      frame_max: 0
      heartbeat: 30
    exchange: psd.sequencescape
    routing_key_prefix: development
# The test environment sets up a test message handler, which lets
# you make assertions about which messages have been sent.
# See: https://rubydoc.info/gems/sanger_warren/Warren/Handler/Test
test:
  type: test
  config:
    routing_key_prefix: test

cucumber:
  type: test
  config:
    routing_key_prefix: test

# We need to pass some value to Warren when the app is being packaged up (vite:build),
# because the initializers are run.
# The value will be overwritten when the app is deployed.
production:
  type: test
# You are encouraged to use the WARREN_CONNECTION_URI environmental
# variable to configure your production environment. Under no
# circumstances should you commit sensitive information in the file.
