# frozen_string_literal: true

require 'rails_helper'

RSpec.describe 'Rails61_upgrade', type: :model do

  it 'plate_sample_manifest_with_manifest_assets factory should be valid' do
    manifest = create(:plate_sample_manifest_with_manifest_assets)
    expect(manifest.sample_manifest_assets).to be_present
  end
  
  # TODO: need to get this working
  it 'validate FactoryBot factories', :aggregate_failures do
    factory_name = :product_line
    expect(build(factory_name)).to be_valid
  end
 
end

# product_line
# accession_response
# successful_accession_response
# failed_accession_response
# sample_metadata_for_accessioning
# sample_metadata_with_accession_number
# minimal_sample_metadata_for_accessioning
# sample_for_accessioning
# sample_for_accessioning_with_open_study
# sample_for_accessioning_with_managed_study
# accession_sample
# invalid_accession_sample
# ena_service
# ega_service
# accession_submission
# accession_tag_list
# standard_accession_tag_list
# accession_tag
# sample_taxon_id_accession_tag
# country_of_origin_accession_tag
# collection_date_accession_tag
# sample_common_name_accession_tag
# gender_accession_tag
# phenotype_accession_tag
# donor_id_accession_tag
# sample_public_name_accession_tag
# disease_state_accession_tag
# rnai_accession_tag
# aliquot
# untagged_aliquot
# single_tagged_aliquot
# minimal_aliquot
# library_aliquot
# phi_x_aliquot
# api_application
# asset_audit
# asset_group
# asset_group_asset
# asset_shape
# fluidigm_96_shape
# fluidigm_192_shape
# strip_tube_column_shape
# barcode
# sanger_ean13
# sanger_ean13_tube
# sanger_code39
# sanger_code39_tube
# sequencescape22
# infinium
# fluidigm
# cgap
# fluidx
# fluidx_tube
# heron_tailed
# barcode_printer
# batch
# multiplexed_batch
# sequencing_batch
# cherrypick_batch
# pac_bio_sequencing_batch
# broadcast_event_asset_audit
# event_subject
# comment
# custom_metadatum_collection
# custom_metadatum_collection_with_metadata
# custom_metadatum
# custom_text
# event
# fragment
# insdc_country
# lane
# empty_lane
# lane_with_stock_plate
# plate_with_3_wells
# lib_pcr_xp_plate_with_tubes
# lib_pcr_xp_request_type
# lib_pool_tube
# lib_pool_norm_tube
# messenger_creator
# messenger
# flowcell_messenger
# phi_x_stock
# phi_x_spiked_buffer
# pick_list
# labware
# plate_creator_purpose
# plate_creator
# control
# descriptor
# lab_event
# flowcell_event
# pipeline
# multiplexed_pipeline
# cherrypick_pipeline
# fluidigm_pipeline
# sequencing_pipeline
# pac_bio_sequencing_pipeline
# library_completion
# pipeline_admin
# workflow
# lab_workflow_for_pipeline
# fluidigm_pipeline_workflow
# cherrypick_pipeline_workflow
# batch_request
# cherrypick_batch_request
# sequencing_batch_request
# request_information_type
# pipeline_request_information_type
# implement
# map
# plate_template
# asset_link
# barcode_prefix
# plate_barcode
# child_plate_barcode
# barcode_printer_type
# plate_barcode_printer_type
# plate_with_wells
# plate
# input_plate
# target_plate
# plate_with_untagged_wells_and_custom_name
# plate_with_untagged_wells
# plate_with_tagged_wells
# final_plate
# plate_with_empty_wells
# source_plate
# child_plate
# plate_with_wells_for_specified_studies
# plate_with_fluidigm_barcode
# full_plate
# pooling_plate
# non_stock_pooling_plate
# input_plate_for_pooling
# stock_plate
# full_stock_plate
# partial_plate
# plate_for_strip_tubes
# two_column_plate
# full_plate_with_samples
# control_plate
# pico_assay_plate
# pico_assay_a_plate
# pico_assay_b_plate
# pico_dilution_plate
# sequenom_qc_plate
# working_dilution_plate
# strip_tube
# plate_type
# pre_capture_pool
# primer_panel
# product_catalogue
# single_product_catalogue
# library_driven_product_catalogue
# product
# product_criteria
# product_product_catalogue
# program
# budget_division
# project_metadata
# project
# project_with_order
# project_manager
# transfer_plate
# transfer_between_plates
# full_transfer_between_plates
# transfer_from_plate_to_tube
# transfer_from_plate_to_tube_with_transfers
# transfer_template
# pooling_transfer_template
# multiplex_transfer_template
# between_tubes_transfer_template
# tag_group_for_layout
# tag_layout_template
# inverted_tag_layout_template
# entire_plate_tag_layout_template
# tag_layout_template_submission
# tag_layout
# plate_creation
# tube_creation
# bait_library_supplier
# bait_library_type
# bait_library
# isc_request
# re_isc_request
# state_change
# plate_owner
# purpose
# stock_purpose
# new_stock_tube_purpose
# illumina_htp_initial_stock_tube_purpose
# purpose_additional_input
# strip_tube_purpose
# plate_purpose
# source_plate_purpose
# input_plate_purpose
# stock_plate_purpose
# pico_assay_purpose
# fluidigm_96_purpose
# fluidigm_192_purpose
# dilution_plate_purpose
# working_dilution_plate_purpose
# tube_purpose
# sample_tube_purpose
# library_tube_purpose
# mx_tube_purpose
# saphyr_tube_purpose
# long_read_tube_purpose
# std_mx_tube_purpose
# illumina_htp_mx_tube_purpose
# parent_plate_purpose
# pooling_plate_purpose
# child_tube_purpose
# tube_rack_purpose
# tube_rack_purpose_48
# qc_assay
# qc_report
# qc_metric
# qc_result
# qc_result_volume
# qc_result_concentration
# qc_result_molarity
# qc_result_rin
# qc_result_loci_passed
# racked_tube
# receptacle
# reference_genome
# request_event
# multiplexed_library_creation_request
# failed_request
# passed_request
# pending_request
# cancelled_request
# request_base
# customer_request
# create_asset_request
# sequencing_request
# sequencing_request_with_assets
# complete_sequencing_request
# library_creation_request
# library_request
# gbs_request
# heron_request
# heron_tailed_request
# multiplex_request
# cherrypick_request
# cherrypick_request_for_pipeline
# passed_cherrypick_request
# cherrypick_for_fluidigm_request
# final_cherrypick_for_fluidigm_request
# request_without_assets
# request
# request_with_submission
# request_with_sequencing_request_type
# well_request
# request_suitable_for_starting
# lib_pcr_xp_request
# request_traction_grid_ion
# request_without_submission
# request_library_creation
# external_multiplexed_library_tube_creation_request
# pac_bio_sample_prep_request
# pac_bio_sequencing_request
# request_metadata
# request_traction_grid_ion_metadata
# request_metadata_for_request_type_
# request_metadata_for_standard_sequencing
# request_metadata_for_single_ended_sequencing
# request_metadata_for_paired_end_sequencing
# request_metadata_for_standard_sequencing_with_read_length
# request_metadata_for_hiseq_sequencing
# request_metadata_for_hiseq_paired_end_sequencing
# request_metadata_for_single_ended_hi_seq_sequencing
# request_metadata_for_miseq_sequencing
# hiseq_x_request_metadata
# request_metadata_for_illumina_a_hiseq_x_paired_end_sequencing
# request_metadata_for_illumina_b_hiseq_x_paired_end_sequencing
# request_metadata_for_hiseq_x_paired_end_sequencing
# request_metadata_for_illumina_a_single_ended_sequencing
# request_metadata_for_illumina_a_paired_end_sequencing
# request_metadata_for_illumina_a_hiseq_sequencing
# request_metadata_for_illumina_a_hiseq_paired_end_sequencing
# request_metadata_for_illumina_a_single_ended_hi_seq_sequencing
# request_metadata_for_illumina_b_single_ended_sequencing
# request_metadata_for_illumina_b_paired_end_sequencing
# request_metadata_for_illumina_b_hiseq_sequencing
# request_metadata_for_illumina_b_hiseq_paired_end_sequencing
# request_metadata_for_illumina_b_single_ended_hi_seq_sequencing
# request_metadata_for_illumina_c_single_ended_sequencing
# request_metadata_for_illumina_c_paired_end_sequencing
# request_metadata_for_illumina_c_hiseq_sequencing
# request_metadata_for_illumina_c_hiseq_paired_end_sequencing
# request_metadata_for_illumina_c_single_ended_hi_seq_sequencing
# request_metadata_for_library_manufacture
# request_metadata_for_library_creation
# request_metadata_for_illumina_c_library_creation
# request_metadata_for_multiplexed_library_creation
# request_metadata_for_mx_library_preparation_new
# request_metadata_for_illumina_b_multiplexed_library_creation
# request_metadata_for_illumina_c_multiplexed_library_creation
# request_metadata_for_pulldown_library_creation
# request_metadata_for_pulldown_multiplex_library_preparation
# request_metadata_for_gbs
# request_metadata_for_heron
# request_metadata_for_bait_pulldown
# request_type
# customer_request_type
# cherrypick_request_type
# well_request_type
# library_request_type
# gbs_request_type
# heron_request_type
# multiplex_request_type
# library_creation_request_type
# isc_library_request_type
# pac_bio_sequencing_request_type
# pac_bio_sample_prep_request_type
# sequencing_request_type
# miseq_sequencing_request_type
# multiplexed_library_creation_request_type
# plate_based_multiplexed_library_creation_request_type
# validated_request_type
# extended_validator
# library_types_request_type
# request_type_validator
# sequencing_request_type_validator
# library_request_type_validator
# pcr_cycles_validator
# pooling_method
# library_type
# library_type_standard
# flowcell_type
# robot
# robot_with_verification_behaviour
# robot_with_generation_behaviour
# full_robot
# full_robot_tecan_v2
# hamilton
# robot_property
# validation_property
# generation_property
# max_plates_property
# role
# admin_role
# public_role
# manager_role
# data_access_coordinator_role
# owner_role
# slf_manager_role
# column_list
# column_list_with_sanger_sample_id
# column_list_for_plate
# column_list_for_tube
# column_list_for_multiplexed_library_tube
# column
# sanger_sample_id_column
# sanger_plate_id_column
# sanger_tube_id_column
# well_column
# tag_group_column
# tag_index_column
# tag2_group_column
# tag2_index_column
# library_type_column
# reference_genome_column
# insert_size_from_column
# insert_size_to_column
# donor_id_column
# retention_instruction_column
# conditional_formatting
# conditional_formatting_with_formula
# range_list
# range
# sample_manifest_asset
# test_download_plates
# test_download_plates_partial
# test_download_plates_cgap
# test_download_plates_partial_cgap
# test_download_tubes
# test_download_tubes_partial
# test_download_tubes_cgap
# test_download_tubes_in_rack
# validation
# sample_manifest
# sample_manifest_with_samples
# plate_sample_manifest_with_manifest_assets
# tube_sample_manifest
# tube_sample_manifest_with_tubes_and_manifest_assets
# tube_sample_manifest_with_samples
# tube_sample_manifest_with_sample_tubes
# pending_plate_sample_manifest
# tube_rack_manifest
# supplier
# sample_metadata
# sample_metadata_with_gender
# sample_metadata_for_api
# sample
# sample_with_well
# sample_with_gender
# sample_with_sanger_sample_id
# accessioned_sample
# study_sample
# search
# uuid
# study
# study_with_manager
# managed_study
# open_study
# not_app_study
# study_type
# data_release_study_type
# faculty_sponsor
# study_for_study_list
# study_for_study_list_pending
# study_for_study_list_active
# study_for_study_list_inactive
# study_for_study_list_pending_ethical_approval
# study_for_study_list_remove_x_and_autosomes
# study_for_study_list_contaminated_with_human_dna
# study_for_study_list_managed_active
# study_for_study_list_managed_inactive
# study_for_study_list_followed
# study_for_study_list_collaborations
# study_for_study_list_interesting
# study_metadata
# study_metadata_for_study_list_pending_ethical_approval
# study_metadata_for_study_list_contaminated_with_human_dna
# study_metadata_for_study_list_remove_x_and_autosomes
# db_file
# study_report
# pending_study_report
# completed_study_report
# submission__
# submission_without_order
# submission
# submission_template
# cherrypick_submission_template
# limber_wgs_submission_template
# libray_and_sequencing_template
# heron_libray_and_sequencing_template
# isc_libray_and_sequencing_template
# order
# order_with_submission
# order_role
# linear_submission
# library_order
# flexible_submission
# automated_order
# library_submission
# tag2_layout
# tag2_layout_template
# tag2_layout_template_submission
# tag
# tag_group
# tag_group_with_tags
# tag_group_form_object
# tag_group_form_object_with_oligos
# adapter_type
# task
# plate_template_task
# assign_tags_task
# fluidigm_template_task
# tag_groups_task
# plate_transfer_task
# cherrypick_task
# add_spiked_in_control_task
# set_descriptors_task
# transfer_request
# transfer_request_with_submission
# transfer_request_with_volume
# tube
# unbarcoded_tube
# empty_sample_tube
# sample_tube
# sample_tube_with_sanger_sample_id
# qc_tube
# multiplexed_library_tube
# pulldown_multiplexed_library_tube
# stock_multiplexed_library_tube
# new_stock_multiplexed_library_tube
# empty_library_tube
# library_tube
# library_tube_with_barcode
# tagged_library_tube
# pac_bio_library_tube
# full_library_tube
# stock_library_tube
# spiked_buffer
# spiked_buffer_with_parent
# phi_x_stock_tube
# tube_rack
# tube_rack_with_tubes
# user
# admin
# manager
# owner
# data_access_coordinator
# slf_manager
# listing_studies_user
# user_query
# well
# untagged_well
# picked_well
# well_attribute
# complete_well_attribute
# tagged_well
# passed_well
# well_with_sample_and_plate
# cross_pooled_well
# well_link
# stock_well_link
# well_for_qc_report
# well_for_location_report
# work_order_type
# work_order
# lot_type
# tag2_lot_type
# tag_layout_lot_type
# pending_purpose
# created_purpose
# qcable_creator
# lot
# tag2_lot
# tag_layout_lot
# stamp
# qcable
# qcable_with_asset
# plate_template_with_well
# tag_layout_qcable_plate_purpose
# location_report
# location_report_selection
# location_report_labwhere
# location_report_form
# product_line
# accession_response