# This product catalogue is associated with the Limber Cardinal pipeline.
# It is in a separate file to allow us to soft-release them before
# the real release.
---
scRNA Core Cell Extraction:
  selection_behaviour: SingleProduct
