#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/boot'

if RUBY_PLATFORM == "java"
  # If we are using jruby, ensure output is sent to the console
  def exec(*args)
    Kernel::exec("#{args.join(' ')} < /dev/tty > /dev/tty 2>&1")
  end
end

require 'commands/dbconsole'
