#!/bin/bash -l
function delayed_job_start() {

  if [ -f tmp/pids/delayed_job.${1}.pid ] && ps -p `cat tmp/pids/delayed_job.${1}.pid` >> /dev/null ; then
    echo 'Existing job appears to be running'
    exit 1
  fi

  echo 'Starting...'

  bundle exec rails runner 'Delayed::Worker.new.start' & > /dev/null
  echo $! > tmp/pids/delayed_job.${1}.pid
  echo "Running!"
  exit 0

}

function check_stopped() {
  if [ -f tmp/pids/delayed_job.${1}.pid ] && ps -p `cat tmp/pids/delayed_job.${1}.pid` >> /dev/null ; then
    echo '.'
  else
    echo 'Delayed Job stopped'
    exit 0
  fi
}

function delayed_job_stop() {
  kill `cat tmp/pids/delayed_job.${1}.pid`
  echo 'Waiting for process to die'
  for ((i = 0; i < 60; i = i + 1)); do
    check_stopped ${1}
    sleep 1
  done
  echo 'Delayed Job failed to die, killing it...'
  kill -9 `cat tmp/pids/delayed_job.${1}.pid`
}

function delayed_job_restart() {
  delayed_job_stop
  delayed_job_start
}

# Provide robust locking as per http://www.davidpashley.com/articles/writing-robust-shell-scripts/
# David Pashley

# The lockfile prevents two scripts concerning the same process from running at the same time.
lockfile="tmp/$2.lock"
echo $lockfile

if ( set -o noclobber; echo "$$" > "$lockfile") 2> /dev/null;
then
   trap 'rm -f "$lockfile"; exit $?' INT TERM EXIT

   # delayed_job_${3} $2
   sleep 5
   rm -f "$lockfile"
   trap - INT TERM EXIT
else
   echo "Failed to acquire lockfile: $lockfile."
   echo "Held by $(cat $lockfile)"
fi

