#!/usr/bin/env ruby

ENV['APP_ROOT'] ||= File.expand_path(File.join(File.dirname(__FILE__), '..'))
APP_ROOT = ENV['APP_ROOT']
script_file = File.join(APP_ROOT, 'lib', 'qc_evaluations-mini_poller.rb')
tmp_dir = File.join(APP_ROOT, 'log')

require 'daemons'

options = {
  #:app_name   => "projects-poller",
  dir_mode: :normal,
  dir: tmp_dir,
  multiple: false,
  ontop: false,
  mode: :load,
  backtrace: true,
  monitor: true,
  log_output: true
}

options[:app_name] = if ENV.has_key?('Rails.env')
  "#{ENV['Rails.env']}-qc_evaluations-mini_poller"
                     else
  'development-qc_evaluations-mini_poller'
                     end

ARGV.each do |arg|
  if arg.include?('=')
    (k, v) = arg.split('=', 2)
    options[:"#{k}"] = v
  end
end

Daemons.run(script_file, options)
