---
UltimaApplicationType:
  request_type_key: limber_ultima_conv
  request_option: application_type
  valid_options: !ruby/object:RequestType::Validator::UltimaApplicationTypeValidator
    request_type_key: limber_ultima_conv

