---
Single Index Kit N, Set A 1000212:
  adapter_type_name: Chromium
  tags:
    1: AAACGGCG
    2: CCTACCAT
    3: GGCGTTTC
    4: TTGTAAGA
    5: AGGCTACC
    6: CTAGCTGT
    7: GCCAACAA
    8: TATTGGTG
    9: AGACTTTC
    10: CCGAGGCA
    11: GATGCAGT
    12: TTCTACAG
    13: AGCTGCGT
    14: CAACCATC
    15: GTGGAGCA
    16: TCTATTAG
    17: ACGAAAGC
    18: CGCCCGTA
    19: GTTTGCCT
    20: TAAGTTAG
    21: ATCGCTCC
    22: CCGTACAG
    23: GATAGGTA
    24: TGACTAGT
    25: ATGCGATT
    26: CATATGCG
    27: GGATACGA
    28: TCCGCTAC
    29: AAACTCAT
    30: CGGGAGTA
    31: GTCACAGG
    32: TCTTGTCC
    33: AGCCCTTT
    34: CAAGTCCA
    35: GTGAGAAG
    36: TCTTAGGC
    37: AAGTTGAT
    38: CCCACCCA
    39: GGTCGAGC
    40: TTAGATTG
    41: AATCACTA
    42: CCGAGAAC
    43: GTAGTGCG
    44: TGCTCTGT
    45: ACATTCCG
    46: CTGCGGTA
    47: GACACAAT
    48: TGTGATGC
    49: AGGCTGGT
    50: CACAACTA
    51: GTTGGTCC
    52: TCATCAAG
    53: ATGGTTAG
    54: CATTGATA
    55: GCAAACGC
    56: TGCCCGCT
    57: ATAACCTA
    58: CGGTGAGC
    59: GATCTTAT
    60: TCCGAGCG
    61: AACGGTCA
    62: CCGAACTC
    63: GGTCCAAG
    64: TTATTGGT
    65: AAAGCATA
    66: CTGCAGCC
    67: GCCTTTAT
    68: TGTAGCGG
    69: ATTGGACG
    70: CAGCTTAC
    71: GGCAAGGA
    72: TCATCCTT
    73: ACGTTACA
    74: CGTAGGTT
    75: GACGACGG
    76: TTACCTAC
    77: ACTTCACT
    78: CGAAGTTG
    79: GAGCACGC
    80: TTCGTGAA
    81: AACAAGTC
    82: CGGCTCCA
    83: GTATGTAT
    84: TCTGCAGG
    85: AGTCTGTA
    86: CAGAATAG
    87: GCCTCCGT
    88: TTAGGACC
    89: ATGTCCAG
    90: CGACGTCA
    91: GCTATAGC
    92: TACGAGTT
    93: ACACCTAA
    94: CGTTTGGG
    95: GACAAACC
    96: TTGGGCTT
    97: AGAACGCC
    98: CATGGCAG
    99: GTCTTTGA
    100: TCGCAATT
    101: AGGGACTG
    102: CCTCTAAC
    103: GACAGGCT
    104: TTATCTGA
    105: ACATTGGC
    106: CTTAGTCA
    107: GAGCCCAT
    108: TGCGAATG
    109: AAATCGTC
    110: CTTCGAAT
    111: GCGATCGG
    112: TGCGATCA
    113: AGCTGACG
    114: CCGGTGTC
    115: GTAAACAT
    116: TATCCTGA
    117: AACGACAC
    118: CGTCCTCT
    119: GCATGATA
    120: TTGATGGG
    121: AGCTTCTC
    122: CCTGCGGT
    123: GTACAACG
    124: TAGAGTAA
    125: ACTGGAGC
    126: CGGTCGTG
    127: GAAATCAA
    128: TTCCATCT
    129: ATTGGGAA
    130: CAGTCTGG
    131: GGCATACT
    132: TCACACTC
    133: ATCGTACT
    134: CATCAGTG
    135: GGGACTAC
    136: TCATGCGA
    137: ATGCATTC
    138: CACTGACT
    139: GGTACGGG
    140: TCAGTCAA
    141: AGACGGAT
    142: CCTTTAGA
    143: GTCGACTC
    144: TAGACTCG
    145: ATCCAAGG
    146: CCGTTGAA
    147: GGAAGCTC
    148: TATGCTCT
    149: AACACAGC
    150: CGGTTTAG
    151: GTACGGCT
    152: TCTGACTA
    153: ATGAAGTA
    154: CGCCGAAC
    155: GAAGCTCG
    156: TCTTTCGT
    157: ATAGTATG
    158: CCGCGTCT
    159: GGCTCCAC
    160: TATAAGGA
    161: ACGGGACT
    162: CTTTCGAC
    163: GAACATGA
    164: TGCATCTG
    165: AACGCGAA
    166: CTATTTGG
    167: GCGCACCT
    168: TGTAGATC
    169: ACTCAGAC
    170: CGCTCAGG
    171: GAGGTTTA
    172: TTAAGCCT
    173: ATGCCAAA
    174: CCTTATCG
    175: GAAGTCTT
    176: TGCAGGGC
    177: ATTGAAAC
    178: CAGCCCGA
    179: GCCATTTG
    180: TGATGGCT
    181: ATGCCGGC
    182: CCTAATTA
    183: GACTTCCT
    184: TGAGGAAG
    185: AGCACTGG
    186: CATTACAC
    187: GTGCGACA
    188: TCAGTGTT
    189: AAGCATAA
    190: CCCATCGC
    191: GGTTGATG
    192: TTAGCGCT
    193: AGGTCATA
    194: CTCATCAT
    195: GCTGAGGG
    196: TAACGTCC
    197: AGGGATGA
    198: CTTCTGTT
    199: GAATGCAC
    200: TCCACACG
    201: ACACCGGG
    202: CATAATCC
    203: GGCGGAAT
    204: TTGTTCTA
    205: AACTTAGA
    206: CCGGATCC
    207: GGTCGCAT
    208: TTAACGTG
    209: AAGACGTG
    210: CCATGTGT
    211: GTTCACAA
    212: TGCGTACC
    213: ACCCGAGA
    214: CAAACTTT
    215: GGTTAGAC
    216: TTGGTCCG
    217: ATTACCGG
    218: CAGTAATT
    219: GCCGGTAA
    220: TGACTGCC
    221: AACGGGTG
    222: CTAATTCT
    223: GCTTCAAC
    224: TGGCACGA
    225: ATGATACG
    226: CCACAGAA
    227: GACTGTTC
    228: TGTGCCGT
    229: ACGTTCAC
    230: CAAGGTCT
    231: GTTAAGTG
    232: TGCCCAGA
    233: AGCTCGAG
    234: CAGGAAGA
    235: GCACGTTT
    236: TTTATCCC
    237: AATCTTTG
    238: CTCAAGAC
    239: GGATGAGT
    240: TCGGCCCA
    241: AGCCTATG
    242: CTAACGCA
    243: GCTTACAT
    244: TAGGGTGC
    245: AGTTGGGA
    246: CCAGAAAG
    247: GTGCCCTC
    248: TACATTCT
    249: AAGTACTC
    250: CTTGGAGA
    251: GGAACTCT
    252: TCCCTGAG
    253: AAGAGCGG
    254: CTTGTTAT
    255: GGCCCATC
    256: TCATAGCA
    257: ACAACTTG
    258: CTCCAACA
    259: GAGTGCGT
    260: TGTGTGAC
    261: AAGCGTGT
    262: CTTGACCG
    263: GCCACGTA
    264: TGATTAAC
    265: AGATCGGT
    266: CATCGTCG
    267: GTCATATA
    268: TCGGACAC
    269: ACCTACTG
    270: CAAGGGAC
    271: GGGACACA
    272: TTTCTTGT
    273: AGTAAGCA
    274: CCGGTAAT
    275: GTATCTTC
    276: TACCGCGG
    277: AGTTAGTT
    278: CACGCACG
    279: GTACTTAA
    280: TCGAGCGC
    281: AGTCTCAG
    282: CAATGGCA
    283: GCCGAAGT
    284: TTGACTTC
    285: ACCTGCCA
    286: CTTCATAC
    287: GGAATATG
    288: TAGGCGGT
    289: ACAGCAAC
    290: CGCAATTT
    291: GAGTTGCG
    292: TTTCGCGA
    293: ACCATTAA
    294: CTGGACGT
    295: GAACGGTC
    296: TGTTCACG
    297: ATCTGATC
    298: CGTGCTAA
    299: GAGAAGGG
    300: TCACTCCT
    301: AGATAACA
    302: CTTATTTG
    303: GCGGGCAT
    304: TACCCGGC
    305: ATTGTTTC
    306: CGCAGGAG
    307: GCACCAGT
    308: TAGTACCA
    309: ATTCGTGC
    310: CGCGTGCA
    311: GAATACTG
    312: TCGACAAT
    313: ATACTGAG
    314: CGGAGACT
    315: GATGCCTC
    316: TCCTATGA
    317: ATTTCAGC
    318: CGAGTGAT
    319: GACCGCCA
    320: TCGAATTG
    321: ACCAGTCC
    322: CTTTCCTT
    323: GGACAGGG
    324: TAGGTAAA
    325: ATGGTCGC
    326: CGACATAG
    327: GATTCGCT
    328: TCCAGATA
    329: ACCGAACA
    330: CGACTCTT
    331: GTTTGTGG
    332: TAGACGAC
    333: ATATGAGA
    334: CACCTCAG
    335: GCTACTTC
    336: TGGGAGCT
    337: ATCGCCAT
    338: CATAAAGG
    339: GGGTTTCC
    340: TCACGGTA
    341: AGCAGTTA
    342: CTTGTACC
    343: GAACCCGG
    344: TCGTAGAT
    345: AGGGCGTT
    346: CTATACGC
    347: GCTCGTCA
    348: TACATAAG
    349: AGGATCGA
    350: CACGATTC
    351: GTATCGAG
    352: TCTCGACT
    353: ACTACTGT
    354: CGGGAACG
    355: GACCTCTC
    356: TTATGGAA
    357: ACGCTTGG
    358: CGCTACAT
    359: GAAAGACA
    360: TTTGCGTC
    361: ATCCGGCA
    362: CCGTTATG
    363: GGTAATGT
    364: TAAGCCAC
    365: AGAAACGT
    366: CACTCAAC
    367: GCTGTGTA
    368: TTGCGTCG
    369: ACGCGGAA
    370: CGCTATCC
    371: GTTGCATG
    372: TAAATCGT
    373: AATTGAAC
    374: CCAGTGGA
    375: GTCCATTG
    376: TGGACCCT
    377: ACCCGCAC
    378: CATGCGTA
    379: GTGATAGT
    380: TGATATCG
    381: ACGAGTAG
    382: CAATCCCT
    383: GTCCAGGC
    384: TGTGTATA

Dual Index Kit TT, Set A 1000215 i7:
  adapter_type_name: Chromium
  tags:
    1: GTAACATGCG
    2: ACAGTAACTA
    3: TGCGCGGTTT
    4: TGCAATGTTC
    5: TTATTCGAGG
    6: AAGATTGGAT
    7: TGTAGTCATT
    8: ACAATGTGAA
    9: GTGGATCAAA
    10: TCTACCATTT
    11: CAATCCCGAC
    12: TTAATACGCG
    13: ATGGAGGGAG
    14: AAGGGCCGCA
    15: CATGTGGGTT
    16: TAGCATAGTG
    17: CACTACGAAA
    18: CACGGTGAAT
    19: ATGGCTTGTG
    20: CCTTCTAGAG
    21: ACCAGACAAC
    22: GAGAGGATAT
    23: ATGACGTCGC
    24: CCCGTTCTCG
    25: CTCTAGCGAG
    26: GTAGACGAAA
    27: TTCTCGATGA
    28: GCAGTATAGG
    29: AACCACGCAT
    30: CCCACCACAA
    31: GCGCTTATGG
    32: AGTTTCCTGG
    33: GTAGCCCTGT
    34: TCGGCTCTAC
    35: TCCGTTGGAT
    36: TGGTTCGGGT
    37: CGCGGTAGGT
    38: CGGCTGGATG
    39: ATAGGGCGAG
    40: AGCAAGAAGC
    41: TAACGCGTGA
    42: AATGCCATGA
    43: ACGACTACCA
    44: CCCAGCTTCT
    45: TTGAGAGTCA
    46: TTGCCCGTGC
    47: GCGGGTAAGT
    48: CCTATCCTCG
    49: TCCCAAGGGT
    50: GCCTTCGGTA
    51: CGCGCACTTA
    52: CCTGTCAGGG
    53: GTCCTTCGGC
    54: AATGTATCCA
    55: GTTTCACGAT
    56: ACCTCGAGCT
    57: CGAAGTATAC
    58: GCACTGAGAA
    59: GCTACAAAGC
    60: CGCTGAAATC
    61: GAGCAAGGGC
    62: CTCCTTTAGA
    63: TAAGCAACTG
    64: ATAAGGATAC
    65: AAGTGGAGAG
    66: TATTGAGGCA
    67: TATCAGCCTA
    68: TGGTCCCAAG
    69: TGTCCCAACG
    70: GTCCCATCAA
    71: CCGGAGGAAG
    72: AGAACTTAGA
    73: CGTGACATGC
    74: GCCCGATGGA
    75: AGAATGGTTT
    76: ATGCGAATGG
    77: CACAATCCCA
    78: CCGGCAACTG
    79: ACTTTACGTG
    80: TTATCTAGGG
    81: CGGAACCCAA
    82: TCTTACTTGC
    83: ATGGGTGAAA
    84: CGAATATTCG
    85: TCCGGGACAA
    86: TTCACACCTT
    87: GATAACCTGC
    88: ACAATCGATC
    89: CACCGCACCA
    90: CGTCAAGGGC
    91: TCGTCAAGAT
    92: GAATTGGTTA
    93: CGTCCACCTG
    94: GAGACGCACG
    95: CTTGCATAAA
    96: TGATGATTCA
