---
PN-1000212 Single Index Kit N Set A:
  adapter_type_name: Chromium
  tags:
    1: AAACGGCG
    2: CCTACCAT
    3: GGCGTTTC
    4: TTGTAAGA
    5: AGGCTACC
    6: CTAGCTGT
    7: GCCAACAA
    8: TATTGGTG
    9: AGACTTTC
    10: CCGAGGCA
    11: GATGCAGT
    12: TTCTACAG
    13: AGCTGCGT
    14: CAACCATC
    15: GTGGAGCA
    16: TCTATTAG
    17: ACGAAAGC
    18: CGCCCGTA
    19: GTTTGCCT
    20: TAAGTTAG
    21: ATCGCTCC
    22: CCGTACAG
    23: GATAGGTA
    24: TGACTAGT
    25: ATGCGATT
    26: CATATGCG
    27: GGATACGA
    28: TCCGCTAC
    29: AAACTCAT
    30: CGGGAGTA
    31: GTCACAGG
    32: TCTTGTCC
    33: AGCCCTTT
    34: CAAGTCCA
    35: GTGAGAAG
    36: TCTTAGGC
    37: AAGTTGAT
    38: CCCACCCA
    39: GGTCGAGC
    40: TTAGATTG
    41: AATCACTA
    42: CCGAGAAC
    43: GTAGTGCG
    44: TGCTCTGT
    45: ACATTCCG
    46: CTGCGGTA
    47: GACACAAT
    48: TGTGATGC
    49: AGGCTGGT
    50: CACAACTA
    51: GTTGGTCC
    52: TCATCAAG
    53: ATGGTTAG
    54: CATTGATA
    55: GCAAACGC
    56: TGCCCGCT
    57: ATAACCTA
    58: CGGTGAGC
    59: GATCTTAT
    60: TCCGAGCG
    61: AACGGTCA
    62: CCGAACTC
    63: GGTCCAAG
    64: TTATTGGT
    65: AAAGCATA
    66: CTGCAGCC
    67: GCCTTTAT
    68: TGTAGCGG
    69: ATTGGACG
    70: CAGCTTAC
    71: GGCAAGGA
    72: TCATCCTT
    73: ACGTTACA
    74: CGTAGGTT
    75: GACGACGG
    76: TTACCTAC
    77: ACTTCACT
    78: CGAAGTTG
    79: GAGCACGC
    80: TTCGTGAA
    81: AACAAGTC
    82: CGGCTCCA
    83: GTATGTAT
    84: TCTGCAGG
    85: AGTCTGTA
    86: CAGAATAG
    87: GCCTCCGT
    88: TTAGGACC
    89: ATGTCCAG
    90: CGACGTCA
    91: GCTATAGC
    92: TACGAGTT
    93: ACACCTAA
    94: CGTTTGGG
    95: GACAAACC
    96: TTGGGCTT
    97: AGAACGCC
    98: CATGGCAG
    99: GTCTTTGA
    100: TCGCAATT
    101: AGGGACTG
    102: CCTCTAAC
    103: GACAGGCT
    104: TTATCTGA
    105: ACATTGGC
    106: CTTAGTCA
    107: GAGCCCAT
    108: TGCGAATG
    109: AAATCGTC
    110: CTTCGAAT
    111: GCGATCGG
    112: TGCGATCA
    113: AGCTGACG
    114: CCGGTGTC
    115: GTAAACAT
    116: TATCCTGA
    117: AACGACAC
    118: CGTCCTCT
    119: GCATGATA
    120: TTGATGGG
    121: AGCTTCTC
    122: CCTGCGGT
    123: GTACAACG
    124: TAGAGTAA
    125: ACTGGAGC
    126: CGGTCGTG
    127: GAAATCAA
    128: TTCCATCT
    129: ATTGGGAA
    130: CAGTCTGG
    131: GGCATACT
    132: TCACACTC
    133: ATCGTACT
    134: CATCAGTG
    135: GGGACTAC
    136: TCATGCGA
    137: ATGCATTC
    138: CACTGACT
    139: GGTACGGG
    140: TCAGTCAA
    141: AGACGGAT
    142: CCTTTAGA
    143: GTCGACTC
    144: TAGACTCG
    145: ATCCAAGG
    146: CCGTTGAA
    147: GGAAGCTC
    148: TATGCTCT
    149: AACACAGC
    150: CGGTTTAG
    151: GTACGGCT
    152: TCTGACTA
    153: ATGAAGTA
    154: CGCCGAAC
    155: GAAGCTCG
    156: TCTTTCGT
    157: ATAGTATG
    158: CCGCGTCT
    159: GGCTCCAC
    160: TATAAGGA
    161: ACGGGACT
    162: CTTTCGAC
    163: GAACATGA
    164: TGCATCTG
    165: AACGCGAA
    166: CTATTTGG
    167: GCGCACCT
    168: TGTAGATC
    169: ACTCAGAC
    170: CGCTCAGG
    171: GAGGTTTA
    172: TTAAGCCT
    173: ATGCCAAA
    174: CCTTATCG
    175: GAAGTCTT
    176: TGCAGGGC
    177: ATTGAAAC
    178: CAGCCCGA
    179: GCCATTTG
    180: TGATGGCT
    181: ATGCCGGC
    182: CCTAATTA
    183: GACTTCCT
    184: TGAGGAAG
    185: AGCACTGG
    186: CATTACAC
    187: GTGCGACA
    188: TCAGTGTT
    189: AAGCATAA
    190: CCCATCGC
    191: GGTTGATG
    192: TTAGCGCT
    193: AGGTCATA
    194: CTCATCAT
    195: GCTGAGGG
    196: TAACGTCC
    197: AGGGATGA
    198: CTTCTGTT
    199: GAATGCAC
    200: TCCACACG
    201: ACACCGGG
    202: CATAATCC
    203: GGCGGAAT
    204: TTGTTCTA
    205: AACTTAGA
    206: CCGGATCC
    207: GGTCGCAT
    208: TTAACGTG
    209: AAGACGTG
    210: CCATGTGT
    211: GTTCACAA
    212: TGCGTACC
    213: ACCCGAGA
    214: CAAACTTT
    215: GGTTAGAC
    216: TTGGTCCG
    217: ATTACCGG
    218: CAGTAATT
    219: GCCGGTAA
    220: TGACTGCC
    221: AACGGGTG
    222: CTAATTCT
    223: GCTTCAAC
    224: TGGCACGA
    225: ATGATACG
    226: CCACAGAA
    227: GACTGTTC
    228: TGTGCCGT
    229: ACGTTCAC
    230: CAAGGTCT
    231: GTTAAGTG
    232: TGCCCAGA
    233: AGCTCGAG
    234: CAGGAAGA
    235: GCACGTTT
    236: TTTATCCC
    237: AATCTTTG
    238: CTCAAGAC
    239: GGATGAGT
    240: TCGGCCCA
    241: AGCCTATG
    242: CTAACGCA
    243: GCTTACAT
    244: TAGGGTGC
    245: AGTTGGGA
    246: CCAGAAAG
    247: GTGCCCTC
    248: TACATTCT
    249: AAGTACTC
    250: CTTGGAGA
    251: GGAACTCT
    252: TCCCTGAG
    253: AAGAGCGG
    254: CTTGTTAT
    255: GGCCCATC
    256: TCATAGCA
    257: ACAACTTG
    258: CTCCAACA
    259: GAGTGCGT
    260: TGTGTGAC
    261: AAGCGTGT
    262: CTTGACCG
    263: GCCACGTA
    264: TGATTAAC
    265: AGATCGGT
    266: CATCGTCG
    267: GTCATATA
    268: TCGGACAC
    269: ACCTACTG
    270: CAAGGGAC
    271: GGGACACA
    272: TTTCTTGT
    273: AGTAAGCA
    274: CCGGTAAT
    275: GTATCTTC
    276: TACCGCGG
    277: AGTTAGTT
    278: CACGCACG
    279: GTACTTAA
    280: TCGAGCGC
    281: AGTCTCAG
    282: CAATGGCA
    283: GCCGAAGT
    284: TTGACTTC
    285: ACCTGCCA
    286: CTTCATAC
    287: GGAATATG
    288: TAGGCGGT
    289: ACAGCAAC
    290: CGCAATTT
    291: GAGTTGCG
    292: TTTCGCGA
    293: ACCATTAA
    294: CTGGACGT
    295: GAACGGTC
    296: TGTTCACG
    297: ATCTGATC
    298: CGTGCTAA
    299: GAGAAGGG
    300: TCACTCCT
    301: AGATAACA
    302: CTTATTTG
    303: GCGGGCAT
    304: TACCCGGC
    305: ATTGTTTC
    306: CGCAGGAG
    307: GCACCAGT
    308: TAGTACCA
    309: ATTCGTGC
    310: CGCGTGCA
    311: GAATACTG
    312: TCGACAAT
    313: ATACTGAG
    314: CGGAGACT
    315: GATGCCTC
    316: TCCTATGA
    317: ATTTCAGC
    318: CGAGTGAT
    319: GACCGCCA
    320: TCGAATTG
    321: ACCAGTCC
    322: CTTTCCTT
    323: GGACAGGG
    324: TAGGTAAA
    325: ATGGTCGC
    326: CGACATAG
    327: GATTCGCT
    328: TCCAGATA
    329: ACCGAACA
    330: CGACTCTT
    331: GTTTGTGG
    332: TAGACGAC
    333: ATATGAGA
    334: CACCTCAG
    335: GCTACTTC
    336: TGGGAGCT
    337: ATCGCCAT
    338: CATAAAGG
    339: GGGTTTCC
    340: TCACGGTA
    341: AGCAGTTA
    342: CTTGTACC
    343: GAACCCGG
    344: TCGTAGAT
    345: AGGGCGTT
    346: CTATACGC
    347: GCTCGTCA
    348: TACATAAG
    349: AGGATCGA
    350: CACGATTC
    351: GTATCGAG
    352: TCTCGACT
    353: ACTACTGT
    354: CGGGAACG
    355: GACCTCTC
    356: TTATGGAA
    357: ACGCTTGG
    358: CGCTACAT
    359: GAAAGACA
    360: TTTGCGTC
    361: ATCCGGCA
    362: CCGTTATG
    363: GGTAATGT
    364: TAAGCCAC
    365: AGAAACGT
    366: CACTCAAC
    367: GCTGTGTA
    368: TTGCGTCG
    369: ACGCGGAA
    370: CGCTATCC
    371: GTTGCATG
    372: TAAATCGT
    373: AATTGAAC
    374: CCAGTGGA
    375: GTCCATTG
    376: TGGACCCT
    377: ACCCGCAC
    378: CATGCGTA
    379: GTGATAGT
    380: TGATATCG
    381: ACGAGTAG
    382: CAATCCCT
    383: GTCCAGGC
    384: TGTGTATA
PN-1000215/PN-3000431 Dual Index Kit TT, Set A (i7):
  adapter_type_name: Chromium
  tags:
    1: GTAACATGCG
    2: ACAGTAACTA
    3: TGCGCGGTTT
    4: TGCAATGTTC
    5: TTATTCGAGG
    6: AAGATTGGAT
    7: TGTAGTCATT
    8: ACAATGTGAA
    9: GTGGATCAAA
    10: TCTACCATTT
    11: CAATCCCGAC
    12: TTAATACGCG
    13: ATGGAGGGAG
    14: AAGGGCCGCA
    15: CATGTGGGTT
    16: TAGCATAGTG
    17: CACTACGAAA
    18: CACGGTGAAT
    19: ATGGCTTGTG
    20: CCTTCTAGAG
    21: ACCAGACAAC
    22: GAGAGGATAT
    23: ATGACGTCGC
    24: CCCGTTCTCG
    25: CTCTAGCGAG
    26: GTAGACGAAA
    27: TTCTCGATGA
    28: GCAGTATAGG
    29: AACCACGCAT
    30: CCCACCACAA
    31: GCGCTTATGG
    32: AGTTTCCTGG
    33: GTAGCCCTGT
    34: TCGGCTCTAC
    35: TCCGTTGGAT
    36: TGGTTCGGGT
    37: CGCGGTAGGT
    38: CGGCTGGATG
    39: ATAGGGCGAG
    40: AGCAAGAAGC
    41: TAACGCGTGA
    42: AATGCCATGA
    43: ACGACTACCA
    44: CCCAGCTTCT
    45: TTGAGAGTCA
    46: TTGCCCGTGC
    47: GCGGGTAAGT
    48: CCTATCCTCG
    49: TCCCAAGGGT
    50: GCCTTCGGTA
    51: CGCGCACTTA
    52: CCTGTCAGGG
    53: GTCCTTCGGC
    54: AATGTATCCA
    55: GTTTCACGAT
    56: ACCTCGAGCT
    57: CGAAGTATAC
    58: GCACTGAGAA
    59: GCTACAAAGC
    60: CGCTGAAATC
    61: GAGCAAGGGC
    62: CTCCTTTAGA
    63: TAAGCAACTG
    64: ATAAGGATAC
    65: AAGTGGAGAG
    66: TATTGAGGCA
    67: TATCAGCCTA
    68: TGGTCCCAAG
    69: TGTCCCAACG
    70: GTCCCATCAA
    71: CCGGAGGAAG
    72: AGAACTTAGA
    73: CGTGACATGC
    74: GCCCGATGGA
    75: AGAATGGTTT
    76: ATGCGAATGG
    77: CACAATCCCA
    78: CCGGCAACTG
    79: ACTTTACGTG
    80: TTATCTAGGG
    81: CGGAACCCAA
    82: TCTTACTTGC
    83: ATGGGTGAAA
    84: CGAATATTCG
    85: TCCGGGACAA
    86: TTCACACCTT
    87: GATAACCTGC
    88: ACAATCGATC
    89: CACCGCACCA
    90: CGTCAAGGGC
    91: TCGTCAAGAT
    92: GAATTGGTTA
    93: CGTCCACCTG
    94: GAGACGCACG
    95: CTTGCATAAA
    96: TGATGATTCA
Dual Index Kit TT, Set A 1000215 i5:
  adapter_type_name: Chromium
  tags:
    1: AGTGTTACCT
    2: ACAGTTCGTT
    3: CAAGGATAAA
    4: GCTTGTCGAA
    5: CTGTCCTGCT
    6: AGCGGGATTT
    7: CTTGATCGTA
    8: CGTACCGTTA
    9: GCCAACCCTG
    10: CGGGAGAGTC
    11: CCGAGTAGTA
    12: CACCTCGGGT
    13: ATAACCCATT
    14: CTGATTCCTC
    15: GATTCCTTTA
    16: CGGCTCTGTC
    17: TTAGACTGAT
    18: GTTCGTCACA
    19: GAATGTTGTG
    20: AATACAACGA
    21: AGGAACTAGG
    22: TTGAAATGGG
    23: AGGTCAGGAT
    24: GACGGATTGG
    25: TATCTTCATC
    26: CTAGTGTGGT
    27: TGTCGGGCAC
    28: TTCCGTGCAC
    29: ATTCAGGTTA
    30: ACCTCCGCTT
    31: GCCTGGCTAG
    32: TGCCACACAG
    33: GAGCATCTAT
    34: CCGATGGTCT
    35: ACGTTCTCGC
    36: GTGGCAGGAG
    37: CAGGATGTTG
    38: TGATAAGCAC
    39: TGCATCGAGT
    40: TTGTGTTTCT
    41: CCCTAACTTC
    42: TACGTAATGC
    43: ACGACCCTAA
    44: GACACCAAAC
    45: AACCTGGTAG
    46: GCGTGAGATT
    47: TAGCACTAAG
    48: GAATACTAAC
    49: TACTACCTTT
    50: CCAACGATTT
    51: CCTGTATTCT
    52: AGCCCGTAAC
    53: TCATGCACAG
    54: AATGAGCTTA
    55: TTCGGCCAAA
    56: TGTGTTCGAT
    57: GAACTTGGAG
    58: TATGCGTGAA
    59: CACGTGCCCT
    60: AGGTGTCTGC
    61: ATTGACTTGG
    62: GACATAGCTC
    63: CTATACTCAA
    64: ATAGATAGGG
    65: TTCCTGTTAC
    66: CAGGTAAGTG
    67: GTTTCGTCCT
    68: CCTCTGGCGT
    69: TCGATGTCCA
    70: CGAACGTGAC
    71: TGCGGATGTT
    72: CGAGTCCTTT
    73: ATGGTCTAAA
    74: AATCGTCTAG
    75: GAGGGTGGGA
    76: ACAAGTGTCG
    77: ATATCCACAA
    78: CGGTTTAACA
    79: TGAACGCCCT
    80: AAAGGCTCTA
    81: GATTCGAGGA
    82: TGACCTCTAG
    83: CTTGGGAATT
    84: CTGGAAGCAA
    85: GTGAATGCCA
    86: TAGTGTACAC
    87: CATTAGAAAC
    88: TGACGGAATG
    89: GACTGTCAAT
    90: TAGGTCACTC
    91: GCAACTCAGG
    92: ACTCTAGTAG
    93: CATTCATGAC
    94: CTATGAACAT
    95: ATCAGGGCTT
    96: GTAGGAGTCG
Dual Index Kit TN, Set A 1000250 i7:
  adapter_type_name: Chromium
  tags:
    1: AGTATCTGCA
    2: CATAGCATGA
    3: AAGGGTTTAC
    4: AGCGCCTTGC
    5: GTCATCCTAT
    6: CCTGGCTATA
    7: TCATCGTTCT
    8: CGTTCCACAT
    9: TCTATGAGTG
    10: TACTGCAATA
    11: GCTTAAGCAA
    12: CAGTAATACA
    13: CGACCCAGTG
    14: ACTTGTTCGA
    15: GCACTACTGA
    16: ATCTTGCAGC
    17: TTATTGACAC
    18: TGGCTACCGG
    19: GTGATCTGGG
    20: ATAGAACCAC
    21: CATAGTTCGC
    22: AACCATTAGT
    23: GTTATCACGA
    24: CAGCTGTTAT
    25: GAACAACCTT
    26: ACGTTTGATT
    27: ATGCAAGATC
    28: TTACAATCGT
    29: TCACGTTGGG
    30: TTGCGGGACT
    31: CAGGCGAATA
    32: CTACGACTGA
    33: TCTCGAATGT
    34: TGGGTGCACA
    35: TCAAAGGGTT
    36: CTGCCTGGGT
    37: TAATCTTCGG
    38: GAGCGAAAGC
    39: TAAGTAGAAG
    40: GCTGGGATGC
    41: TTTGCTGGGT
    42: ACGAGCGGAA
    43: TCAAGTAAAG
    44: GAAAGCGCGC
    45: CCATCACCAC
    46: AGCATCACAT
    47: CGAGGAGCAT
    48: CCGTCGCTGA
    49: TCCGAATAAA
    50: CCATTGTAAG
    51: GCTGCTCCCA
    52: TGTTCGCGAA
    53: CCATTAGGCG
    54: ACCATTGCAC
    55: ATCACCGTTT
    56: AAGTTAGTAC
    57: GTTTGAAAGT
    58: TAGTAGTTTG
    59: ATCTGTAGTT
    60: GCGTAACGAT
    61: CTGGTGATAA
    62: GTTCTGGAAC
    63: GACCGCCTTT
    64: GACTCAGGGT
    65: GCACGTGACA
    66: GATGGAAGGT
    67: ATGGCGCAAA
    68: TGTCAGTAAG
    69: CGTTGGTCCG
    70: CGGACGACCT
    71: TCCCGACCTG
    72: TGCACAAGCG
    73: GTCGTTGCCT
    74: ACAGGTTACG
    75: TAATGGGCAA
    76: CTACGTAGGT
    77: CTTCCTACTT
    78: TGGACCTTTG
    79: ATTGTACAGT
    80: TTCGCTTAAC
    81: TCGTACGATG
    82: AGTAGTTTGG
    83: TAACTGTAGT
    84: CCTAGGCAAA
    85: AGACGCATCT
    86: TCATATGTGA
    87: GACAATTGGG
    88: AGACGACCGA
    89: CGCGAGTAGG
    90: TCGCCATTTG
    91: AGCCTTCTCT
    92: TTAACGGACG
    93: TCGGGAGCTG
    94: CGCCCTCATC
    95: ATTGGCGCAA
    96: AGTGGAGGGA
Dual Index Kit TN, Set A 1000250 i5:
  adapter_type_name: Chromium
  tags:
    1: TCGCTAGCGA
    2: GACCTGCCTG
    3: TACTCACGCG
    4: GTACGAAGTG
    5: CTAGGGCAAA
    6: CCCTCACAAA
    7: AATTCGGGAA
    8: GAGGGAGCCA
    9: CAACCAACGA
    10: AGAGTCCATG
    11: GCCTACCGAA
    12: TTGAGCTGAG
    13: TCGCACCAAC
    14: TGGATGGGTG
    15: CACTACGGTT
    16: CGAGTAAGGA
    17: GCGAACTGAT
    18: CTGAGTCATT
    19: ACTGTGTCGC
    20: CTAACCTAAC
    21: TTTCGTAACT
    22: GTATGTCGGG
    23: GCAACACCTC
    24: AGTACGTGAG
    25: GAACTGGTAC
    26: TACTGAGAGA
    27: ACGCCTCTGA
    28: CAGATTGTAC
    29: CTTTGCTCCA
    30: TGAGGATCGC
    31: CCCTTTACCG
    32: CATCGCCCTC
    33: ACGATCGCGA
    34: CATGCATCAT
    35: GATTACTGAG
    36: GACCAATAGC
    37: AGCCATCAAT
    38: TCCTTACCAA
    39: CGCGTTTCCT
    40: GACTAACTGG
    41: CAAATTCCGG
    42: AACAACTAAG
    43: CAGTGCTGTT
    44: GAAACATATC
    45: GTGATCCCAA
    46: TCGTAGAGGA
    47: CAGTAAGTCT
    48: AGGTGTTAGT
    49: ATGCTACCGC
    50: TACGAATTGA
    51: CTACAGGGTC
    52: TCGTGAAATA
    53: GCATTTCATC
    54: ACAGTTAAGC
    55: TGTCGAGGAG
    56: ACGCGGAATA
    57: GTACGCCATG
    58: TCATCGGGCG
    59: AGGCCCAATG
    60: ATTCGTTCAA
    61: AGGGACCTGG
    62: CGGGTACTGG
    63: TTTAACTCGT
    64: GAGACCCTTC
    65: AGGAAGTCTG
    66: AAATTGAGCA
    67: CGATGCAAGC
    68: AGATGACATC
    69: GTAGCTGATA
    70: GTTGCGCCTC
    71: AACCCACCAA
    72: TGATGTTTGC
    73: AGAACTTCTT
    74: AGATAAACAG
    75: GCGCATAGGC
    76: GTCCCACTTA
    77: TCCTCCTGTA
    78: TAAATCTCTG
    79: TTGGTTACGT
    80: CCGCTCGTTA
    81: ACCCTCCCAT
    82: ATAGCATGCA
    83: ATGACCGATA
    84: CAGAAATATC
    85: TTGTACGTGG
    86: AAAGTGTTCT
    87: ACATTTGGAA
    88: CCACAGAACA
    89: CCTGGTGACA
    90: ACGGGCATGT
    91: CTGTCCGCGT
    92: CAAACGTCGC
    93: CCAGACTGCA
    94: GCGTCTACGC
    95: TCAATTGCAA
    96: TGCATAGTTT
Dual Index Kit TS, Set A 1000251 i7:
  adapter_type_name: Chromium
  tags:
    1: AATTTCGGGT
    2: TATGACGAGT
    3: TAGGGTCAAA
    4: CTTCTAATGT
    5: CACATAAACA
    6: GATAATACCG
    7: TTGGCGGCAC
    8: CAGGACTCTA
    9: CTACTGAATT
    10: ACCTGGTACA
    11: TCCTTGGAGC
    12: AGGCTGATTC
    13: ACCAATCGTG
    14: CTCAACCAGG
    15: TGATCAAAGG
    16: GACCTCTATC
    17: CAAGCGTTAG
    18: GTCACGGGTG
    19: ACCGACTGAT
    20: TTCTTTGTAG
    21: GTATAGGGTG
    22: CTGGCCGAAG
    23: CCAGACACGG
    24: AAACAGGAGA
    25: GCTACCCGGT
    26: ACCCGCTCGA
    27: GTTACTAGAT
    28: AGACAAGTCA
    29: CGCTTCCAGA
    30: TTTCGCAGGC
    31: CATTTACCGT
    32: TCTATTGACA
    33: CTCAGCGGGA
    34: GTGTCTAACT
    35: CGAGTTGGGT
    36: ACACAGACAA
    37: CGATGCCCAA
    38: ACTACGGACT
    39: TGGCCGTGAC
    40: CCCGCTTGAA
    41: TCAGAACTTT
    42: CGGCCATAGG
    43: CGCGCCAAAG
    44: ACTAAATGGG
    45: CAGAGAGGGT
    46: GCGAGTTTGG
    47: CTGAAGTTGC
    48: AGTGACCAGT
    49: TAAACCCTAG
    50: CATGCTGCTC
    51: GATCGCGGTA
    52: CTAGAAATTG
    53: TACCAGTGCG
    54: TTGAACCTCT
    55: TGAGTCAAGA
    56: CGAGCGCAGT
    57: GTCTAGTTTG
    58: CGCATTTCTC
    59: GCCACTTCGA
    60: GCGCAAACAA
    61: GTTAAACCGC
    62: GTCGCGACAA
    63: CAGAGGTAAG
    64: ATACCTAACT
    65: CCACTTACGT
    66: TCAGTGATGA
    67: TGCTTAACGT
    68: GAGTAGGATT
    69: CTTAACGCTT
    70: TATGTTGTGC
    71: TGAGTATCTG
    72: CCTCCGTGTC
    73: TACGGTTCAT
    74: CACCGTCGAT
    75: CCATGGAGGC
    76: TTATGGTGCT
    77: GAAATGACGG
    78: TAAGATGCAC
    79: TACATATGCT
    80: TGTGAATTTC
    81: CTACCTTTCT
    82: TCTAGACGAA
    83: CAGCCAGTAA
    84: GAGTCCGCAA
    85: TCTTCGAAGT
    86: ATAGTCATAC
    87: AATAGCTATC
    88: ACACCAGCCT
    89: GTACCGGTAT
    90: CCAGGGTCAA
    91: TTTGAGATAC
    92: ACGGAATTAC
    93: GCGCCACATG
    94: GAATGGAAGG
    95: ACCCAGTTGT
    96: GACAGGCGGT
Dual Index Kit TS, Set A 1000251 i5:
  adapter_type_name: Chromium
  tags:
    1: CTCTCTCCTC
    2: AGGATTCTCG
    3: TAGGCAATAA
    4: AGTGCGCACT
    5: TACTTCAAAC
    6: ACCACGTAAA
    7: GTAAGTTACT
    8: CGTAGGATGG
    9: CGCTAGCGCT
    10: TGGGTAAAGT
    11: CGTCAACCCA
    12: GCTAGATGAC
    13: TCTCCACGGG
    14: GTCTGCAGAC
    15: AACCTTACTA
    16: CGAGGTGTAA
    17: CGCGAATGCG
    18: TGTTATCGTT
    19: TCCTGGGTTC
    20: GTCCTCTAAG
    21: AAACCCTCCA
    22: CATTATTCAC
    23: AGAAAGCGGT
    24: TCGGCCCTTG
    25: ATGTAATGGA
    26: GTCACCCGTA
    27: GACTGATCAT
    28: CCAGCAGCTT
    29: TCCGGGTGCT
    30: CTCGATGCAC
    31: CACCTGTAAA
    32: GTGAACAAAC
    33: TTACGGATAA
    34: GCAAGCTCTC
    35: ACTAGAAACA
    36: AGACGCGCTA
    37: AGTGGACTTA
    38: GAAGCGCTTC
    39: AACTGTAACG
    40: GCCCAAGGTA
    41: CGCAGTCCAC
    42: AGCTTCGTTC
    43: AAATCCAAGG
    44: ACAAATCTGT
    45: CGATCGTTTA
    46: GCACCCGTAC
    47: GATCTTAAGC
    48: TTGTTAGACA
    49: CTGATAGGAA
    50: GTGGAAACCG
    51: CGGAACCGTC
    52: CTTACTTTCG
    53: TACCAGGCTC
    54: GAAGATATAG
    55: GCAGATCCTA
    56: ACCTCAACTG
    57: TGGTTGCAAC
    58: CGCACAACCA
    59: GAATACGCCA
    60: CTAGATAACT
    61: AGCCGGCTTG
    62: CAATCTGCCA
    63: TTTGCACTGA
    64: TATAATGGTG
    65: TTGAAACACG
    66: CGACTCTCGC
    67: TACACCCACA
    68: CGTATAGCAT
    69: GCTAGTGTGA
    70: ATGGCTTAAT
    71: TGACTCGTTC
    72: GTTCCAGGTA
    73: CGTCCAAGAT
    74: AGCTATTTCG
    75: CGCCTAGGTT
    76: TTATCCATGC
    77: TGGAGAAGGG
    78: TCATAGCCAA
    79: GTAATCGTGA
    80: GAACCACGTG
    81: TTCACAGGGA
    82: TGAATTAGAG
    83: GACATAATAC
    84: CTCTGGAACT
    85: ACCTGATATG
    86: GAAACTGGTC
    87: AGTGTCGCTT
    88: GCTGGTTCGT
    89: TTTGGATGGG
    90: CGACCTTGTC
    91: GCACTCCGTG
    92: GACAGGACGC
    93: CATAGTTACA
    94: GTCGCTTGTA
    95: CTTCCCACAA
    96: CTGGACTTAG
