---
# Chromium Dual Index Kit Tag Sets
# See: Intermediate files for DPL-554
# https://github.com/sanger/sequencescape/pull/4149/commits/f04b929aef53509efa41a7f5156efdf5d191840a
PN-1000215/PN-3000431 Dual Index Kit TT, Set A (i7):
  adapter_type_name: Chromium
  tags:
    1: GTAACATGCG
    2: ACAGTAACTA
    3: TGCGCGGTTT
    4: TGCAATGTTC
    5: TTATTCGAGG
    6: AAGATTGGAT
    7: TGTAGTCATT
    8: ACAATGTGAA
    9: GTGGATCAAA
    10: TCTACCATTT
    11: CAATCCCGAC
    12: TTAATACGCG
    13: ATGGAGGGAG
    14: AAGGGCCGCA
    15: CATGTGGGTT
    16: TAGCATAGTG
    17: CACTACGAAA
    18: CACGGTGAAT
    19: ATGGCTTGTG
    20: CCTTCTAGAG
    21: ACCAGACAAC
    22: GAGAGGATAT
    23: ATGACGTCGC
    24: CCCGTTCTCG
    25: CTCTAGCGAG
    26: GTAGACGAAA
    27: TTCTCGATGA
    28: GCAGTATAGG
    29: AACCACGCAT
    30: CCCACCACAA
    31: GCGCTTATGG
    32: AGTTTCCTGG
    33: GTAGCCCTGT
    34: TCGGCTCTAC
    35: TCCGTTGGAT
    36: TGGTTCGGGT
    37: CGCGGTAGGT
    38: CGGCTGGATG
    39: ATAGGGCGAG
    40: AGCAAGAAGC
    41: TAACGCGTGA
    42: AATGCCATGA
    43: ACGACTACCA
    44: CCCAGCTTCT
    45: TTGAGAGTCA
    46: TTGCCCGTGC
    47: GCGGGTAAGT
    48: CCTATCCTCG
    49: TCCCAAGGGT
    50: GCCTTCGGTA
    51: CGCGCACTTA
    52: CCTGTCAGGG
    53: GTCCTTCGGC
    54: AATGTATCCA
    55: GTTTCACGAT
    56: ACCTCGAGCT
    57: CGAAGTATAC
    58: GCACTGAGAA
    59: GCTACAAAGC
    60: CGCTGAAATC
    61: GAGCAAGGGC
    62: CTCCTTTAGA
    63: TAAGCAACTG
    64: ATAAGGATAC
    65: AAGTGGAGAG
    66: TATTGAGGCA
    67: TATCAGCCTA
    68: TGGTCCCAAG
    69: TGTCCCAACG
    70: GTCCCATCAA
    71: CCGGAGGAAG
    72: AGAACTTAGA
    73: CGTGACATGC
    74: GCCCGATGGA
    75: AGAATGGTTT
    76: ATGCGAATGG
    77: CACAATCCCA
    78: CCGGCAACTG
    79: ACTTTACGTG
    80: TTATCTAGGG
    81: CGGAACCCAA
    82: TCTTACTTGC
    83: ATGGGTGAAA
    84: CGAATATTCG
    85: TCCGGGACAA
    86: TTCACACCTT
    87: GATAACCTGC
    88: ACAATCGATC
    89: CACCGCACCA
    90: CGTCAAGGGC
    91: TCGTCAAGAT
    92: GAATTGGTTA
    93: CGTCCACCTG
    94: GAGACGCACG
    95: CTTGCATAAA
    96: TGATGATTCA
PN-1000215/PN-3000431 Dual Index Kit TT, Set A (i5):
  adapter_type_name: Chromium
  tags:
    1: AGTGTTACCT
    2: ACAGTTCGTT
    3: CAAGGATAAA
    4: GCTTGTCGAA
    5: CTGTCCTGCT
    6: AGCGGGATTT
    7: CTTGATCGTA
    8: CGTACCGTTA
    9: GCCAACCCTG
    10: CGGGAGAGTC
    11: CCGAGTAGTA
    12: CACCTCGGGT
    13: ATAACCCATT
    14: CTGATTCCTC
    15: GATTCCTTTA
    16: CGGCTCTGTC
    17: TTAGACTGAT
    18: GTTCGTCACA
    19: GAATGTTGTG
    20: AATACAACGA
    21: AGGAACTAGG
    22: TTGAAATGGG
    23: AGGTCAGGAT
    24: GACGGATTGG
    25: TATCTTCATC
    26: CTAGTGTGGT
    27: TGTCGGGCAC
    28: TTCCGTGCAC
    29: ATTCAGGTTA
    30: ACCTCCGCTT
    31: GCCTGGCTAG
    32: TGCCACACAG
    33: GAGCATCTAT
    34: CCGATGGTCT
    35: ACGTTCTCGC
    36: GTGGCAGGAG
    37: CAGGATGTTG
    38: TGATAAGCAC
    39: TGCATCGAGT
    40: TTGTGTTTCT
    41: CCCTAACTTC
    42: TACGTAATGC
    43: ACGACCCTAA
    44: GACACCAAAC
    45: AACCTGGTAG
    46: GCGTGAGATT
    47: TAGCACTAAG
    48: GAATACTAAC
    49: TACTACCTTT
    50: CCAACGATTT
    51: CCTGTATTCT
    52: AGCCCGTAAC
    53: TCATGCACAG
    54: AATGAGCTTA
    55: TTCGGCCAAA
    56: TGTGTTCGAT
    57: GAACTTGGAG
    58: TATGCGTGAA
    59: CACGTGCCCT
    60: AGGTGTCTGC
    61: ATTGACTTGG
    62: GACATAGCTC
    63: CTATACTCAA
    64: ATAGATAGGG
    65: TTCCTGTTAC
    66: CAGGTAAGTG
    67: GTTTCGTCCT
    68: CCTCTGGCGT
    69: TCGATGTCCA
    70: CGAACGTGAC
    71: TGCGGATGTT
    72: CGAGTCCTTT
    73: ATGGTCTAAA
    74: AATCGTCTAG
    75: GAGGGTGGGA
    76: ACAAGTGTCG
    77: ATATCCACAA
    78: CGGTTTAACA
    79: TGAACGCCCT
    80: AAAGGCTCTA
    81: GATTCGAGGA
    82: TGACCTCTAG
    83: CTTGGGAATT
    84: CTGGAAGCAA
    85: GTGAATGCCA
    86: TAGTGTACAC
    87: CATTAGAAAC
    88: TGACGGAATG
    89: GACTGTCAAT
    90: TAGGTCACTC
    91: GCAACTCAGG
    92: ACTCTAGTAG
    93: CATTCATGAC
    94: CTATGAACAT
    95: ATCAGGGCTT
    96: GTAGGAGTCG
PN-1000250 Dual Index Kit TN, Set A (i7):
  adapter_type_name: Chromium
  tags:
    1: AGTATCTGCA
    2: CATAGCATGA
    3: AAGGGTTTAC
    4: AGCGCCTTGC
    5: GTCATCCTAT
    6: CCTGGCTATA
    7: TCATCGTTCT
    8: CGTTCCACAT
    9: TCTATGAGTG
    10: TACTGCAATA
    11: GCTTAAGCAA
    12: CAGTAATACA
    13: CGACCCAGTG
    14: ACTTGTTCGA
    15: GCACTACTGA
    16: ATCTTGCAGC
    17: TTATTGACAC
    18: TGGCTACCGG
    19: GTGATCTGGG
    20: ATAGAACCAC
    21: CATAGTTCGC
    22: AACCATTAGT
    23: GTTATCACGA
    24: CAGCTGTTAT
    25: GAACAACCTT
    26: ACGTTTGATT
    27: ATGCAAGATC
    28: TTACAATCGT
    29: TCACGTTGGG
    30: TTGCGGGACT
    31: CAGGCGAATA
    32: CTACGACTGA
    33: TCTCGAATGT
    34: TGGGTGCACA
    35: TCAAAGGGTT
    36: CTGCCTGGGT
    37: TAATCTTCGG
    38: GAGCGAAAGC
    39: TAAGTAGAAG
    40: GCTGGGATGC
    41: TTTGCTGGGT
    42: ACGAGCGGAA
    43: TCAAGTAAAG
    44: GAAAGCGCGC
    45: CCATCACCAC
    46: AGCATCACAT
    47: CGAGGAGCAT
    48: CCGTCGCTGA
    49: TCCGAATAAA
    50: CCATTGTAAG
    51: GCTGCTCCCA
    52: TGTTCGCGAA
    53: CCATTAGGCG
    54: ACCATTGCAC
    55: ATCACCGTTT
    56: AAGTTAGTAC
    57: GTTTGAAAGT
    58: TAGTAGTTTG
    59: ATCTGTAGTT
    60: GCGTAACGAT
    61: CTGGTGATAA
    62: GTTCTGGAAC
    63: GACCGCCTTT
    64: GACTCAGGGT
    65: GCACGTGACA
    66: GATGGAAGGT
    67: ATGGCGCAAA
    68: TGTCAGTAAG
    69: CGTTGGTCCG
    70: CGGACGACCT
    71: TCCCGACCTG
    72: TGCACAAGCG
    73: GTCGTTGCCT
    74: ACAGGTTACG
    75: TAATGGGCAA
    76: CTACGTAGGT
    77: CTTCCTACTT
    78: TGGACCTTTG
    79: ATTGTACAGT
    80: TTCGCTTAAC
    81: TCGTACGATG
    82: AGTAGTTTGG
    83: TAACTGTAGT
    84: CCTAGGCAAA
    85: AGACGCATCT
    86: TCATATGTGA
    87: GACAATTGGG
    88: AGACGACCGA
    89: CGCGAGTAGG
    90: TCGCCATTTG
    91: AGCCTTCTCT
    92: TTAACGGACG
    93: TCGGGAGCTG
    94: CGCCCTCATC
    95: ATTGGCGCAA
    96: AGTGGAGGGA
PN-1000250 Dual Index Kit TN, Set A (i5):
  adapter_type_name: Chromium
  tags:
    1: TCGCTAGCGA
    2: GACCTGCCTG
    3: TACTCACGCG
    4: GTACGAAGTG
    5: CTAGGGCAAA
    6: CCCTCACAAA
    7: AATTCGGGAA
    8: GAGGGAGCCA
    9: CAACCAACGA
    10: AGAGTCCATG
    11: GCCTACCGAA
    12: TTGAGCTGAG
    13: TCGCACCAAC
    14: TGGATGGGTG
    15: CACTACGGTT
    16: CGAGTAAGGA
    17: GCGAACTGAT
    18: CTGAGTCATT
    19: ACTGTGTCGC
    20: CTAACCTAAC
    21: TTTCGTAACT
    22: GTATGTCGGG
    23: GCAACACCTC
    24: AGTACGTGAG
    25: GAACTGGTAC
    26: TACTGAGAGA
    27: ACGCCTCTGA
    28: CAGATTGTAC
    29: CTTTGCTCCA
    30: TGAGGATCGC
    31: CCCTTTACCG
    32: CATCGCCCTC
    33: ACGATCGCGA
    34: CATGCATCAT
    35: GATTACTGAG
    36: GACCAATAGC
    37: AGCCATCAAT
    38: TCCTTACCAA
    39: CGCGTTTCCT
    40: GACTAACTGG
    41: CAAATTCCGG
    42: AACAACTAAG
    43: CAGTGCTGTT
    44: GAAACATATC
    45: GTGATCCCAA
    46: TCGTAGAGGA
    47: CAGTAAGTCT
    48: AGGTGTTAGT
    49: ATGCTACCGC
    50: TACGAATTGA
    51: CTACAGGGTC
    52: TCGTGAAATA
    53: GCATTTCATC
    54: ACAGTTAAGC
    55: TGTCGAGGAG
    56: ACGCGGAATA
    57: GTACGCCATG
    58: TCATCGGGCG
    59: AGGCCCAATG
    60: ATTCGTTCAA
    61: AGGGACCTGG
    62: CGGGTACTGG
    63: TTTAACTCGT
    64: GAGACCCTTC
    65: AGGAAGTCTG
    66: AAATTGAGCA
    67: CGATGCAAGC
    68: AGATGACATC
    69: GTAGCTGATA
    70: GTTGCGCCTC
    71: AACCCACCAA
    72: TGATGTTTGC
    73: AGAACTTCTT
    74: AGATAAACAG
    75: GCGCATAGGC
    76: GTCCCACTTA
    77: TCCTCCTGTA
    78: TAAATCTCTG
    79: TTGGTTACGT
    80: CCGCTCGTTA
    81: ACCCTCCCAT
    82: ATAGCATGCA
    83: ATGACCGATA
    84: CAGAAATATC
    85: TTGTACGTGG
    86: AAAGTGTTCT
    87: ACATTTGGAA
    88: CCACAGAACA
    89: CCTGGTGACA
    90: ACGGGCATGT
    91: CTGTCCGCGT
    92: CAAACGTCGC
    93: CCAGACTGCA
    94: GCGTCTACGC
    95: TCAATTGCAA
    96: TGCATAGTTT
PN-1000251 Dual Index Kit TS, Set A (i7):
  adapter_type_name: Chromium
  tags:
    1: AATTTCGGGT
    2: TATGACGAGT
    3: TAGGGTCAAA
    4: CTTCTAATGT
    5: CACATAAACA
    6: GATAATACCG
    7: TTGGCGGCAC
    8: CAGGACTCTA
    9: CTACTGAATT
    10: ACCTGGTACA
    11: TCCTTGGAGC
    12: AGGCTGATTC
    13: ACCAATCGTG
    14: CTCAACCAGG
    15: TGATCAAAGG
    16: GACCTCTATC
    17: CAAGCGTTAG
    18: GTCACGGGTG
    19: ACCGACTGAT
    20: TTCTTTGTAG
    21: GTATAGGGTG
    22: CTGGCCGAAG
    23: CCAGACACGG
    24: AAACAGGAGA
    25: GCTACCCGGT
    26: ACCCGCTCGA
    27: GTTACTAGAT
    28: AGACAAGTCA
    29: CGCTTCCAGA
    30: TTTCGCAGGC
    31: CATTTACCGT
    32: TCTATTGACA
    33: CTCAGCGGGA
    34: GTGTCTAACT
    35: CGAGTTGGGT
    36: ACACAGACAA
    37: CGATGCCCAA
    38: ACTACGGACT
    39: TGGCCGTGAC
    40: CCCGCTTGAA
    41: TCAGAACTTT
    42: CGGCCATAGG
    43: CGCGCCAAAG
    44: ACTAAATGGG
    45: CAGAGAGGGT
    46: GCGAGTTTGG
    47: CTGAAGTTGC
    48: AGTGACCAGT
    49: TAAACCCTAG
    50: CATGCTGCTC
    51: GATCGCGGTA
    52: CTAGAAATTG
    53: TACCAGTGCG
    54: TTGAACCTCT
    55: TGAGTCAAGA
    56: CGAGCGCAGT
    57: GTCTAGTTTG
    58: CGCATTTCTC
    59: GCCACTTCGA
    60: GCGCAAACAA
    61: GTTAAACCGC
    62: GTCGCGACAA
    63: CAGAGGTAAG
    64: ATACCTAACT
    65: CCACTTACGT
    66: TCAGTGATGA
    67: TGCTTAACGT
    68: GAGTAGGATT
    69: CTTAACGCTT
    70: TATGTTGTGC
    71: TGAGTATCTG
    72: CCTCCGTGTC
    73: TACGGTTCAT
    74: CACCGTCGAT
    75: CCATGGAGGC
    76: TTATGGTGCT
    77: GAAATGACGG
    78: TAAGATGCAC
    79: TACATATGCT
    80: TGTGAATTTC
    81: CTACCTTTCT
    82: TCTAGACGAA
    83: CAGCCAGTAA
    84: GAGTCCGCAA
    85: TCTTCGAAGT
    86: ATAGTCATAC
    87: AATAGCTATC
    88: ACACCAGCCT
    89: GTACCGGTAT
    90: CCAGGGTCAA
    91: TTTGAGATAC
    92: ACGGAATTAC
    93: GCGCCACATG
    94: GAATGGAAGG
    95: ACCCAGTTGT
    96: GACAGGCGGT
PN-1000251 Dual Index Kit TS, Set A (i5):
  adapter_type_name: Chromium
  tags:
    1: CTCTCTCCTC
    2: AGGATTCTCG
    3: TAGGCAATAA
    4: AGTGCGCACT
    5: TACTTCAAAC
    6: ACCACGTAAA
    7: GTAAGTTACT
    8: CGTAGGATGG
    9: CGCTAGCGCT
    10: TGGGTAAAGT
    11: CGTCAACCCA
    12: GCTAGATGAC
    13: TCTCCACGGG
    14: GTCTGCAGAC
    15: AACCTTACTA
    16: CGAGGTGTAA
    17: CGCGAATGCG
    18: TGTTATCGTT
    19: TCCTGGGTTC
    20: GTCCTCTAAG
    21: AAACCCTCCA
    22: CATTATTCAC
    23: AGAAAGCGGT
    24: TCGGCCCTTG
    25: ATGTAATGGA
    26: GTCACCCGTA
    27: GACTGATCAT
    28: CCAGCAGCTT
    29: TCCGGGTGCT
    30: CTCGATGCAC
    31: CACCTGTAAA
    32: GTGAACAAAC
    33: TTACGGATAA
    34: GCAAGCTCTC
    35: ACTAGAAACA
    36: AGACGCGCTA
    37: AGTGGACTTA
    38: GAAGCGCTTC
    39: AACTGTAACG
    40: GCCCAAGGTA
    41: CGCAGTCCAC
    42: AGCTTCGTTC
    43: AAATCCAAGG
    44: ACAAATCTGT
    45: CGATCGTTTA
    46: GCACCCGTAC
    47: GATCTTAAGC
    48: TTGTTAGACA
    49: CTGATAGGAA
    50: GTGGAAACCG
    51: CGGAACCGTC
    52: CTTACTTTCG
    53: TACCAGGCTC
    54: GAAGATATAG
    55: GCAGATCCTA
    56: ACCTCAACTG
    57: TGGTTGCAAC
    58: CGCACAACCA
    59: GAATACGCCA
    60: CTAGATAACT
    61: AGCCGGCTTG
    62: CAATCTGCCA
    63: TTTGCACTGA
    64: TATAATGGTG
    65: TTGAAACACG
    66: CGACTCTCGC
    67: TACACCCACA
    68: CGTATAGCAT
    69: GCTAGTGTGA
    70: ATGGCTTAAT
    71: TGACTCGTTC
    72: GTTCCAGGTA
    73: CGTCCAAGAT
    74: AGCTATTTCG
    75: CGCCTAGGTT
    76: TTATCCATGC
    77: TGGAGAAGGG
    78: TCATAGCCAA
    79: GTAATCGTGA
    80: GAACCACGTG
    81: TTCACAGGGA
    82: TGAATTAGAG
    83: GACATAATAC
    84: CTCTGGAACT
    85: ACCTGATATG
    86: GAAACTGGTC
    87: AGTGTCGCTT
    88: GCTGGTTCGT
    89: TTTGGATGGG
    90: CGACCTTGTC
    91: GCACTCCGTG
    92: GACAGGACGC
    93: CATAGTTACA
    94: GTCGCTTGTA
    95: CTTCCCACAA
    96: CTGGACTTAG
PN-1000242/PN-3000483 Dual Index Kit NT, Set A (i7):
  adapter_type_name: Chromium
  tags:
    1: ATTTACCGCA
    2: CTTATTGTGG
    3: GATAGTGAAG
    4: CTGGGATTAA
    5: GCCTAGAAAT
    6: CGGTATGGAA
    7: GATGTCTGTG
    8: GCGGCGTAAA
    9: TTGTCGTAGA
    10: ATTCGTTGGG
    11: CTGTGCAATG
    12: TACACTATTC
    13: TACAAAGATG
    14: TCGGTTTAGT
    15: TGTTAGACTA
    16: TCTCCTTCGG
    17: AGTCCTGCGG
    18: GTGGCCTCAT
    19: AAAGCTGAGC
    20: AGAGCTATTT
    21: GCAGGCTTAG
    22: CTTTGCTTTG
    23: TAGAACGCTT
    24: CCTTACCCAT
    25: TTGTTCATGT
    26: CTATGGCATC
    27: GTCCAAGTCG
    28: AGGTCGTTAT
    29: CAGCTCCAAT
    30: ATGATCGCAC
    31: AATTTGACGT
    32: AAGGAACATC
    33: TCAGGAAGGA
    34: AAACCACAGT
    35: GATTTCCATC
    36: GCTGGACAGG
    37: TTTGGAGAAA
    38: CGGCGTGTTA
    39: GAGTGGCCAC
    40: GTGGGAACTT
    41: CTGTTAGAGG
    42: ATGTATCCAC
    43: CTAAATGGAT
    44: ACTTAGATGG
    45: TGTCGCTTTC
    46: TCATTTCCGC
    47: ATCAGTTACG
    48: ACCGCACCAC
    49: AGATGAGAAT
    50: GATGAGTCTG
    51: ATTTCAGTTC
    52: AGGCGCGAGT
    53: GTGTTGCGAG
    54: TTGTGCCCAG
    55: TGTAAGCTTT
    56: ACCTTTATCT
    57: CCAAAGCCGG
    58: CTCACAATAA
    59: TTGCGACGTC
    60: GAGGTCGTAC
    61: GTCTGTTCTG
    62: AGCCAACGTG
    63: GCTTCGGTCT
    64: AGTAGCCCGT
    65: AGTCATAATG
    66: TCTGTCGCAA
    67: GTACTGTCCA
    68: CCCAATGAGC
    69: TCGCTCAATC
    70: GATCCATACT
    71: AGTCTAAGAC
    72: AGATAGCATA
    73: TTCATCAGAG
    74: CATCGAGAAG
    75: AAACGGTTTA
    76: ACATTCAGGG
    77: CGTTACTAGC
    78: TTTCCATGAA
    79: TGAAACATTC
    80: TGGCGTTAAA
    81: GAAGCGCGAA
    82: ACGTATTGGG
    83: CGATAGTTCT
    84: AGAAACGGTG
    85: GTGCAGATTT
    86: TCTTTATCGG
    87: CCTCACGAAA
    88: TCAGGCGAAA
    89: ATCCGCCGAA
    90: CTTACGCGAC
    91: TACTTTAGCT
    92: AGTTGCAAGT
    93: GTTACCGAAA
    94: GAACCCGATG
    95: CTACGGGCTT
    96: AAGACATAGC
PN-1000242/PN-3000483 Dual Index Kit NT, Set A (i5):
  adapter_type_name: Chromium
  tags:
    1: GACAATAAAG
    2: AGCTGTGGGT
    3: CGTTCGCCAG
    4: AGTAAAGTTC
    5: ACTACTCCGG
    6: TGCAACTGGT
    7: CGTGCTACCG
    8: CACGCGATCA
    9: CAATGTAGCA
    10: CATCAGGAGC
    11: ATGGTGCTTT
    12: ATTGCAACGT
    13: CCGATGACGT
    14: TAAAGTGTTC
    15: TCATGACGAC
    16: TGTCCGTCGC
    17: TGACACAAGT
    18: TCGAAAGTGA
    19: CAGGAACGAG
    20: CTGGCACCCA
    21: CGTCTATTGC
    22: ACATTCATTC
    23: GTCGCAAACG
    24: TCCCGGCAAC
    25: TGACAGCTGA
    26: CTCTGAGCGC
    27: GTCATGGCAC
    28: AGGTTATCCA
    29: TAGGAGGGTG
    30: GCGGTATGTA
    31: AGAAGTGAGG
    32: TATCTGTGGG
    33: GAACGTGCTT
    34: CCGCAAATGG
    35: CTTATGGTCA
    36: TAATCTCTGT
    37: CAGCCCTTGA
    38: TGAGACGCGG
    39: GATGCACAGT
    40: GCACTTACAG
    41: CCACGCTTCG
    42: CAGGCTGAGG
    43: AATCACATAC
    44: AATGTTGAGT
    45: CCTAAAGGGT
    46: ACAGCTGTTG
    47: TACAATCTCT
    48: TCGGATTATA
    49: GTCGACGGGT
    50: TATGTAACCG
    51: GCAGCATTAA
    52: TGTGTCTATA
    53: CACTTTGAGC
    54: TTGCGAGTTG
    55: CGGACTAGTC
    56: CGAGTGCCAA
    57: ACCGTGCACA
    58: CCGTGTTTAA
    59: TTAATCCACA
    60: CAACTGCGGG
    61: TCTGATGCTT
    62: TCAAAGGAAC
    63: CGCGGGTTAG
    64: TTCGGGACCT
    65: AGGCTTGAAA
    66: ATCCGAACTG
    67: TTTGTTGGAA
    68: AGTTTCTGAT
    69: GCTTACGTGA
    70: ATCGAGAGAA
    71: CTGAAGTGAA
    72: CATTTCCGGA
    73: TTGTCGTCTC
    74: GTGCATCCGC
    75: TCTTCGTTAC
    76: GTCCTGAGAG
    77: AATGGCCATT
    78: CGGTTCTAAC
    79: CCTCCTGCCT
    80: TGTTAAGATG
    81: CAGCGAAATT
    82: CAATCGCAAA
    83: GCGATTTCCT
    84: TCACCCAGCA
    85: TAAAGGCGAT
    86: CCCAATAGCG
    87: TGCCCTGTGC
    88: TCTCTGGAAG
    89: GCTACAGAAT
    90: CCTGTCGGAT
    91: GAGTTATTTG
    92: ATACTTCATG
    93: CGTTTGAATC
    94: TCTATCCGGG
    95: AGGCGTCCCT
    96: ATGTGGACGT