Ultima P1:
  visible: true
  tags:
    1: CAGCTCGAATGCGAT
    2: CATGTGCAGCCATCGAT
    3: CATCACACATGAATGAT
    4: CTGTGTAGGCATGAT
    5: CATGTATCCTCTGAT
    6: CATATAGCCTATGAT
    7: CGATTCATGCTCGAT
    8: CACATCCTGCATGTGAT
    9: CGCGCATCCTGCATGAT
    10: CACTGCACGAATGAT
    11: CACGCACTGCCAGAT
    12: CTGCCATAGCACGAT
    13: CAGTTGTGCTGTGAT
    14: CATGGCGCGATCATGAT
    15: CTTAGATATCATGAT
    16: CATCCTGTGCGCATGAT
    17: CACGTGGCACATGAT
    18: CATGCGTCCTGTGAT
    19: CAATGCTCTGCATAGAT
    20: CTACATTGCACAGAT
    21: CATAGCGAGCCAGAT
    22: CGGAGTGCATGCATGAT
    23: CATGGAGATACTGAT
    24: CTGAGCCTGTCAGAT
    25: CTCGAGATTGATGAT
    26: CATCCATCTCATCTGAT
    27: CACTGTCAGCCAGAT
    28: CAGACTTGCTGCGAT
    29: CATATAGCAGGAGAT
    30: CATGTCTAAGATGAT
    31: CATCGCAGCTGAATGAT
    32: CTCTGTATTGCAGAT
    33: CATCATCGATTCGAT
    34: CTGTGAATATGCGAT
    35: CTGAATGATCTCGAT
    36: CAGAAGCTGCATGAGAT
    37: CTAGATTGCGCAGAT
    38: CGCATCCTCACAGAT
    39: CACAACATATCAGAT
    40: CATCCTGCATCGCAGAT
    41: CACATCAGCTCAATGAT
    42: CATGCATATAATGCGAT
    43: CTCAATGCATCAGCGAT
    44: CAATGTGTGCTAGAT
    45: CTCAGCCTCATGCTGAT
    46: CTCTCGCATGCAATGAT
    47: CTAGCAGCCAGCGAT
    48: CTGCCAGACTGTGAT
    49: CGCACTGCTCCTGAT
    50: CACATGGCAGCACAGAT
    51: CACTTGCAGATCGAT
    52: CTATGCCACAGCATGAT
    53: CAACATCAGCATGAGAT
    54: CTGCAGTGATTCATGAT
    55: CAGCACCTGCATCAGAT
    56: CTTATGCTATCAGAT
    57: CAATGCGTGCTGCAGAT
    58: CATCTCAGTGCAATGAT
    59: CATGTGCTTCGCATGAT
    60: CATGAGTGCAGCCAGAT
    61: CTCAAGCATGTGCTGAT
    62: CACAGTCAATGTGAT
    63: CACACTTGATGCGAT
    64: CATAGAGCCTCAGAT
    65: CTTGTGTCATGAGAT
    66: CAATGCACTCGAGAT
    67: CTTATGAGCGCTGAT
    68: CGTCATTGCACAGAT
    69: CATCACTGCAACGAT
    70: CTTGCATGCGATGCGAT
    71: CGTGCGCAAGCAGAT
    72: CTATCTCATAATGAT
    73: CATGGCTATGCACTGAT
    74: CTATGAATGAGCGAT
    75: CTATGCACCATCGAT
    76: CACAATGTGCGCGAT
    77: CAATGACTATCTGAT
    78: CAGCCGCTGCTCGAT
    79: CGCGCGCAGAATGAT
    80: CAGCCTCAGCGTGAT
    81: CTTGATCATACAGAT
    82: CTCTGCTGTGCAATGAT
    83: CAGTGTATTGCTGAT
    84: CTGTGCATCTGCCTGAT
    85: CTCTATGTTGCTGAT
    86: CAACTATCTGCAGAT
    87: CAGATCTCATGAATGAT
    88: CTATCATCCAGTGAT
    89: CTGCTACAAGCAGAT
    90: CAATATGCACGTGAT
    91: CACTTCTGCGATGAT
    92: CAAGCATATCTAGAT
    93: CAATGACAGCTCGAT
    94: CTGATGAGCTTGATGAT
    95: CATATGACCTGAGAT
    96: CAGCCGATATCAGAT

Ultima P2:
  visible: true
  tags:
    97: CAGTCAGTTGCAGAT
    98: CAACAGATGTATGAT
    99: CTCATCTGCGCAATGAT
    100: CGGATCATGCGTGAT
    101: CTATTGCATGCTCTGAT
    102: CTACCTGATGCAGAT
    103: CATATAATCACAGAT
    104: CATGCAGCGCTAATGAT
    105: CATGGCGCAGTGCTGAT
    106: CTGAGAATGTGTGAT
    107: CATGCATGGTACGAT
    108: CATGCATGCGAGGAGAT
    109: CAATCTGCATACGAT
    110: CAGCATGAGCGCCAGAT
    111: CTTATCTGATCTGAT
    112: CATCCAGCGCATGTGAT
    113: CAGTTCATCTGTGAT
    114: CAACATACATCAGAT
    115: CGGCTAGATGCAGAT
    116: CAGTTATGTGCTGAT
    117: CTGCCGAGCAGCATGAT
    118: CTGCCTCAGATCATGAT
    119: CTGATCAGTGGCGAT
    120: CTGCTGCGGAGCATGAT
    121: CAGTGCTGTGGCATGAT
    122: CACATATGGCATATGAT
    123: CAGATCGCCACAGAT
    124: CACGGCTCAGATGAT
    125: CTTGATGATAGTGAT
    126: CAACTGCACATAGAT
    127: CGCATACATCCTGAT
    128: CATCTCTGGCTGCAGAT
    129: CATCTGGTGCATGTGAT
    130: CAGCAGCTTCGCGAT
    131: CGCATATGGCAGCAGAT
    132: CACAGCACCGCTGAT
    133: CTAGCATCTGGTGAT
    134: CTTCAGCATACAGAT
    135: CATGCAGATGGCGAGAT
    136: CAGATCTATCCAGAT
    137: CTTCATGCATCTCAGAT
    138: CATGCAAGTGTGATGAT
    139: CTGTTCGCTGCAGAT
    140: CTCAGATCCTGCATGAT
    141: CACACAGATAATGAT
    142: CGATGCTCTGGCGAT
    143: CAGATCCATCATCTGAT
    144: CTGCACCATCATATGAT
    145: CATGCTATAGCAATGAT
    146: CATCTGCACATGGCGAT
    147: CGCTGCATGAAGATGAT
    148: CTATTCAGATGCATGAT
    149: CTCGCGCAATGCGAT
    150: CGCGCAGATGGCATGAT
    151: CAGTGAATCATCGAT
    152: CATGCAACACTAGAT
    153: CTATTATGATATGAT
    154: CTCAGAAGCATCGAT
    155: CTTCATATCTGAGAT
    156: CAATAGCTATGAGAT
    157: CATGGATAGCTGCAGAT
    158: CATAATATCTGCGAT
    159: CGCATGCATCCTGAGAT
    160: CAGCACAGAGGAGAT
    161: CAACTGCGCTCTGAT
    162: CACAAGATGACAGAT
    163: CAGATGACATTAGAT
    164: CATGGCTCACATATGAT
    165: CAAGAGATGCATCTGAT
    166: CATGACCGCTGTGAT
    167: CGCATCTGGCGCGAT
    168: CTTAGCTGTGATGAT
    169: CTCGCAATAGATGAT
    170: CACTCTCTCAATGAT
    171: CACTGCCTGATGATGAT
    172: CTCTATTCATATGAT
    173: CTTGAGCGCACTGAT
    174: CGCTGATCAGGCGAT
    175: CGCTCTGTTGATGAT
    176: CTCAACATATCTGAT
    177: CATGCGGCGCAGCAGAT
    178: CTTGCTGTGCGCGAT
    179: CATAGCGTTCATGAT
    180: CGCACATAGCCTGAT
    181: CTTCTCATGTCAGAT
    182: CAGCCATCTGCTGAGAT
    183: CACTCAGCGCCAGAT
    184: CAACATCTGATAGAT
    185: CTGCTCCGCATCGAT
    186: CTATCGCTTGATGAT
    187: CTCTTCTCAGCAGAT
    188: CATGGTGTGCACGAT
    189: CATATCATCTTAGAT
    190: CGGTGCTGCTATGAT
    191: CTGTCAGCCTATGAT
    192: CATGATCACACAATGAT
