Ultima P3:
  visible: true
  adapter_type_name: Ultima
  tags:
    1: CTGCACATTGTAGAT
    2: CTCATGGTATATGAT
    3: CTGCATGCTGGCGTGAT
    4: CGGCACGATGCTGAT
    5: CTCTTCATGAGCATGAT
    6: CTCATGGAGCATATGAT
    7: CATACTGCCTATGAT
    8: CAATGCATCTATATGAT
    9: CGAGCACAATGCATGAT
    10: CGGCAGCAGACTGAT
    11: CAACATGCACATCTGAT
    12: CGTGCATGGCATCTGAT
    13: CTACAGCAATGTGAT
    14: CATCAGTCCTGCGAT
    15: CAAGCGACATGCGAT
    16: CATGCTCAATATCTGAT
    17: CGACTCATGCCTGAT
    18: CATGGCATACTGCTGAT
    19: CAATCGCATCGTGAT
    20: CGGCACTGCAGTGAT
    21: CGGATCGCATGCGAT
    22: CTATTGCTCTGCATGAT
    23: CATCTGCGGCACATGAT
    24: CATCGATGCAGAATGAT
    25: CACATGACCAGCGAT
    26: CAATGCTGTAGTGAT
    27: CGACATGCACCTGAT
    28: CGCAAGCATGTCGAT
    29: CATGCTCGGCTGCTGAT
    30: CAAGTCTGCTCAGAT
    31: CATCATTGATCATCGAT
    32: CACTCACAATGCATGAT
    33: CATGTGGCTATCATGAT
    34: CATGTATGCGCAATGAT
    35: CTTGCGCTCTCAGAT
    36: CGCGCACAATATGAT
    37: CAGCGCACCAGCATGAT
    38: CTGCTATCTGGTGAT
    39: CGATATCATGGTGAT
    40: CATGCATGTGGATAGAT
    41: CTCTGCTCCTGCGAT
    42: CATCGCACCAGAGAT
    43: CAATCTGATATGATGAT
    44: CATACTGCAGGAGAT
    45: CTTCATGACAGAGAT
    46: CTACATCATGGCATGAT
    47: CGCTGTTGCATGATGAT
    48: CTTCACTCATGAGAT
    49: CATGCGCTTACAGAT
    50: CAGCATCTCTGCCTGAT
    51: CACTGCCATATCATGAT
    52: CTCAGCTGCGGCGAT
    53: CATGCAGAGCGCCTGAT
    54: CAATGCTATCGAGAT
    55: CAGATAAGAGCAGAT
    56: CAGAGCCACTCAGAT
    57: CATGTAATATCAGAT
    58: CAGCGCATGATCCTGAT
    59: CATAGATAGCCAGAT
    60: CACTAGCATGGCGAT
    61: CAATAGCATCGAGAT
    62: CTTCTGTGAGATGAT
    63: CTCTGCTCATTCATGAT
    64: CACAATAGCGATGAT
    65: CTGTAGGCATCTGAT
    66: CAACAGCTCTCTGAT
    67: CAGACACAATATGAT
    68: CTAGCAAGATCAGAT
    69: CTTGAGACATGAGAT
    70: CTCAGATGTCCAGAT
    71: CAGCCGCATGCACAGAT
    72: CTCGCATGTGGAGAT
    73: CACATGCATGTCCTGAT
    74: CGCGGCTGATATGAT
    75: CTGTGACAAGCTGAT
    76: CATGCGAGCATGGTGAT
    77: CAATACATGATCGAT
    78: CATGGACATATGCAGAT
    79: CAGCGCGCTGGCATGAT
    80: CATGCGTCACCTGAT
    81: CTGCATGTTGCTGAGAT
    82: CATCCTGCGATAGAT
    83: CAATATCTGAGTGAT
    84: CTGTGCAGGAGTGAT
    85: CGATGTGCCATAGAT
    86: CTCACATGGAGAGAT
    87: CAGAACATGTCAGAT
    88: CGCACAATGCGAGAT
    89: CATGCACAGAATGTGAT
    90: CGTATGGCAGCTGAT
    91: CTGATGGTGCTCATGAT
    92: CTCAGCCATGCGATGAT
    93: CATGCACAAGATCAGAT
    94: CTCTGTTGCTCAGAT
    95: CACAGCGCTCCAGAT
    96: CACAGAAGATGCGAT

UG-RD-1916 (Solaris 2.0 V1 PCR-Free Adapters for Ultima Genomics P4):
  visible: true
  adapter_type_name: Ultima
  tags:
    1: CATCATGCTCCGCTGAT
    2: CTTGCTATGAGCGAT
    3: CATGTATCAGGTGAT
    4: CATGCGCAATGTATGAT
    5: CATGTGAGCGGTGAT
    6: CGCACAAGTCATGAT
    7: CATGCAATACATGAGAT
    8: CATCTATCAGGCGAT
    9: CGAGCATCAGGTGAT
    10: CAAGACTGATATGAT
    11: CATGCGGAGTGAGAT
    12: CAGATATAGCCTGAT
    13: CAAGAGAGAGCTGAT
    14: CTATCAAGCTCAGAT
    15: CAGAATACATGCGAT
    16: CTCAAGCGCACAGAT
    17: CACACACAACATGAT
    18: CTTACATGTCATGAT
    19: CAGAAGAGATATGAT
    20: CAGAGCGCCGCAGAT
    21: CGCTCAACATGCGAT
    22: CATGACAGTAATGAT
    23: CATGCAATCACATCGAT
    24: CAGTTGATACATGAT
    25: CTGTGACATAATGAT
    26: CATAGTGCTGCAATGAT
    27: CACGAGCGCAATGAT
    28: CACAATGCAGATGTGAT
    29: CTGCGCAGCATCCTGAT
    30: CAAGACATCAGAGAT
    31: CATGCTTGTGTCATGAT
    32: CAGTGCGACAATGAT
    33: CATATGGTGACAGAT
    34: CAATGATAGTGTGAT
    35: CATAGCAGCAACATGAT
    36: CATGACACCAGTGAT
    37: CAATCTCAGCAGATGAT
    38: CTCGATGAGCCTGAT
    39: CAACACTCTGCAGAT
    40: CTTAGCATCACTGAT
    41: CTGTTGTGATCAGAT
    42: CAAGTGTGCGCAGAT
    43: CATGAGCATGGTCTGAT
    44: CACTGATGCATGGAGAT
    45: CTTATATCTCATGAT
    46: CATCAGCTGAAGATGAT
    47: CACACATCCAGCGAT
    48: CAACATGTGATCGAT
    49: CGGCTATGCATCGAT
    50: CAAGTGAGCTGCGAT
    51: CAATAGACAGCTGAT
    52: CAGTCTGATCCTGAT
    53: CTTGCATAGCGTGAT
    54: CTCGTGGCATGCATGAT
    55: CGCTGCCTGCTGCTGAT
    56: CATAGTTCATCTGAT
    57: CAATCAGCAGACGAT
    58: CATGAGCATGAGGCGAT
    59: CACATCAGTGGCGAT
    60: CTGCATGCACACCTGAT
    61: CTACTGGCAGCTGAT
    62: CTATTGATATGAGAT
    63: CTCATAGCCTGCATGAT
    64: CACATGCTCAATGCGAT
    65: CAACTCATATGCGAT
    66: CATGGCTGTCTCGAT
    67: CATCTAGCCATAGAT
    68: CAGTCAACAGCAGAT
    69: CTAGCGCAATGAGAT
    70: CATCATTAGCGCGAT
    71: CGCTTCATGCTGCAGAT
    72: CTGATGGCGCGCATGAT
    73: CTGATCTATGCAATGAT
    74: CACTGAATGTGCGAT
    75: CGCAATCTATCTGAT
    76: CGGCATGCTGTAGAT
    77: CTCATGTGTGGTGAT
    78: CTGCATATTGTGATGAT
    79: CGCATGTATGGCGAT
    80: CATATAACATGCATGAT
    81: CATATCTCCTGTGAT
    82: CTGATACAGAATGAT
    83: CTGTGCGCCATAGAT
    84: CAGAGCATGCTAATGAT
    85: CATAAGATGCGTGAT
    86: CATACAAGAGCTGAT
    87: CATGCTGAATGTGTGAT
    88: CTCATGATTACTGAT
    89: CATGACGCATTAGAT
    90: CGTGTGCAACATGAT
    91: CGGTGCATATCAGAT
    92: CTTCGATGCTGTGAT
    93: CAATAGATGTGAGAT
    94: CGATGCCATCTCATGAT
    95: CGATCACAAGCTGAT
    96: CTGTGATGTAATGAT
