---
Dual Index Tag2 sequences:
  visible: true
  tags:
    1: TATAGCCT
    2: ATAGAGGC
    3: CCTATCCT
    4: GGCTCTGA
    999: TCTTTCCC
Dual Index Tag2 sequences set B:
  visible: true
  tags:
    5: AGGCGAAG
    6: TAATCTTA
    7: CAGGACGT
    8: GTACTGAC
Dual Index Tag2 sequences set C:
  visible: true
  tags:
    9: CTCTCTAT
    10: TATCCTCT
    11: AGAGTAGA
    12: GTAAGGAG
Dual Index Tag2 sequences set D:
  visible: true
  tags:
    13: CTATTAAG
    14: AAGGCTAT
    15: GAGCCTTA
    16: TTATGCGA
