# frozen_string_literal: true

# Autogenerated migration to convert orders to utf8mb4
class MigrateOrdersToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('orders', from: 'latin1', to: 'utf8mb4')
  end
end
