# frozen_string_literal: true

# Autogenerated migration to convert qc_decisions to utf8mb4
class MigrateQcDecisionsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('qc_decisions', from: 'utf8', to: 'utf8mb4')
  end
end
