# frozen_string_literal: true

# Autogenerated migration to convert descriptors to utf8mb4
class MigrateDescriptorsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('descriptors', from: 'latin1', to: 'utf8mb4')
  end
end
