# frozen_string_literal: true

# Autogenerated migration to convert faculty_sponsors to utf8mb4
class MigrateFacultySponsorsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('faculty_sponsors', from: 'latin1', to: 'utf8mb4')
  end
end
