# frozen_string_literal: true

# Autogenerated migration to convert asset_shapes to utf8mb4
class MigrateAssetShapesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('asset_shapes', from: 'utf8', to: 'utf8mb4')
  end
end
