# frozen_string_literal: true

# Autogenerated migration to convert qc_assays to utf8mb4
class MigrateQcAssaysToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('qc_assays', from: 'latin1', to: 'utf8mb4')
  end
end
