# frozen_string_literal: true

# Autogenerated migration to convert qc_metrics to utf8mb4
class MigrateQcMetricsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('qc_metrics', from: 'latin1', to: 'utf8mb4')
  end
end
