# frozen_string_literal: true

# Autogenerated migration to convert suppliers to utf8mb4
class MigrateSuppliersToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('suppliers', from: 'latin1', to: 'utf8mb4')
  end
end
