# frozen_string_literal: true

# Autogenerated migration to convert asset_audits to utf8mb4
class MigrateAssetAuditsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('asset_audits', from: 'latin1', to: 'utf8mb4')
  end
end
