# frozen_string_literal: true

# Autogenerated migration to convert roles_users to utf8mb4
class MigrateRolesUsersToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('roles_users', from: 'latin1', to: 'utf8mb4')
  end
end
