# frozen_string_literal: true

# Autogenerated migration to convert product_product_catalogues to utf8mb4
class MigrateProductProductCataloguesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('product_product_catalogues', from: 'latin1', to: 'utf8mb4')
  end
end
