# frozen_string_literal: true

# Autogenerated migration to convert specific_tube_creation_purposes to utf8mb4
class MigrateSpecificTubeCreationPurposesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('specific_tube_creation_purposes', from: 'utf8', to: 'utf8mb4')
  end
end
