# frozen_string_literal: true

# Autogenerated migration to convert programs to utf8mb4
class MigrateProgramsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('programs', from: 'latin1', to: 'utf8mb4')
  end
end
