# frozen_string_literal: true

# Autogenerated migration to convert request_type_plate_purposes to utf8mb4
class MigrateRequestTypePlatePurposesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('request_type_plate_purposes', from: 'latin1', to: 'utf8mb4')
  end
end
