# frozen_string_literal: true

# Autogenerated migration to convert transfer_request_collections to utf8mb4
class MigrateTransferRequestCollectionsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('transfer_request_collections', from: 'latin1', to: 'utf8mb4')
  end
end
