# frozen_string_literal: true

# Autogenerated migration to convert families to utf8mb4
class MigrateFamiliesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('families', from: 'latin1', to: 'utf8mb4')
  end
end
