# frozen_string_literal: true

# Autogenerated migration to convert custom_metadatum_collections to utf8mb4
class MigrateCustomMetadatumCollectionsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('custom_metadatum_collections', from: 'latin1', to: 'utf8mb4')
  end
end
