# frozen_string_literal: true

# Autogenerated migration to convert roles to utf8mb4
class MigrateRolesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('roles', from: 'latin1', to: 'utf8mb4')
  end
end
