# frozen_string_literal: true

# Autogenerated migration to convert requests to utf8mb4
class MigrateRequestsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('requests', from: 'latin1', to: 'utf8mb4')
  end
end
