# frozen_string_literal: true

# Autogenerated migration to convert study_reports to utf8mb4
class MigrateStudyReportsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('study_reports', from: 'latin1', to: 'utf8mb4')
  end
end
