# frozen_string_literal: true

# Autogenerated migration to convert aliquots to utf8mb4
class MigrateAliquotsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('aliquots', from: 'latin1', to: 'utf8mb4')
  end
end
