# frozen_string_literal: true

# Autogenerated migration to convert controls to utf8mb4
class MigrateControlsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('controls', from: 'latin1', to: 'utf8mb4')
  end
end
