# frozen_string_literal: true

# Autogenerated migration to convert messengers to utf8mb4
class MigrateMessengersToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('messengers', from: 'utf8', to: 'utf8mb4')
  end
end
