# frozen_string_literal: true

# Autogenerated migration to convert tag_layout_template_submissions to utf8mb4
class MigrateTagLayoutTemplateSubmissionsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('tag_layout_template_submissions', from: 'latin1', to: 'utf8mb4')
  end
end
