# frozen_string_literal: true

# Autogenerated migration to convert billing_items to utf8mb4
class MigrateBillingItemsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('billing_items', from: 'latin1', to: 'utf8mb4')
  end
end
