# frozen_string_literal: true

# Autogenerated migration to convert bait_libraries to utf8mb4
class MigrateBaitLibrariesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('bait_libraries', from: 'latin1', to: 'utf8mb4')
  end
end
