# frozen_string_literal: true

# Autogenerated migration to convert custom_texts to utf8mb4
class MigrateCustomTextsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('custom_texts', from: 'latin1', to: 'utf8mb4')
  end
end
