# frozen_string_literal: true

# Autogenerated migration to convert data_release_study_types to utf8mb4
class MigrateDataReleaseStudyTypesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('data_release_study_types', from: 'latin1', to: 'utf8mb4')
  end
end
