# frozen_string_literal: true

# Autogenerated migration to convert primer_panels to utf8mb4
class MigratePrimerPanelsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('primer_panels', from: 'latin1', to: 'utf8mb4')
  end
end
