# frozen_string_literal: true

# Autogenerated migration to convert projects to utf8mb4
class MigrateProjectsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('projects', from: 'latin1', to: 'utf8mb4')
  end
end
