# frozen_string_literal: true

# Autogenerated migration to convert pipelines_request_types to utf8mb4
class MigratePipelinesRequestTypesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('pipelines_request_types', from: 'latin1', to: 'utf8mb4')
  end
end
