# frozen_string_literal: true

# Autogenerated migration to convert sample_registrars to utf8mb4
class MigrateSampleRegistrarsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('sample_registrars', from: 'latin1', to: 'utf8mb4')
  end
end
