# frozen_string_literal: true

# Autogenerated migration to convert aliquot_indices to utf8mb4
class MigrateAliquotIndicesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('aliquot_indices', from: 'utf8', to: 'utf8mb4')
  end
end
