# frozen_string_literal: true

# Autogenerated migration to convert transfer_requests to utf8mb4
class MigrateTransferRequestsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('transfer_requests', from: 'latin1', to: 'utf8mb4')
  end
end
