# frozen_string_literal: true

# Autogenerated migration to convert library_types to utf8mb4
class MigrateLibraryTypesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('library_types', from: 'utf8', to: 'utf8mb4')
  end
end
