# frozen_string_literal: true

# Autogenerated migration to convert plate_purpose_relationships to utf8mb4
class MigratePlatePurposeRelationshipsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('plate_purpose_relationships', from: 'latin1', to: 'utf8mb4')
  end
end
