# frozen_string_literal: true

# Autogenerated migration to convert tag_layout_templates to utf8mb4
class MigrateTagLayoutTemplatesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('tag_layout_templates', from: 'latin1', to: 'utf8mb4')
  end
end
