# frozen_string_literal: true

# Autogenerated migration to convert volume_updates to utf8mb4
class MigrateVolumeUpdatesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('volume_updates', from: 'latin1', to: 'utf8mb4')
  end
end
