# frozen_string_literal: true

# Autogenerated migration to convert work_order_types to utf8mb4
class MigrateWorkOrderTypesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('work_order_types', from: 'latin1', to: 'utf8mb4')
  end
end
