# frozen_string_literal: true

# Autogenerated migration to convert request_information_types to utf8mb4
class MigrateRequestInformationTypesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('request_information_types', from: 'latin1', to: 'utf8mb4')
  end
end
