# frozen_string_literal: true

# Autogenerated migration to convert tags to utf8mb4
class MigrateTagsToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('tags', from: 'latin1', to: 'utf8mb4')
  end
end
