# frozen_string_literal: true

# Autogenerated migration to convert study_samples to utf8mb4
class MigrateStudySamplesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('study_samples', from: 'latin1', to: 'utf8mb4')
  end
end
