# frozen_string_literal: true

# Autogenerated migration to convert tag_group_adapter_types to utf8mb4
class MigrateTagGroupAdapterTypesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('tag_group_adapter_types', from: 'latin1', to: 'utf8mb4')
  end
end
