# frozen_string_literal: true

# Autogenerated migration to convert order_roles to utf8mb4
class MigrateOrderRolesToUtf8mb4 < ActiveRecord::Migration[5.1]
  include MigrationExtensions::EncodingChanges

  def change
    change_encoding('order_roles', from: 'utf8', to: 'utf8mb4')
  end
end
