# These purposes are associated with the Limber Cardinal pipeline.
# They are in a separate file to allow us to soft-release them before
# the real release.
---
limber_cardinal:
  name: Cardinal
  asset_type: Well
  order: 1
  request_class_name: IlluminaHtp::Requests::StdLibraryRequest
  for_multiplexing: false
  billable: true
  product_line_name: Illumina-Htp
  library_types:
    - Cardinal
  acceptable_plate_purposes:
    - LCA Blood Array
limber_cardinal_banking:
  name: Cardinal
  asset_type: Well
  order: 1
  request_class_name: IlluminaHtp::Requests::StdLibraryRequest
  for_multiplexing: false
  billable: true
  product_line_name: Illumina-Htp
  library_types:
    - Cardinal Banking
  acceptable_plate_purposes:
    - LCA Blood Bank
