# These purposes are associated with the Limber Cardinal pipeline.
# They are in a separate file to allow us to soft-release them before
# the real release.
---
limber_cardinal:
  name: Cardinal
  asset_type: SampleTube
  order: 1
  request_class_name: IlluminaHtp::Requests::StdLibraryRequest
  for_multiplexing: false
  billable: true
  product_line_name: Cardinal
  library_types:
    - Chromium single cell 3 prime v3
  acceptable_purposes:
    - LCA Blood Vac
limber_cardinal_banking:
  name: Cardinal Banking
  asset_type: SampleTube
  order: 1
  request_class_name: CustomerRequest
  for_multiplexing: false
  billable: true
  product_line_name: Cardinal
  acceptable_purposes:
    - LCA Blood Vac
