# These request types  associated with the LCA DNAseq/RNA pipeline.
# They are in a separate file to allow us to soft-release them before
# the real release.
---
lca_seq_dna_rna:
  name: LCA seq DNA RNA
  asset_type: Well
  order: 1
  request_class_name: IlluminaHtp::Requests::StdLibraryRequest
  for_multiplexing: false
  billable: true
  product_line_name: Illumina-Htp
  #library_types:
  #  - Cardinal
  acceptable_plate_purposes:
    - Lysate LCA