# Request type for scRNA Core 'Donor Pooling' and 'cDNA Prep' submission.
# There is only one request type for this submission.
# - asset_type is the type of asset that is being requested.
# - acceptable_purposes is where the request type can be used.
#
---
limber_scrna_core_cdna_prep_v2:
  name: scRNA Core cDNA Prep
  asset_type: SampleTube
  order: 1
  request_class_name: IlluminaHtp::Requests::StdLibraryRequest
  for_multiplexing: false
  billable: true
  product_line_name: Short Read
  acceptable_purposes:
    - LRC Bank Seq
    - LRC Bank Spare
  library_types:
    - Chromium single cell 5 prime HT v2
    # - Chromium single cell 3 prime HT v3
    # - Chromium single cell BCR HT
    # - Chromium single cell TCR HT
limber_scrna_core_cdna_prep_input:
  name: scRNA Core cDNA Prep Input
  asset_type: Well
  order: 1
  request_class_name: IlluminaHtp::Requests::StdLibraryRequest
  for_multiplexing: false
  billable: true
  product_line_name: Short Read
  acceptable_purposes:
    - LRC PBMC Pools Input
  library_types:
    - Chromium single cell 5 prime HT v2
    # - Chromium single cell 3 prime HT v3
    # - Chromium single cell BCR HT
    # - Chromium single cell TCR HT
limber_scrna_core_chromium_ht_aggregation:
  name: scRNA Core Chromium HT Aggregation
  asset_type: Well
  order: 1
  request_class_name: CustomerRequest
  for_multiplexing: false
  billable: true
  product_line_name: Short Read
  # NB. alternate faculty input plate route here as well as standard route
  acceptable_purposes:
    - LRC HT 5p cDNA PCR XP
    - LRC HT 5p cDNA Input
limber_scrna_core_chromium_ht:
  name: scRNA Core Chromium HT
  asset_type: Well
  order: 1
  request_class_name: IlluminaHtp::Requests::StdLibraryRequest
  for_multiplexing: false
  billable: true
  product_line_name: Short Read
  acceptable_purposes:
    - LRC HT 5p Cherrypick