# Request type for scRNA Core 'Donor Pooling' and 'cDNA Prep' submission.
# There is only one request type for this submission.
# - asset_type is the type of asset that is being requested.
# - acceptable_purposes is where the request type can be used.
#
---
limber_scrna_core_cdna_prep_v2:
  name: scRNA Core cDNA Prep
  asset_type: SampleTube
  order: 1
  request_class_name: IlluminaHtp::Requests::StdLibraryRequest
  for_multiplexing: false
  billable: true
  product_line_name: Short Read
  acceptable_purposes:
    - LRC Bank Seq
    - LRC Bank Spare
  library_types:
    - Chromium single cell 5 prime HT v2
    # - Chromium single cell 3 prime HT v3
    # - Chromium single cell BCR HT
    # - Chromium single cell TCR HT
