# Request type for scRNA Core 'Donor Pooling' and 'cDNA Prep' submission.
# There is only one request type for this submission.
# - asset_type is the type of asset that is being requested.
# - acceptable_purposes is where the request type can be used.
#
---
limber_scrna_core_cdna_prep_gem_x_5p:
  name: scRNA Core cDNA Prep GEM-X 5p
  asset_type: SampleTube
  order: 1
  request_class_name: PbmcPoolingCustomerRequest
  for_multiplexing: false
  billable: true
  product_line_name: Short Read
  acceptable_purposes:
    - LRC Bank Seq
    - LRC Bank Spare
    - LRC Bank Input
limber_scrna_core_cdna_prep_gem_x_5p_gems_input:
  name: scRNA Core cDNA Prep GEM-X 5p GEMs Input
  asset_type: Well
  order: 1
  request_class_name: CustomerRequest
  for_multiplexing: false
  billable: true
  product_line_name: Short Read
  acceptable_purposes:
    - LRC GEM-X 5p GEMs Input
    - LRC GEM-X 5p GEMs Input CITE
limber_scrna_core_aggregation:
  name: scRNA Core Aggregation
  asset_type: Well
  order: 1
  request_class_name: CustomerRequest
  for_multiplexing: false
  billable: true
  product_line_name: Short Read
  # NB. alternate faculty input plate route here as well as standard route
  acceptable_purposes:
    - LRC GEM-X 5p cDNA PCR XP
    - LRC GEM-X 5p cDNA Input
limber_scrna_core_cdna_pcr_cite:
  name: scRNA Core cDNA PCR CITE
  asset_type: Well
  order: 1
  request_class_name: IlluminaHtp::Requests::StdLibraryRequest
  for_multiplexing: false
  billable: true
  product_line_name: Short Read
  acceptable_purposes:
    - LRC GEM-X 5p cDNA PCR CITE
  library_types:
    - Chromium single cell GEM-X 5p v3 cell surface protein
