# Request types for Targeted NanoSeq
---
# TODO: uncomment and remove copy from 004_limber_high_throughput.yml when remove WIP flag
# limber_targeted_nanoseq:
#   name: Limber Targeted NanoSeq
#   asset_type: Well
#   order: 1
#   request_class_name: IlluminaHtp::Requests::StdLibraryRequest
#   billable: true
#   product_line_name: Illumina-HTP
#   acceptable_purposes:
#     - LTN Stock
#     - LTN Cherrypick
#   library_types:
#     - Targeted Nanoseq
limber_targeted_nanoseq_isc_prep:
  name: Limber Targeted NanoSeq ISC Prep
  asset_type: Well
  order: 1
  request_class_name: CustomerRequest
  for_multiplexing: false
  billable: true
  product_line_name: Short Read
  acceptable_purposes:
    - LTN AL Lib
