# Request types for LCM Triomics DNA WGS and EMSeq
---
limber_lcm_triomics:
  name: LCM Triomics
  asset_type: Well
  order: 1
  request_class_name: IlluminaHtp::Requests::StdLibraryRequest
  for_multiplexing: false
  billable: true
  product_line_name: Short Read
  library_types:
    - LCM Triomics EMSeq
  acceptable_purposes:
    - LCMT Lysate
