# Request types for LCM Triomics DNA WGS and EMSeq
---
limber_lcm_triomics:
  name: LCM Triomics
  asset_type: Well
  order: 1
  request_class_name: CustomerRequest
  for_multiplexing: false
  billable: true
  product_line_name: Short Read
  acceptable_purposes:
    - LCMT Lysate
