---
limber_bge_pcr_free:
  asset_type: Well
  order: 1
  request_class_name: IlluminaHtp::Requests::StdLibraryRequest
  billable: true
  product_line_name: Illumina-HTP
  name: Limber BGE PCR Free
  acceptable_purposes:
    - PF Cherrypicked
  library_types:
    - HiSeqX PCR free
    - Chromium single cell CNV
    - DAFT-seq
    - PCR Free 384
    - BGE
limber_bge_isc:
  asset_type: Well
  order: 1
  billable: true
  product_line_name: Illumina-HTP
  name: Limber BGE ISC
  request_class_name: Pulldown::Requests::IscLibraryRequest
  acceptable_purposes:
    - LB Cherrypick
  library_types:
    - Agilent Pulldown
    - Twist Pulldown
    - BGE
