# Request types for Ultima UG200 sequencing platform.
---
ultima_u_g_200_sequencing:
  name: Ultima UG200 sequencing
  asset_type: LibraryTube
  order: 2
  initial_state: pending
  billable: true
  product_line_name: Ultima
  request_class_name: UltimaUG200SequencingRequest
  request_purpose: standard
