# Request types for Ultima UG200 sequencing platform.
---
limber_ultima_ug200_htp_pcr_free:
  name: Limber Ultima UG200 HTP PCR Free
  order: 1
  request_class_name: IlluminaHtp::Requests::StdLibraryRequest
  asset_type: Well
  for_multiplexing: false
  billable: true
  product_line_name: Ultima # same as UG100
  acceptable_purposes:
    - UPF2 Cherrypicked
  library_types:
    - Ultima High Throughput PCR Free 96 # same as UG100
limber_multiplexing_ultima_ug200:
  name: Limber Multiplexing Ultima UG200
  asset_type: Well
  order: 2
  request_class_name: Request::Multiplexing
  for_multiplexing: true
  product_line_name: Ultima # same as UG100
  target_purpose_name: UPF2 EqVol Norm
ultima_ug200_sequencing:
  name: Ultima UG200 sequencing
  asset_type: LibraryTube
  order: 2
  initial_state: pending
  billable: true
  # Using same product line name as Ultima UG100
  product_line_name: Ultima # same as UG100
  request_class_name: UltimaUG200SequencingRequest
  request_purpose: standard
