---
Pre-Extracted Plate:
  target_type: "Plate"
  stock_plate: true
  barcode_printer_type: "96 Well Plate"
SWGA Stock:
  target_type: "Plate"
  stock_plate: true
  barcode_printer_type: "96 Well Plate"
  plate_creator: true
