# These purposes are associated with the Limber Cardinal pipeline.
# They are in a separate file to allow us to soft-release them before
# the real release.
---
LCA Blood Array:
  type: PlatePurpose::Input
  stock_plate: true
  cherrypickable_target: false
