# Plate purposes for LCM Triomics WGS and EMSeq
---
LCMT Lysate:
  type: PlatePurpose::Input
  stock_plate: true
  cherrypickable_target: false
LCMT DNA Lib PCR:
  type: PlatePurpose::Intermediate
  stock_plate: true
  cherrypickable_target: false
