# frozen_string_literal: true
# A class for requests generated by auto-submission for the Duplex-Seq and Targeted Nanoseq pipelines
class DilutionAndCleanupRequest < CustomerRequest
  # TODO: remove
  YES_OR_NO = ['Y', 'N'].freeze

  has_metadata as: Request do
    include Pulldown::Requests::BaitLibraryRequest::BaitMetadata

    custom_attribute(:pcr_cycles, integer: true, minimum: 0, required: false, validator: true)
    # custom_attribute(:bait_library_id, integer: true, minimum: 0, required: false, validator: true)
    # These 4 fields are inside the json field stored_metadata
    # TODO: use a boolean here
    custom_attribute(:submit_for_sequencing, in: YES_OR_NO, required: false, validator: true)
    custom_attribute(:sub_pool, integer: true, minimum: 0, required: false, validator: true)
    custom_attribute(:coverage, integer: true, minimum: 0, required: false, validator: true)
    custom_attribute(:diluent_volume, positive_float: true, required: false, validator: true)
  end
end
