# frozen_string_literal: true
require 'find'

# This file was automatically generated by `rails g record_loader`
module RecordLoader
  # This forms the standard base class for record loaders in your
  # application, allowing for easy configuration.
  # @see https://rubydoc.info/github/sanger/record_loader/
  class ApplicationRecordLoader < RecordLoader::Base
    # Uses the standard RailsAdapter
    # @see https://rubydoc.info/github/sanger/record_loader/RecordLoader/Adapter
    adapter RecordLoader::Adapter::Rails.new

    def wip_list
      wip_files = []
      wip_files_path = Rails.root.join('config/default_records')
      Find.find(wip_files_path) { |path| wip_files << path if /\wip\.yml$/.match?(path) }
      wip_files
    end
  end
end
