---
FragmentSizeRequiredFromInformationTypeForUltimaUG200:
  pipeline_name: Ultima UG200
  request_information_type_key: fragment_size_required_from

FragmentSizeRequiredToInformationTypeForUltimaUG200:
  pipeline_name: Ultima UG200
  request_information_type_key: fragment_size_required_to

WaferSizeInformationTypeForUltimaUG200:
  pipeline_name: Ultima UG200
  request_information_type_key: wafer_size

OTRecipeInformationTypeForUltima:
  pipeline_name: Ultima
  request_information_type_key: ot_recipe
