---
ABgene_0765:
  maximum_volume: 800
ABgene_0800:
  maximum_volume: 180
FluidX075:
  maximum_volume: 500
FluidX05:
  maximum_volume: 520
FluidX03:
  maximum_volume: 280
KingFisher 96 2ml:
  maximum_volume: 2000
Optical96 and Base:
  maximum_volume: 250
Bio-Rad_96PCR:
  maximum_volume: 200
4titude 96:
  maximum_volume: 180
TwinTecOnRedBlockOnAdapter:
  maximum_volume: 150
