name: Trigger build and append on release

on:
  workflow_dispatch: # temporary to test
    inputs:
      upload_url:
        description: "Release upload URL"
        required: true
        type: string
  push:

jobs:
  trigger_build_and_append:
    uses: sanger/.github/.github/workflows/build-and-append.yml@y25-099-migrate-actions
    with:
      upload_url: ${{ github.event.release.upload_url }}
