name: Check docker image building process

on:
  pull_request:

env:
  IMAGE_NAME: ${{ github.repository }}/${{ github.event.repository.name }}  

jobs:
  build:
    name: Check docker image building process
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: >-
          docker-compose build

      - name: Start stack and wait for all healthy
        run: |
          RESET_DATABASE="true" docker-compose up
        timeout-minutes: 5

      - name: Stop stack
        run: >-
          docker-compose down
