name: Check docker image building process

on:
  pull_request:

env:
  IMAGE_NAME: ${{ github.repository }}/${{ github.event.repository.name }}  

jobs:
  build:
    name: Check docker image building process
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: >-
          docker-compose build

      # Test that the stack wil start all required services and wait until the specified string is
      # displayed returning success, or wait until 5 minutes has passed and fail
      - name: Start stack and check correct start
        run: >-
          docker-compose up | grep -q "Listening on http://0.0.0.0"
        timeout-minutes: 5

      - name: Stop stack
        run: >-
          docker-compose down
