name: Javascript testing

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: sanger/.github/.github/actions/setup/checkout@master

      - name: Setup Node
        uses: sanger/.github/.github/actions/setup/node@master

      - name: Install
        run: yarn install

      - name: Run yarn test
        run: yarn test
