name: Unit tests

on:
  push:
    branches:
      - y25-099-6-migrate-actions

jobs:
  js_tests:
    name: Javascript tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: sanger/.github/.github/actions/setup/checkout@master

      - name: Setup Node
        uses: sanger/.github/.github/actions/setup/node@master

      - name: Install
        run: yarn install

      - name: Run yarn test
        run: yarn test
