name: Unit tests

on:
  push:
  pull_request:
    types:
      # defaults
      - opened
      - synchronize
      - reopened
      # custom
      - ready_for_review # required for Github-created PRs

jobs:
  js_tests:
    name: Javascript tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: sanger/.github/.github/actions/setup/checkout@master

      - name: Setup Node
        uses: sanger/.github/.github/actions/setup/node@master

      - name: Install
        run: yarn install
