name: Update Rubocop

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Every sunday at 10 am
    - cron: "0 10 * * 0"

jobs:
  update_rubocop:
    uses: sanger/.github/.github/workflows/update-rubocop.yml@master
