# frozen_string_literal: true

require 'rails_helper'

RSpec.describe Api::SampleIo do
  subject do
    create(
      :sample,
      name: 'sample_testing_messages',
      component_samples: [comp_sample1, comp_sample2],
      updated_by_manifest: true,
      control: true,
      control_type: 'positive',
      sample_metadata_attributes: {
        supplier_name: 'A name',
        phenotype: 'positive',
        gc_content: 'Neutral',
        dna_source: 'Genomic',
        volume: 'N/A',
        sibling: '209_210',
        is_resubmitted: true,
        date_of_sample_collection: '02-Oct',
        date_of_sample_extraction: '02-Oct',
        sample_extraction_method: '5',
        sample_purified: 'N',
        purification_method: 'Other',
        concentration: '100',
        concentration_determined_by: 'Nanodrop',
        sample_type: 'MDA',
        sample_storage_conditions: '+4C',
        genotype: 'WT',
        age: '10 weeks',
        cell_type: 'iPSC-derived microglia',
        disease_state: 'Healthy',
        compound: 'lomitapide',
        dose: '10 uM',
        immunoprecipitate: 'antiKdm1a, ab17721, 4ug/IP',
        growth_condition: 'Oxford N2 media without geltrex',
        organism_part: 'Primary T cells',
        time_point: '2020-03-18',
        disease: 'Tumour Growing',
        subject: '19',
        treatment: '10uM lomitapide in 0.1% ethanol',
        date_of_consent_withdrawn: DateTime.new(2021, 3, 19, 13, 36, 51),
        user_id_of_consent_withdrawn: user.id,
        reference_genome_id: reference_genome.id,
        organism: 'rat',
        sample_ebi_accession_number: 18_374_739_430,
        sample_common_name: 'mouse',
        sample_description: 'desc',
        sample_taxon_id: 2,
        father: 'fred',
        mother: 'frieda',
        replicate: 'yes',
        ethnicity: 'stuff',
        gender: 'female',
        cohort: 'this one',
        country_of_origin: 'uk',
        geographical_region: 'cambridge',
        sample_public_name: 'public_name',
        sample_sra_hold: 'Hold',
        sample_strain_att: 'stuff about strain',
        consent_withdrawn: false,
        donor_id: 2,
        developmental_stage: 'thing',
        huMFre_code: '23/21'
      }
    )
  end

  let(:user) { create(:user) }
  let(:reference_genome) { create(:reference_genome) }
  let(:comp_sample1) { create(:sample) }
  let(:comp_sample2) { create(:sample) }

  let(:expected_json) do
    {
      'uuid' => subject.uuid,
      'id' => subject.id,
      'name' => 'sample_testing_messages',
      'sanger_sample_id' => subject.sanger_sample_id,
      'control' => true,
      'control_type' => 'positive',
      'replicate' => 'yes',
      'organism' => 'rat',
      'strain' => 'stuff about strain',
      'ethnicity' => 'stuff',
      'mother' => 'frieda',
      'public_name' => 'public_name',
      'accession_number' => '18374739430',
      'common_name' => 'mouse',
      'taxon_id' => 2,
      'country_of_origin' => 'uk',
      'gender' => 'Female',
      'sample_visibility' => 'Hold',
      'geographical_region' => 'cambridge',
      'description' => 'desc',
      'father' => 'fred',
      'cohort' => 'this one',
      'empty_supplier_sample_name' => false,
      'supplier_name' => 'A name',
      'updated_by_manifest' => true,
      'phenotype' => 'positive',
      'gc_content' => 'Neutral',
      'dna_source' => 'Genomic',
      'customer_measured_volume' => 'N/A',
      'sibling' => '209_210',
      'is_resubmitted' => true,
      'date_of_sample_collection' => '02-Oct',
      'date_of_sample_extraction' => '02-Oct',
      'extraction_method' => '5',
      'purified' => 'N',
      'purification_method' => 'Other',
      'customer_measured_concentration' => '100',
      'concentration_determined_by' => 'Nanodrop',
      'sample_type' => 'MDA',
      'storage_conditions' => '+4C',
      'genotype' => 'WT',
      'age' => '10 weeks',
      'cell_type' => 'iPSC-derived microglia',
      'disease_state' => 'Healthy',
      'compound' => 'lomitapide',
      'dose' => '10 uM',
      'immunoprecipitate' => 'antiKdm1a, ab17721, 4ug/IP',
      'growth_condition' => 'Oxford N2 media without geltrex',
      'organism_part' => 'Primary T cells',
      'time_point' => '2020-03-18',
      'disease' => 'Tumour Growing',
      'subject' => '19',
      'treatment' => '10uM lomitapide in 0.1% ethanol',
      'date_of_consent_withdrawn' => '2021-03-19 13:36:51',
      'marked_as_consent_withdrawn_by' => user.login,
      'consent_withdrawn' => false,
      'developmental_stage' => 'thing',
      'donor_id' => '2',
      'reference_genome' => 'ReferenceGenome1',
      'component_sample_uuids' => [{ uuid: comp_sample1.uuid }, { uuid: comp_sample2.uuid }],
      'huMFre_code' => '23/21'
    }
  end

  it_behaves_like('an IO object')
end
