#!/bin/sh
# take parametes?
#RUBY=1.8.6 #-p399
#RAILS=2.2.2

gem install rails -v=2.2.2 #RY!
gem install rcov -v=0.9.8
gem install curb -v'~>0.5.9.0'
rake gems:install
rake gems:install RAILS_ENV=test
